# Generated by Django 5.2.1 on 2025-06-21 20:01

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('overall_rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('categories', models.JSONField(default=dict)),
                ('comments', models.TextField(blank=True)),
                ('testimonial', models.TextField(blank=True)),
                ('is_public', models.BooleanField(default=False)),
                ('response', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EventFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('category', models.CharField(choices=[('CONTRACT', 'Contract Document'), ('QUOTE', 'Quote/Proposal'), ('PAYMENT', 'Payment Document'), ('REQUIREMENTS', 'Requirements Doc'), ('PHOTO', 'Photo'), ('OTHER', 'Other')], max_length=50)),
                ('file', models.FileField(upload_to='event_files/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'jpg', 'jpeg', 'png'])])),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('mime_type', models.CharField(max_length=100)),
                ('size', models.PositiveIntegerField()),
                ('version', models.PositiveIntegerField(default=1)),
                ('is_public', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at', '-version'],
            },
        ),
        migrations.CreateModel(
            name='EventProductOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('final_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('num_participants', models.PositiveIntegerField(blank=True, null=True)),
                ('num_nights', models.PositiveIntegerField(blank=True, null=True)),
                ('excess_hours', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EventTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('due_date', models.DateTimeField()),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('URGENT', 'Urgent')], max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('BLOCKED', 'Blocked'), ('CANCELLED', 'Cancelled')], max_length=20)),
                ('completion_notes', models.TextField(blank=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('is_visible_to_client', models.BooleanField(default=False)),
                ('requires_client_input', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['due_date', 'priority'],
            },
        ),
        migrations.CreateModel(
            name='EventTimeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('action_type', models.CharField(choices=[('STATUS_CHANGE', 'Status Changed'), ('STAGE_CHANGE', 'Stage Changed'), ('QUOTE_CREATED', 'Quote Created'), ('QUOTE_UPDATED', 'Quote Updated'), ('QUOTE_ACCEPTED', 'Quote Accepted'), ('CONTRACT_SENT', 'Contract Sent'), ('CONTRACT_SIGNED', 'Contract Signed'), ('PAYMENT_RECEIVED', 'Payment Received'), ('NOTE_ADDED', 'Note Added'), ('FILE_UPLOADED', 'File Uploaded'), ('TASK_COMPLETED', 'Task Completed'), ('FEEDBACK_RECEIVED', 'Feedback Received'), ('CLIENT_MESSAGE', 'Client Message'), ('SYSTEM_UPDATE', 'System Update')], max_length=50)),
                ('description', models.TextField()),
                ('action_data', models.JSONField(blank=True, null=True)),
                ('is_public', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='event',
            options={},
        ),
        migrations.RemoveField(
            model_name='event',
            name='venue',
        ),
    ]
