# Generated by Django 5.2.1 on 2025-06-21 20:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_eventfeedback_eventfile_eventproductoption_eventtask_and_more'),
        ('products', '0002_discount_currency'),
        ('workflows', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='current_stage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='workflows.workflowstage'),
        ),
        migrations.AddField(
            model_name='event',
            name='last_contacted',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='payment_status',
            field=models.CharField(choices=[('UNPAID', 'Unpaid'), ('PARTIALLY_PAID', 'Partially Paid'), ('PAID', 'Paid')], default='UNPAID', max_length=20),
        ),
        migrations.AddField(
            model_name='event',
            name='total_amount_due',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='total_amount_paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='event',
            name='workflow_template',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='workflows.workflowtemplate'),
        ),
        migrations.AddField(
            model_name='eventfeedback',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='events.event'),
        ),
        migrations.AddField(
            model_name='eventfeedback',
            name='response_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedback_responses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='eventfeedback',
            name='submitted_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='eventfile',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='events.event'),
        ),
        migrations.AddField(
            model_name='eventfile',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='eventproductoption',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_products', to='events.event'),
        ),
        migrations.AddField(
            model_name='eventproductoption',
            name='product_option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.productoption'),
        ),
        migrations.AddField(
            model_name='event',
            name='product_options',
            field=models.ManyToManyField(through='events.EventProductOption', to='products.productoption'),
        ),
        migrations.AddField(
            model_name='eventtask',
            name='assigned_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='eventtask',
            name='completed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='eventtask',
            name='dependencies',
            field=models.ManyToManyField(blank=True, related_name='dependent_tasks', to='events.eventtask'),
        ),
        migrations.AddField(
            model_name='eventtask',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='events.event'),
        ),
        migrations.AddField(
            model_name='eventtask',
            name='workflow_stage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='workflows.workflowstage'),
        ),
        migrations.AddField(
            model_name='eventtimeline',
            name='actor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_actions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='eventtimeline',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline', to='events.event'),
        ),
        migrations.AddConstraint(
            model_name='eventfeedback',
            constraint=models.UniqueConstraint(fields=('event', 'submitted_by'), name='unique_event_feedback_per_user'),
        ),
        migrations.AlterUniqueTogether(
            name='eventproductoption',
            unique_together={('event', 'product_option')},
        ),
        migrations.AddIndex(
            model_name='eventtask',
            index=models.Index(fields=['event', 'status', 'due_date'], name='events_even_event_i_954331_idx'),
        ),
        migrations.AddIndex(
            model_name='eventtimeline',
            index=models.Index(fields=['event', 'action_type', '-created_at'], name='events_even_event_i_35b2de_idx'),
        ),
    ]
