# Generated by Django 5.2.1 on 2025-08-24 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_current_stage_event_last_contacted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='preferences',
            field=models.JSONField(blank=True, default=dict, help_text='Client preferences'),
        ),
    ]
