# Generated by Django 5.2.1 on 2025-08-26 00:14
# Performance optimization indexes for Event domain

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_event_preferences'),
    ]

    operations = [
        # Add composite indexes for common query patterns
        migrations.AddIndex(
            model_name='event',
            index=models.Index(
                fields=['client', 'status', '-start_date'],
                name='event_client_status_date_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(
                fields=['event_type', 'status'],
                name='event_type_status_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(
                fields=['payment_status', '-start_date'],
                name='event_payment_date_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(
                fields=['workflow_template', 'current_stage'],
                name='event_workflow_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(
                fields=['status', '-created_at'],
                name='event_status_created_idx'
            ),
        ),
        
        # Add indexes for EventTask common queries
        migrations.AddIndex(
            model_name='eventtask',
            index=models.Index(
                fields=['event', 'status', 'due_date'],
                name='task_event_status_due_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='eventtask',
            index=models.Index(
                fields=['assigned_to', 'status'],
                name='task_assigned_status_idx'
            ),
        ),
        
        # Add index for EventTimeline queries
        migrations.AddIndex(
            model_name='eventtimeline',
            index=models.Index(
                fields=['event', '-created_at'],
                name='timeline_event_created_idx'
            ),
        ),
        
        # Add index for EventFile queries
        migrations.AddIndex(
            model_name='eventfile',
            index=models.Index(
                fields=['event', 'category', 'is_public'],
                name='file_event_category_public_idx'
            ),
        ),
    ]
