# Generated by Django 5.2.1 on 2025-08-27 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_add_performance_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='event',
            name='event_workflow_idx',
        ),
        migrations.RemoveIndex(
            model_name='eventfile',
            name='file_event_category_public_idx',
        ),
        migrations.RemoveIndex(
            model_name='eventtask',
            name='task_event_status_due_idx',
        ),
        migrations.RemoveIndex(
            model_name='eventtask',
            name='task_assigned_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='eventtimeline',
            name='timeline_event_created_idx',
        ),
        migrations.RenameIndex(
            model_name='event',
            new_name='events_even_client__23c4d6_idx',
            old_name='event_client_status_date_idx',
        ),
        migrations.RenameIndex(
            model_name='event',
            new_name='events_even_event_t_938c6a_idx',
            old_name='event_type_status_idx',
        ),
        migrations.RenameIndex(
            model_name='event',
            new_name='events_even_payment_c877f7_idx',
            old_name='event_payment_date_idx',
        ),
        migrations.RenameIndex(
            model_name='event',
            new_name='events_even_status_0dedab_idx',
            old_name='event_status_created_idx',
        ),
    ]
