# Generated by Django 5.2.1 on 2025-10-04 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_remove_event_event_workflow_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='completion_type',
            field=models.CharField(blank=True, choices=[('payment', 'Payment Completion'), ('quote', 'Quote Request')], help_text='How this event was completed in the booking flow', max_length=20, null=True),
        ),
    ]
