# Generated by Django 5.2.1 on 2025-12-16 06:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_alter_event_created_at_alter_event_updated_at_and_more'),
        ('products', '0004_productoption_maximum_guests_and_more'),
        ('workflows', '0007_alter_workflowstage_automation_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='can_rebook',
            field=models.BooleanField(default=True, help_text='Whether this cancelled event can be rebooked'),
        ),
        migrations.AddField(
            model_name='event',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, help_text='When the event was cancelled', null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='cancelled_reason',
            field=models.CharField(blank=True, choices=[('CLIENT_REQUEST', 'Client Requested'), ('PAYMENT_TIMEOUT', 'Payment Deadline Expired'), ('DATE_TAKEN', 'Date Taken by Another Booking'), ('ADMIN', 'Admin Cancelled')], help_text='Reason for cancellation', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='date_blocked',
            field=models.BooleanField(default=False, help_text="Whether this event's date is officially blocked"),
        ),
        migrations.AddField(
            model_name='event',
            name='date_blocked_at',
            field=models.DateTimeField(blank=True, help_text='When the date was officially blocked', null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='downpayment_deadline',
            field=models.DateTimeField(blank=True, help_text='Deadline for downpayment before auto-cancellation', null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='original_event',
            field=models.ForeignKey(blank=True, help_text='If this is a rebooked event, reference to original', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rebooked_events', to='events.event'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['date_blocked', 'start_date'], name='events_even_date_bl_295877_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['downpayment_deadline', 'payment_status'], name='events_even_downpay_7df7ac_idx'),
        ),
    ]
