# Generated by Django 5.2.1 on 2025-12-16 07:12

from django.db import migrations


def set_date_blocked_for_confirmed_events(apps, schema_editor):
    """
    Data migration for backwards compatibility:
    Set date_blocked=True for all CONFIRMED events.
    This preserves existing behavior where CONFIRMED events block dates.
    """
    Event = apps.get_model('events', 'Event')
    # Update all CONFIRMED events to have date_blocked=True
    updated_count = Event.objects.filter(status='CONFIRMED').update(date_blocked=True)
    if updated_count > 0:
        print(f"\n    Set date_blocked=True for {updated_count} CONFIRMED events")


def reverse_set_date_blocked(apps, schema_editor):
    """
    Reverse migration: Set date_blocked=False for all events
    """
    Event = apps.get_model('events', 'Event')
    Event.objects.all().update(date_blocked=False)


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_event_can_rebook_event_cancelled_at_and_more'),
    ]

    operations = [
        migrations.RunPython(
            set_date_blocked_for_confirmed_events,
            reverse_set_date_blocked
        ),
    ]
