# Generated by Django 5.2.1 on 2025-12-17 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_set_date_blocked_for_confirmed_events'),
        ('sales', '0004_alter_eventquote_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='accepted_quote',
            field=models.ForeignKey(blank=True, help_text='The accepted quote for this event', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_for_event', to='sales.eventquote'),
        ),
    ]
