# Generated by Django 5.2.1 on 2025-12-18 05:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_add_accepted_quote_to_event'),
        ('products', '0005_add_is_tax_inclusive_to_productoption'),
        ('sales', '0005_eventquote_service_charge_amount'),
        ('workflows', '0007_alter_workflowstage_automation_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='actual_check_in_time',
            field=models.DateTimeField(blank=True, help_text='Actual check-in time', null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='actual_checkout_time',
            field=models.DateTimeField(blank=True, help_text='Actual checkout time', null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='check_in_notes',
            field=models.TextField(blank=True, help_text='Notes from check-in (condition, issues, etc.)'),
        ),
        migrations.AddField(
            model_name='event',
            name='check_in_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('CHECKED_IN', 'Checked In'), ('CHECKED_OUT', 'Checked Out'), ('NO_SHOW', 'No Show')], default='PENDING', help_text='Current check-in/out status', max_length=20),
        ),
        migrations.AddField(
            model_name='event',
            name='checked_in_by',
            field=models.ForeignKey(blank=True, help_text='Staff who performed check-in', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events_checked_in', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='event',
            name='checked_out_by',
            field=models.ForeignKey(blank=True, help_text='Staff who performed checkout', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events_checked_out', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='event',
            name='checkout_notes',
            field=models.TextField(blank=True, help_text='Notes from checkout (condition, damages, etc.)'),
        ),
        migrations.AddField(
            model_name='event',
            name='date_held_at',
            field=models.DateTimeField(blank=True, help_text='When the date was first held', null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='date_hold_expires_at',
            field=models.DateTimeField(blank=True, help_text='When the temporary hold expires (null for permanent blocks)', null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='date_hold_extended_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of times the hold has been extended'),
        ),
        migrations.AddField(
            model_name='event',
            name='date_hold_status',
            field=models.CharField(choices=[('NONE', 'No Hold'), ('TEMPORARY_HOLD', 'Temporary Hold'), ('PERMANENT_BLOCK', 'Permanently Blocked')], default='NONE', help_text="Current hold status for this event's date", max_length=20),
        ),
        migrations.AddField(
            model_name='event',
            name='last_rescheduled_at',
            field=models.DateTimeField(blank=True, help_text='When the event was last rescheduled', null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='late_checkout_fee_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Late checkout fee amount applied', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='late_checkout_fee_applied',
            field=models.BooleanField(default=False, help_text='Whether late checkout fee has been applied'),
        ),
        migrations.AddField(
            model_name='event',
            name='original_start_date',
            field=models.DateTimeField(blank=True, help_text='Original start date before any rescheduling', null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='reschedule_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of times this event has been rescheduled'),
        ),
        migrations.AddField(
            model_name='event',
            name='scheduled_check_in_time',
            field=models.DateTimeField(blank=True, help_text='Scheduled check-in time (defaults to start_date)', null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='scheduled_checkout_time',
            field=models.DateTimeField(blank=True, help_text='Scheduled checkout time (defaults to end_date)', null=True),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['date_hold_status', 'date_hold_expires_at'], name='events_even_date_ho_322e9a_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['check_in_status', 'start_date'], name='events_even_check_i_32baf8_idx'),
        ),
    ]
