# Generated by Django 5.2.1 on 2025-12-18 06:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_event_actual_check_in_time_and_more'),
        ('products', '0005_add_is_tax_inclusive_to_productoption'),
        ('sales', '0005_eventquote_service_charge_amount'),
        ('venues', '0001_initial'),
        ('workflows', '0007_alter_workflowstage_automation_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='early_checkin_fee',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Early check-in fee amount', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='early_checkin_hours',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Hours early for check-in', max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='early_checkin_requested',
            field=models.BooleanField(default=False, help_text='Whether early check-in was requested'),
        ),
        migrations.AddField(
            model_name='event',
            name='early_checkin_time',
            field=models.DateTimeField(blank=True, help_text='Requested early check-in time', null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='egress_end_time',
            field=models.DateTimeField(blank=True, help_text='Calculated egress (teardown) end time', null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='ingress_start_time',
            field=models.DateTimeField(blank=True, help_text='Calculated ingress (setup) start time', null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='late_checkout_hours',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Hours late for checkout', max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='late_checkout_requested',
            field=models.BooleanField(default=False, help_text='Whether late checkout was requested'),
        ),
        migrations.AddField(
            model_name='event',
            name='late_checkout_time',
            field=models.DateTimeField(blank=True, help_text='Requested late checkout time', null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='program_duration_hours',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Program duration in hours', max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='program_end_time',
            field=models.DateTimeField(blank=True, help_text="Client's program end time", null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='program_start_time',
            field=models.DateTimeField(blank=True, help_text="Client's program start time", null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='venue',
            field=models.ForeignKey(blank=True, help_text='Primary venue for this event', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='venues.venue'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['venue', 'start_date'], name='events_even_venue_i_0543fa_idx'),
        ),
    ]
