# Generated by Django 5.2.1 on 2025-12-18 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0013_add_venue_and_timing_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='lead_source',
            field=models.CharField(blank=True, choices=[('FACEBOOK', 'Facebook'), ('REFERRAL', 'Referral'), ('WALKIN', 'Walk-in'), ('CLIENT_PORTAL', 'Client Portal'), ('OTHER', 'Other')], max_length=50),
        ),
    ]
