# Generated by Django 5.2.1 on 2025-12-18 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0014_add_lead_source_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='num_participants',
            field=models.PositiveIntegerField(blank=True, help_text='Total number of guests/participants for this event', null=True),
        ),
    ]
