# Generated by Django 5.2.1 on 2026-01-12 09:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0015_add_guest_count_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventDateReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('days_before', models.PositiveIntegerField(help_text='Number of days before event this reminder was sent')),
                ('sent_at', models.DateTimeField(auto_now_add=True, help_text='When this reminder was sent')),
                ('communication_record_id', models.UUIDField(blank=True, help_text='UUID of the CommunicationRecord for tracking delivery status', null=True)),
                ('event', models.ForeignKey(help_text='The event this reminder was sent for', on_delete=django.db.models.deletion.CASCADE, related_name='date_reminders', to='events.event')),
            ],
            options={
                'verbose_name': 'Event Date Reminder',
                'verbose_name_plural': 'Event Date Reminders',
                'ordering': ['-sent_at'],
                'indexes': [models.Index(fields=['event', 'days_before'], name='events_even_event_i_773e96_idx'), models.Index(fields=['sent_at'], name='events_even_sent_at_18257e_idx')],
                'unique_together': {('event', 'days_before')},
            },
        ),
    ]
