# Generated by Django 5.2.1 on 2026-01-14 03:22

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0016_eventdatereminder'),
    ]

    operations = [
        migrations.CreateModel(
            name='DateReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('token', models.UUIDField(db_index=True, default=uuid.uuid4, help_text='Unique token for identifying this reservation', unique=True)),
                ('target_date', models.DateField(db_index=True, help_text='The date being reserved')),
                ('booking_session_id', models.CharField(db_index=True, help_text='The booking session that created this reservation', max_length=255)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Payment'), ('CONFIRMED', 'Confirmed'), ('RELEASED', 'Released'), ('EXPIRED', 'Expired')], default='PENDING', help_text='Current status of the reservation', max_length=20)),
                ('expires_at', models.DateTimeField(help_text='When this reservation expires (5 minutes from creation)')),
                ('confirmed_event_id', models.IntegerField(blank=True, help_text='The event ID if this reservation was confirmed', null=True)),
            ],
            options={
                'verbose_name': 'Date Reservation',
                'verbose_name_plural': 'Date Reservations',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['target_date', 'status'], name='events_date_target__aab6c4_idx'), models.Index(fields=['booking_session_id'], name='events_date_booking_e4d796_idx'), models.Index(fields=['status', 'expires_at'], name='events_date_status_56358c_idx')],
            },
        ),
    ]
