# Generated by Django 5.2.1 on 2026-01-22 14:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0017_add_date_reservation'),
        ('products', '0013_remove_tax_rate_from_productoption'),
        ('sales', '0006_add_venue_hours_breakdown_to_quotelineitem'),
        ('venues', '0008_seed_all_event_types_and_packages'),
        ('workflows', '0012_add_trigger_after_stage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['workflow_template'], name='events_even_workflo_088ad3_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['current_stage'], name='events_even_current_1dd941_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['accepted_quote'], name='events_even_accepte_45a4e3_idx'),
        ),
    ]
