# Generated by Django 5.2.1 on 2026-01-26 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0018_add_performance_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventtype',
            name='color',
            field=models.CharField(blank=True, help_text='Hex color code for UI display (e.g., #2d5016)', max_length=7),
        ),
    ]
