# Generated by Django 5.2.1 on 2026-02-08 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0019_add_color_to_eventtype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventfile',
            name='version',
            field=models.PositiveIntegerField(db_index=True, default=1),
        ),
    ]
