# Generated by Django 5.2.1 on 2026-02-14 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0020_bugfix_indexes_and_managers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventtype',
            options={'ordering': ['sort_order', 'name']},
        ),
        migrations.AddField(
            model_name='eventtype',
            name='featured_image',
            field=models.ImageField(blank=True, help_text='Representative photo for this event type', null=True, upload_to='event_types/images/'),
        ),
        migrations.AddField(
            model_name='eventtype',
            name='gallery_images',
            field=models.JSONField(blank=True, default=list, help_text='List of image URLs for event type gallery'),
        ),
        migrations.AddField(
            model_name='eventtype',
            name='sort_order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
