# Generated by Django 5.2.1 on 2026-02-17 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0021_alter_eventtype_options_eventtype_featured_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='cancellation_request_reason',
            field=models.TextField(blank=True, help_text="Client's reason for requesting cancellation"),
        ),
        migrations.AddField(
            model_name='event',
            name='cancellation_requested',
            field=models.BooleanField(default=False, help_text='Whether the client has requested cancellation'),
        ),
        migrations.AddField(
            model_name='event',
            name='cancellation_requested_at',
            field=models.DateTimeField(blank=True, help_text='When the client requested cancellation', null=True),
        ),
    ]
