# Generated by Django 5.2.1 on 2026-02-17 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0022_cancellation_request_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventtimeline',
            name='action_type',
            field=models.CharField(choices=[('STATUS_CHANGE', 'Status Changed'), ('STAGE_CHANGE', 'Stage Changed'), ('QUOTE_CREATED', 'Quote Created'), ('QUOTE_UPDATED', 'Quote Updated'), ('QUOTE_ACCEPTED', 'Quote Accepted'), ('CONTRACT_SENT', 'Contract Sent'), ('CONTRACT_SIGNED', 'Contract Signed'), ('PAYMENT_RECEIVED', 'Payment Received'), ('NOTE_ADDED', 'Note Added'), ('FILE_UPLOADED', 'File Uploaded'), ('TASK_COMPLETED', 'Task Completed'), ('FEEDBACK_RECEIVED', 'Feedback Received'), ('CLIENT_MESSAGE', 'Client Message'), ('SYSTEM_UPDATE', 'System Update'), ('CANCELLATION_REQUESTED', 'Cancellation Requested')], max_length=50),
        ),
    ]
