# Generated by Django 5.2.1 on 2025-08-30 09:52

import core.utils.encryption
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('category', models.CharField(choices=[('CURRENCY', 'Currency Settings'), ('PAYMENT', 'Payment Settings'), ('NOTIFICATION', 'Notification Settings'), ('SYSTEM', 'System Settings'), ('ANALYTICS', 'Analytics Settings')], max_length=50)),
                ('key', models.CharField(max_length=100)),
                ('value', models.JSONField()),
                ('description', models.TextField(blank=True)),
                ('is_encrypted', models.BooleanField(default=False)),
                ('encrypted_value', core.utils.encryption.EncryptedJSONField(blank=True, default='')),
                ('user', models.ForeignKey(blank=True, help_text='Leave null for system-wide settings', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['category', 'key'],
                'indexes': [models.Index(fields=['category', 'key'], name='settings_ap_categor_b49660_idx'), models.Index(fields=['user', 'category'], name='settings_ap_user_id_5b4622_idx')],
                'unique_together': {('category', 'key', 'user')},
            },
        ),
        migrations.CreateModel(
            name='CurrencySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('default_currency', models.CharField(choices=[('PHP', 'Philippine Peso'), ('USD', 'US Dollar'), ('EUR', 'Euro'), ('SGD', 'Singapore Dollar'), ('HKD', 'Hong Kong Dollar')], default='PHP', help_text='Default currency for the application', max_length=3)),
                ('enabled_currencies', models.JSONField(default=list, help_text='List of enabled currency codes')),
                ('display_format', models.CharField(choices=[('symbol', 'Symbol Only (₱)'), ('code', 'Code Only (PHP)'), ('both', 'Symbol and Code (₱ PHP)')], default='symbol', help_text='How to display currency values', max_length=10)),
                ('decimal_places', models.PositiveIntegerField(default=0, help_text='Number of decimal places to show (0 for PHP business context)')),
                ('thousands_separator', models.CharField(choices=[(',', 'Comma (,)'), ('.', 'Period (.)'), (' ', 'Space ( )')], default=',', help_text='Thousands separator character', max_length=1)),
                ('decimal_separator', models.CharField(choices=[('.', 'Period (.)'), (',', 'Comma (,)')], default='.', help_text='Decimal separator character', max_length=1)),
                ('auto_format', models.BooleanField(default=True, help_text='Automatically format currency inputs')),
                ('compact_format', models.BooleanField(default=False, help_text='Use compact format for large amounts (1K, 1M)')),
                ('user', models.ForeignKey(blank=True, help_text='Leave null for system-wide settings', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Currency Settings',
                'verbose_name_plural': 'Currency Settings',
                'constraints': [models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('user',), name='unique_currency_settings_per_user'), models.UniqueConstraint(condition=models.Q(('user__isnull', True)), fields=('id',), name='unique_system_currency_settings')],
            },
        ),
    ]
