# Generated by Django 5.2.1 on 2025-12-22 02:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_alter_appsettings_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LegalDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document_type', models.CharField(choices=[('TERMS_OF_SERVICE', 'Terms of Service'), ('PRIVACY_POLICY', 'Privacy Policy')], help_text='Type of legal document', max_length=50, unique=True)),
                ('title', models.CharField(default='', max_length=255)),
                ('content', models.TextField(blank=True, help_text='Rich text content of the document')),
                ('version', models.CharField(default='1.0', max_length=50)),
                ('effective_date', models.DateField(blank=True, null=True)),
                ('is_published', models.BooleanField(default=False)),
                ('last_updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_legal_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Legal Document',
                'verbose_name_plural': 'Legal Documents',
            },
        ),
    ]
