# Generated by Django 5.2.1 on 2025-12-23 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0003_legaldocument'),
    ]

    operations = [
        migrations.CreateModel(
            name='MobileAppVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('platform', models.CharField(choices=[('ios', 'iOS'), ('android', 'Android'), ('all', 'All Platforms')], max_length=10)),
                ('minimum_required_version', models.CharField(help_text='Minimum version allowed (force update below this)', max_length=20)),
                ('recommended_version', models.CharField(help_text='Recommended version (soft prompt to update)', max_length=20)),
                ('latest_version', models.CharField(help_text='Latest available version', max_length=20)),
                ('ios_store_url', models.URLField(blank=True)),
                ('android_store_url', models.URLField(blank=True)),
                ('update_title', models.CharField(default='Update Available', max_length=100)),
                ('update_message', models.TextField(default='A new version is available with improvements.')),
                ('force_title', models.CharField(default='Update Required', max_length=100)),
                ('force_message', models.TextField(default='Please update to continue using the app.')),
                ('deprecation_date', models.DateField(blank=True, null=True)),
                ('sunset_date', models.DateField(blank=True, null=True)),
                ('deprecation_message', models.TextField(blank=True)),
                ('is_maintenance_mode', models.BooleanField(default=False)),
                ('maintenance_message', models.TextField(blank=True)),
                ('maintenance_end', models.DateTimeField(blank=True, null=True)),
                ('feature_flags', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Mobile App Version',
                'verbose_name_plural': 'Mobile App Versions',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('platform',), name='unique_active_platform_config')],
            },
        ),
    ]
