# Generated by Django 5.2.1 on 2026-01-18 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0005_companysettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companysettings',
            name='email',
            field=models.EmailField(default='info@lifeplace.dev', help_text='Primary contact email', max_length=254),
        ),
        migrations.AlterField(
            model_name='companysettings',
            name='support_email',
            field=models.EmailField(default='support@lifeplace.dev', help_text='Support email address', max_length=254),
        ),
        migrations.AlterField(
            model_name='companysettings',
            name='website',
            field=models.URLField(default='https://lifeplace.dev', help_text='Company website URL'),
        ),
    ]
