# Generated by Django 5.2.1 on 2026-01-20 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0006_alter_companysettings_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysettings',
            name='support_hours',
            field=models.JSONField(blank=True, default=dict, help_text="Support availability hours, e.g., {'weekdays': '9AM-6PM', 'weekends': 'Closed'}"),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='support_phone',
            field=models.CharField(blank=True, default='', help_text='Support phone number (if different from main phone)', max_length=20),
        ),
    ]
