# Generated by Django 5.2.1 on 2026-01-19 07:09

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CircuitBreakerState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(db_index=True, help_text="Name of the service (e.g., 'stripe', 'brevo', 'expo')", max_length=100, unique=True)),
                ('state', models.CharField(choices=[('CLOSED', 'Closed (Normal)'), ('OPEN', 'Open (Failing Fast)'), ('HALF_OPEN', 'Half-Open (Testing)')], default='CLOSED', max_length=10)),
                ('failure_count', models.PositiveIntegerField(default=0, help_text='Current consecutive failure count')),
                ('failure_threshold', models.PositiveIntegerField(default=5, help_text='Number of failures before opening circuit')),
                ('success_threshold', models.PositiveIntegerField(default=3, help_text='Number of successes in half-open state to close circuit')),
                ('last_failure_at', models.DateTimeField(blank=True, help_text='When the last failure occurred', null=True)),
                ('last_success_at', models.DateTimeField(blank=True, help_text='When the last success occurred', null=True)),
                ('opened_at', models.DateTimeField(blank=True, help_text='When the circuit was last opened', null=True)),
                ('recovery_timeout_seconds', models.PositiveIntegerField(default=60, help_text='Seconds to wait before transitioning from OPEN to HALF_OPEN')),
                ('half_open_successes', models.PositiveIntegerField(default=0, help_text='Successes since entering half-open state')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Circuit Breaker State',
                'verbose_name_plural': 'Circuit Breaker States',
            },
        ),
        migrations.CreateModel(
            name='FailedTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('task_id', models.CharField(db_index=True, help_text='Original Celery task ID', max_length=255)),
                ('task_name', models.CharField(db_index=True, help_text="Fully qualified task name (e.g., 'core.domains.payments.tasks.process_payment')", max_length=255)),
                ('queue', models.CharField(db_index=True, default='celery', help_text='Queue the task was originally sent to', max_length=100)),
                ('args', models.JSONField(blank=True, default=list, help_text='Positional arguments passed to the task')),
                ('kwargs', models.JSONField(blank=True, default=dict, help_text='Keyword arguments passed to the task')),
                ('exception_type', models.CharField(blank=True, help_text='Type of exception that caused the failure', max_length=255)),
                ('exception_message', models.TextField(blank=True, help_text='Exception message')),
                ('traceback', models.TextField(blank=True, help_text='Full traceback of the exception')),
                ('retry_count', models.PositiveIntegerField(default=0, help_text='Number of times the task was retried before failing permanently')),
                ('max_retries', models.PositiveIntegerField(default=3, help_text='Maximum retry limit configured for the task')),
                ('status', models.CharField(choices=[('PENDING_REVIEW', 'Pending Review'), ('REVIEWED', 'Reviewed'), ('REPLAYING', 'Replaying'), ('REPLAYED', 'Replayed Successfully'), ('REPLAY_FAILED', 'Replay Failed'), ('IGNORED', 'Ignored'), ('RESOLVED_MANUALLY', 'Resolved Manually')], db_index=True, default='PENDING_REVIEW', max_length=20)),
                ('admin_notes', models.TextField(blank=True, help_text='Notes from admin about resolution or investigation')),
                ('replay_count', models.PositiveIntegerField(default=0, help_text='Number of times the task was replayed from DLQ')),
                ('last_replay_at', models.DateTimeField(blank=True, help_text='When the task was last replayed', null=True)),
                ('failed_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='When the task permanently failed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('replayed_by', models.ForeignKey(blank=True, help_text='User who initiated the replay', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replayed_tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Failed Task',
                'verbose_name_plural': 'Failed Tasks',
                'ordering': ['-failed_at'],
                'indexes': [models.Index(fields=['task_name', '-failed_at'], name='infrastruct_task_na_afc3eb_idx'), models.Index(fields=['status', '-failed_at'], name='infrastruct_status_e71c58_idx'), models.Index(fields=['queue', '-failed_at'], name='infrastruct_queue_afa2cc_idx')],
            },
        ),
    ]
