# Generated by Django 5.2.1 on 2026-02-07 02:13

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemHealthSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, unique=True)),
                ('error_count', models.PositiveIntegerField(default=0, help_text='DLQ failures on this date')),
                ('pending_review_count', models.PositiveIntegerField(default=0, help_text='DLQ tasks pending review as of snapshot')),
                ('celery_tasks_failed', models.PositiveIntegerField(default=0)),
                ('celery_success_rate', models.DecimalField(decimal_places=2, default=100.0, max_digits=5)),
                ('cache_hit_ratio', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('cache_memory_used_bytes', models.BigIntegerField(blank=True, null=True)),
                ('total_queue_depth', models.PositiveIntegerField(default=0)),
                ('queue_depth_breakdown', models.JSONField(blank=True, default=dict, help_text='Per-queue depth breakdown')),
                ('open_circuit_breakers', models.PositiveIntegerField(default=0)),
                ('circuit_breaker_states', models.JSONField(blank=True, default=dict, help_text='Service name to state mapping')),
                ('broker_ping_ms', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('broker_healthy', models.BooleanField(default=True)),
                ('raw_health_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'System Health Snapshot',
                'verbose_name_plural': 'System Health Snapshots',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Deployment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('git_sha', models.CharField(db_index=True, max_length=40)),
                ('git_sha_short', models.CharField(blank=True, max_length=8)),
                ('commit_message', models.TextField(blank=True)),
                ('commit_timestamp', models.DateTimeField(blank=True, help_text='When the commit was authored (for lead time calculation)', null=True)),
                ('service', models.CharField(choices=[('backend', 'Backend API'), ('admin-crm', 'Admin CRM'), ('client-portal', 'Client Portal')], db_index=True, max_length=50)),
                ('environment', models.CharField(db_index=True, default='production', max_length=50)),
                ('github_run_id', models.CharField(blank=True, max_length=100)),
                ('github_run_url', models.URLField(blank=True, max_length=500)),
                ('triggered_by', models.CharField(blank=True, help_text='push, workflow_dispatch, etc.', max_length=50)),
                ('deploy_started_at', models.DateTimeField(blank=True, null=True)),
                ('deploy_finished_at', models.DateTimeField(blank=True, null=True)),
                ('deploy_duration_seconds', models.PositiveIntegerField(blank=True, help_text='Auto-calculated from started/finished', null=True)),
                ('lead_time_seconds', models.PositiveIntegerField(blank=True, help_text='Time from commit to deploy finish', null=True)),
                ('status', models.CharField(choices=[('SUCCESS', 'Success'), ('FAILURE', 'Failure'), ('ROLLBACK', 'Rollback')], db_index=True, default='SUCCESS', max_length=10)),
                ('caused_incident', models.BooleanField(default=False)),
                ('incident_detected_at', models.DateTimeField(blank=True, null=True)),
                ('incident_resolved_at', models.DateTimeField(blank=True, null=True)),
                ('incident_notes', models.TextField(blank=True)),
                ('mttr_seconds', models.PositiveIntegerField(blank=True, help_text='Mean time to recovery in seconds', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Deployment',
                'verbose_name_plural': 'Deployments',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['service', '-created_at'], name='infrastruct_service_b18f82_idx'), models.Index(fields=['environment', '-created_at'], name='infrastruct_environ_e488b9_idx'), models.Index(fields=['status', '-created_at'], name='infrastruct_status_87d8bd_idx')],
            },
        ),
    ]
