// Integration Test - Testing Component Interoperability
// This file tests that components can be imported and used together correctly

import React from 'react';
import { Box, Typography, Button, Card, CardContent } from '@mui/material';

// Test 1: Basic MUI integration with custom styling
const MUIIntegrationTest: React.FC = () => {
  return (
    <Box sx={{ p: 2, display: 'flex', flexDirection: 'column', gap: 2 }}>
      <Typography variant="h4" component="h1">
        MUI Integration Test
      </Typography>
      <Card>
        <CardContent>
          <Typography variant="body1">
            This tests that MUI components work correctly together.
          </Typography>
          <Button variant="contained" sx={{ mt: 2 }}>
            Test Button
          </Button>
        </CardContent>
      </Card>
    </Box>
  );
};

// Test 2: Responsive design integration (simulating the responsive utilities)
const ResponsiveIntegrationTest: React.FC = () => {
  // Simulating responsive styles that would be generated by the utilities
  const responsiveStyles = {
    padding: '16px',
    display: 'grid',
    gridTemplateColumns: 'repeat(1, 1fr)',
    gap: '16px',
    '@media (min-width: 768px)': {
      padding: '24px',
      gridTemplateColumns: 'repeat(2, 1fr)',
    },
    '@media (min-width: 1024px)': {
      gridTemplateColumns: 'repeat(3, 1fr)',
    },
  };

  return (
    <Box sx={responsiveStyles}>
      <Card>
        <CardContent>
          <Typography variant="h6">Card 1</Typography>
          <Typography>Responsive grid item</Typography>
        </CardContent>
      </Card>
      <Card>
        <CardContent>
          <Typography variant="h6">Card 2</Typography>
          <Typography>Responsive grid item</Typography>
        </CardContent>
      </Card>
      <Card>
        <CardContent>
          <Typography variant="h6">Card 3</Typography>
          <Typography>Responsive grid item</Typography>
        </CardContent>
      </Card>
    </Box>
  );
};

// Test 3: Theme integration test
const ThemeIntegrationTest: React.FC = () => {
  return (
    <Box sx={{ 
      p: 3, 
      backgroundColor: 'background.paper',
      color: 'text.primary',
      borderRadius: 1,
      boxShadow: 1 
    }}>
      <Typography variant="h5" sx={{ color: 'primary.main', mb: 2 }}>
        Theme Integration Test
      </Typography>
      <Typography variant="body1" sx={{ color: 'text.secondary', mb: 2 }}>
        This tests theme tokens and color system integration.
      </Typography>
      <Button 
        variant="outlined" 
        color="primary" 
        sx={{ mr: 2 }}
      >
        Primary Button
      </Button>
      <Button 
        variant="contained" 
        color="secondary"
      >
        Secondary Button
      </Button>
    </Box>
  );
};

// Test 4: Form integration test
const FormIntegrationTest: React.FC = () => {
  const [formData, setFormData] = React.useState({
    name: '',
    email: '',
  });

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    console.log('Form submitted:', formData);
  };

  const handleChange = (field: string) => (e: React.ChangeEvent<HTMLInputElement>) => {
    setFormData(prev => ({
      ...prev,
      [field]: e.target.value
    }));
  };

  return (
    <Box sx={{ p: 3, maxWidth: 400 }}>
      <Typography variant="h5" sx={{ mb: 2 }}>
        Form Integration Test
      </Typography>
      <Box component="form" onSubmit={handleSubmit} sx={{ display: 'flex', flexDirection: 'column', gap: 2 }}>
        <Box>
          <label htmlFor="name">Name:</label>
          <input
            id="name"
            type="text"
            value={formData.name}
            onChange={handleChange('name')}
            style={{ width: '100%', padding: '8px', marginTop: '4px' }}
          />
        </Box>
        <Box>
          <label htmlFor="email">Email:</label>
          <input
            id="email"
            type="email"
            value={formData.email}
            onChange={handleChange('email')}
            style={{ width: '100%', padding: '8px', marginTop: '4px' }}
          />
        </Box>
        <Button type="submit" variant="contained" sx={{ mt: 2 }}>
          Submit Form
        </Button>
      </Box>
    </Box>
  );
};

// Test 5: Error boundary test
interface ErrorBoundaryState {
  hasError: boolean;
  error?: Error;
}

class SimpleErrorBoundary extends React.Component<
  React.PropsWithChildren<{}>, 
  ErrorBoundaryState
> {
  constructor(props: React.PropsWithChildren<{}>) {
    super(props);
    this.state = { hasError: false };
  }

  static getDerivedStateFromError(error: Error): ErrorBoundaryState {
    return { hasError: true, error };
  }

  componentDidCatch(error: Error, errorInfo: React.ErrorInfo) {
    console.error('Error caught by boundary:', error, errorInfo);
  }

  render() {
    if (this.state.hasError) {
      return (
        <Box sx={{ p: 3, backgroundColor: 'error.light', borderRadius: 1 }}>
          <Typography variant="h6" color="error">
            Something went wrong
          </Typography>
          <Typography variant="body2">
            {this.state.error?.message || 'An unknown error occurred'}
          </Typography>
        </Box>
      );
    }

    return this.props.children;
  }
}

// Main integration test component
export const IntegrationTestSuite: React.FC = () => {
  return (
    <SimpleErrorBoundary>
      <Box sx={{ p: 3, backgroundColor: 'background.default', minHeight: '100vh' }}>
        <Typography variant="h3" sx={{ mb: 4, textAlign: 'center' }}>
          Component Integration Test Suite
        </Typography>
        
        <Box sx={{ display: 'flex', flexDirection: 'column', gap: 4 }}>
          <MUIIntegrationTest />
          <ResponsiveIntegrationTest />
          <ThemeIntegrationTest />
          <FormIntegrationTest />
        </Box>

        <Box sx={{ mt: 4, p: 3, backgroundColor: 'success.light', borderRadius: 1 }}>
          <Typography variant="h6" sx={{ color: 'success.dark' }}>
            ✅ Integration Test Complete
          </Typography>
          <Typography variant="body2" sx={{ color: 'success.dark' }}>
            If you can see this, all components integrated successfully!
          </Typography>
        </Box>
      </Box>
    </SimpleErrorBoundary>
  );
};

// Export for testing
export default IntegrationTestSuite;

// Type-only exports to test type system integration
export type TestComponentProps = {
  title: string;
  variant?: 'primary' | 'secondary';
  size?: 'small' | 'medium' | 'large';
  children?: React.ReactNode;
};

export interface TestFormData {
  name: string;
  email: string;
  preferences: {
    theme: 'light' | 'dark';
    notifications: boolean;
  };
}

// Test utility functions
export const testUtils = {
  formatTestId: (component: string, id: string) => `${component}-${id}`,
  validateEmail: (email: string): boolean => {
    const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
    return emailRegex.test(email);
  },
  createMockProps: function<T>(overrides: Partial<T> = {}): T {
    return {
      ...overrides
    } as T;
  },
};

console.log('✅ Integration test file loaded successfully');
console.log('📝 Components available:', {
  MUIIntegrationTest: typeof MUIIntegrationTest,
  ResponsiveIntegrationTest: typeof ResponsiveIntegrationTest,  
  ThemeIntegrationTest: typeof ThemeIntegrationTest,
  FormIntegrationTest: typeof FormIntegrationTest,
  IntegrationTestSuite: typeof IntegrationTestSuite,
});
console.log('🔧 Test utilities available:', Object.keys(testUtils));