# Generated by Django 5.2.1 on 2025-06-23 02:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0003_event_current_stage_event_last_contacted_and_more'),
        ('products', '0002_discount_currency'),
        ('questionnaires', '0001_initial'),
        ('workflows', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddonConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('min_selection', models.PositiveIntegerField(default=0)),
                ('max_selection', models.PositiveIntegerField(default=0, help_text='0 means unlimited')),
                ('is_required', models.BooleanField(default=False)),
                ('is_visible', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='AddonItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_highlighted', models.BooleanField(default=False)),
                ('custom_price', models.DecimalField(blank=True, decimal_places=2, help_text="If set, overrides the product's default price", max_digits=10, null=True)),
                ('custom_description', models.TextField(blank=True, help_text="If set, overrides the product's default description")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addon_items', to='bookingflow.addonconfiguration')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addon_items', to='products.productoption')),
            ],
            options={
                'ordering': ['config', 'order'],
                'unique_together': {('config', 'order')},
            },
        ),
        migrations.AddField(
            model_name='addonconfiguration',
            name='addons',
            field=models.ManyToManyField(related_name='addon_configs', through='bookingflow.AddonItem', to='products.productoption'),
        ),
        migrations.CreateModel(
            name='BookingFlow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_flows', to='events.eventtype')),
                ('workflow_template', models.ForeignKey(blank=True, help_text='Workflow template to assign to events created through this booking flow', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking_flows', to='workflows.workflowtemplate')),
            ],
        ),
        migrations.AddField(
            model_name='addonconfiguration',
            name='booking_flow',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='addon_config', to='bookingflow.bookingflow'),
        ),
        migrations.CreateModel(
            name='ConfirmationConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('success_message', models.TextField(blank=True)),
                ('send_email', models.BooleanField(default=True)),
                ('email_template', models.CharField(blank=True, max_length=255)),
                ('show_summary', models.BooleanField(default=True)),
                ('is_visible', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking_flow', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='confirmation_config', to='bookingflow.bookingflow')),
            ],
        ),
        migrations.CreateModel(
            name='DateConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('min_days_in_future', models.PositiveIntegerField(default=1)),
                ('max_days_in_future', models.PositiveIntegerField(default=365)),
                ('allow_time_selection', models.BooleanField(default=True)),
                ('buffer_before_event', models.PositiveIntegerField(default=0, help_text='Buffer time in minutes before event')),
                ('buffer_after_event', models.PositiveIntegerField(default=0, help_text='Buffer time in minutes after event')),
                ('allow_multi_day', models.BooleanField(default=False, help_text='Allow selection of both start and end dates for multi-day events')),
                ('is_required', models.BooleanField(default=True)),
                ('is_visible', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking_flow', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='date_config', to='bookingflow.bookingflow')),
            ],
        ),
        migrations.CreateModel(
            name='IntroConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('show_event_details', models.BooleanField(default=True)),
                ('is_required', models.BooleanField(default=True)),
                ('is_visible', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking_flow', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='intro_config', to='bookingflow.bookingflow')),
            ],
        ),
        migrations.CreateModel(
            name='PackageConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('min_selection', models.PositiveIntegerField(default=1)),
                ('max_selection', models.PositiveIntegerField(default=1)),
                ('selection_type', models.CharField(choices=[('SINGLE', 'Single Selection'), ('MULTIPLE', 'Multiple Selection')], default='SINGLE', max_length=20)),
                ('is_required', models.BooleanField(default=True)),
                ('is_visible', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking_flow', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='package_config', to='bookingflow.bookingflow')),
            ],
        ),
        migrations.CreateModel(
            name='PackageItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_highlighted', models.BooleanField(default=False)),
                ('custom_price', models.DecimalField(blank=True, decimal_places=2, help_text="If set, overrides the product's default price", max_digits=10, null=True)),
                ('custom_description', models.TextField(blank=True, help_text="If set, overrides the product's default description")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='package_items', to='bookingflow.packageconfiguration')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='package_items', to='products.productoption')),
            ],
            options={
                'ordering': ['config', 'order'],
                'unique_together': {('config', 'order')},
            },
        ),
        migrations.AddField(
            model_name='packageconfiguration',
            name='packages',
            field=models.ManyToManyField(related_name='package_configs', through='bookingflow.PackageItem', to='products.productoption'),
        ),
        migrations.CreateModel(
            name='PaymentConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('require_deposit', models.BooleanField(default=False)),
                ('deposit_percentage', models.PositiveIntegerField(default=50)),
                ('accept_credit_card', models.BooleanField(default=True)),
                ('accept_paypal', models.BooleanField(default=False)),
                ('accept_bank_transfer', models.BooleanField(default=False)),
                ('payment_instructions', models.TextField(blank=True)),
                ('is_required', models.BooleanField(default=True)),
                ('is_visible', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking_flow', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment_config', to='bookingflow.bookingflow')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionnaireConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('is_required', models.BooleanField(default=True)),
                ('is_visible', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking_flow', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='questionnaire_config', to='bookingflow.bookingflow')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionnaireItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_required', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questionnaire_items', to='bookingflow.questionnaireconfiguration')),
                ('questionnaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='config_items', to='questionnaires.questionnaire')),
            ],
            options={
                'ordering': ['config', 'order'],
                'unique_together': {('config', 'order')},
            },
        ),
        migrations.AddField(
            model_name='questionnaireconfiguration',
            name='questionnaires',
            field=models.ManyToManyField(related_name='booking_flows', through='bookingflow.QuestionnaireItem', to='questionnaires.questionnaire'),
        ),
        migrations.CreateModel(
            name='SummaryConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('show_date', models.BooleanField(default=True)),
                ('show_packages', models.BooleanField(default=True)),
                ('show_addons', models.BooleanField(default=True)),
                ('show_questionnaire', models.BooleanField(default=True)),
                ('show_total', models.BooleanField(default=True)),
                ('is_required', models.BooleanField(default=True)),
                ('is_visible', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking_flow', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='summary_config', to='bookingflow.bookingflow')),
            ],
        ),
    ]
