# Generated by Django 5.2.1 on 2025-06-25 19:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingflow', '0001_initial'),
        ('communications', '0001_initial'),
        ('events', '0003_event_current_stage_event_last_contacted_and_more'),
        ('products', '0002_discount_currency'),
        ('workflows', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bookingflow',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='bookingflow',
            name='event_type',
            field=models.ForeignKey(blank=True, help_text="Leave blank for 'Any Event Type'", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='booking_flows', to='events.eventtype'),
        ),
        migrations.AddIndex(
            model_name='bookingflow',
            index=models.Index(fields=['event_type', 'is_active'], name='bookingflow_event_t_7ffe67_idx'),
        ),
        migrations.AddIndex(
            model_name='bookingflow',
            index=models.Index(fields=['is_active'], name='bookingflow_is_acti_803e0f_idx'),
        ),
    ]
