# Generated by Django 5.2.1 on 2025-06-29 03:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingflow', '0002_alter_bookingflow_unique_together_and_more'),
        ('payments', '0002_invoice_quote_payment_quote_paymentplan_quote'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingflow',
            name='allowed_payment_gateways',
            field=models.ManyToManyField(blank=True, help_text='Payment gateways available for this booking flow', related_name='booking_flows', to='payments.paymentgateway'),
        ),
        migrations.AddField(
            model_name='bookingflow',
            name='default_payment_gateway',
            field=models.ForeignKey(blank=True, help_text='Default payment gateway for this booking flow', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_booking_flows', to='payments.paymentgateway'),
        ),
        migrations.AddField(
            model_name='bookingflow',
            name='require_immediate_payment',
            field=models.BooleanField(default=False, help_text='Require payment during booking completion'),
        ),
        migrations.AddField(
            model_name='paymentinfostepconfiguration',
            name='allowed_gateways',
            field=models.ManyToManyField(blank=True, help_text='Payment gateways available for this step', related_name='payment_step_configs', to='payments.paymentgateway'),
        ),
        migrations.AddField(
            model_name='paymentinfostepconfiguration',
            name='default_gateway',
            field=models.ForeignKey(blank=True, help_text='Default payment gateway for this step', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_payment_steps', to='payments.paymentgateway'),
        ),
        migrations.AlterField(
            model_name='paymentinfostepconfiguration',
            name='require_immediate_payment',
            field=models.BooleanField(default=False, help_text='Process payment immediately during booking'),
        ),
    ]
