# Generated by Django 5.2.1 on 2025-07-01 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingflow', '0003_bookingflow_allowed_payment_gateways_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingflowstep',
            name='step_type',
            field=models.CharField(choices=[('introduction', 'Introduction'), ('date_time', 'Date & Time Selection'), ('questionnaire', 'Questionnaire'), ('package_selection', 'Package Selection'), ('addon_selection', 'Add-on Selection'), ('availability_check', 'Availability Check'), ('pricing_summary', 'Pricing Summary'), ('contact_info', 'Contact Information'), ('payment_info', 'Payment Information'), ('review_booking', 'Review Booking'), ('confirmation', 'Confirmation')], max_length=50),
        ),
        migrations.DeleteModel(
            name='EventDetailsStepConfiguration',
        ),
    ]
