# Generated by Django 5.2.1 on 2025-07-01 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingflow', '0004_alter_bookingflowstep_step_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='datetimestepconfiguration',
            name='allow_overbooking',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='datetimestepconfiguration',
            name='auto_check_conflicts',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='datetimestepconfiguration',
            name='availability_display_mode',
            field=models.CharField(choices=[('FULL', 'Show Full Availability'), ('LIMITED', 'Show Limited Availability'), ('SIMPLE', 'Show Simple Yes/No')], default='FULL', max_length=20),
        ),
        migrations.AddField(
            model_name='datetimestepconfiguration',
            name='calendar_source',
            field=models.CharField(blank=True, choices=[('GOOGLE', 'Google Calendar'), ('OUTLOOK', 'Outlook Calendar'), ('EXTERNAL', 'External System')], help_text='Calendar system to sync availability with', max_length=50),
        ),
        migrations.AddField(
            model_name='datetimestepconfiguration',
            name='check_resource_availability',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='datetimestepconfiguration',
            name='check_staff_availability',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='datetimestepconfiguration',
            name='check_venue_availability',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='datetimestepconfiguration',
            name='overbooking_threshold',
            field=models.PositiveIntegerField(default=0, help_text='Maximum allowed conflicts before blocking'),
        ),
        migrations.AddField(
            model_name='datetimestepconfiguration',
            name='show_availability_status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='datetimestepconfiguration',
            name='sync_with_calendar',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='bookingflowstep',
            name='step_type',
            field=models.CharField(choices=[('introduction', 'Introduction'), ('date_time', 'Date & Time Selection'), ('questionnaire', 'Questionnaire'), ('package_selection', 'Package Selection'), ('addon_selection', 'Add-on Selection'), ('pricing_summary', 'Pricing Summary'), ('contact_info', 'Contact Information'), ('payment_info', 'Payment Information'), ('review_booking', 'Review Booking'), ('confirmation', 'Confirmation')], max_length=50),
        ),
    ]
