# Generated by Django 5.2.1 on 2025-07-26 20:52

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingflow', '0005_datetimestepconfiguration_allow_overbooking_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PricingSummaryStepConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('show_package_breakdown', models.BooleanField(default=True)),
                ('show_addon_breakdown', models.BooleanField(default=True)),
                ('show_tax_breakdown', models.BooleanField(default=True)),
                ('show_discount_field', models.BooleanField(default=True)),
                ('show_subtotal', models.BooleanField(default=True)),
                ('allow_discount_codes', models.BooleanField(default=True)),
                ('calculate_tax', models.BooleanField(default=True)),
                ('header_text', models.CharField(blank=True, default='Review your order', max_length=255)),
                ('footer_text', models.TextField(blank=True)),
                ('discount_help_text', models.CharField(blank=True, default='Enter discount code', max_length=255)),
                ('step', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pricing_config', to='bookingflow.bookingflowstep')),
            ],
            options={
                'ordering': ['step'],
            },
        ),
    ]
