# Generated by Django 5.2.1 on 2025-08-25 03:53

from django.db import migrations, connection


def fix_payment_methods_field(apps, schema_editor):
    """
    Fix the available_payment_methods field type in PostgreSQL.
    This migration only runs on PostgreSQL databases.
    """
    if connection.vendor == 'postgresql':
        with schema_editor.connection.cursor() as cursor:
            # Check if the column exists as an array type
            cursor.execute("""
                SELECT data_type 
                FROM information_schema.columns
                WHERE table_name = 'bookingflow_paymentinfostepconfiguration'
                AND column_name = 'available_payment_methods'
            """)
            result = cursor.fetchone()
            
            if result and result[0] == 'ARRAY':
                # First, alter the column to a temporary text column with array converted to JSON
                cursor.execute("""
                    ALTER TABLE bookingflow_paymentinfostepconfiguration 
                    ALTER COLUMN available_payment_methods TYPE text 
                    USING CASE 
                        WHEN available_payment_methods IS NULL THEN '[]'
                        WHEN array_length(available_payment_methods, 1) IS NULL THEN '[]'
                        ELSE array_to_json(available_payment_methods)::text
                    END;
                """)
                
                # Then alter from text to jsonb
                cursor.execute("""
                    ALTER TABLE bookingflow_paymentinfostepconfiguration 
                    ALTER COLUMN available_payment_methods TYPE jsonb 
                    USING available_payment_methods::jsonb;
                """)


def reverse_fix_payment_methods_field(apps, schema_editor):
    """
    Reverse the field type change (for rollback).
    This migration only runs on PostgreSQL databases.
    """
    if connection.vendor == 'postgresql':
        with schema_editor.connection.cursor() as cursor:
            # Check if the column exists as jsonb
            cursor.execute("""
                SELECT data_type 
                FROM information_schema.columns
                WHERE table_name = 'bookingflow_paymentinfostepconfiguration'
                AND column_name = 'available_payment_methods'
            """)
            result = cursor.fetchone()
            
            if result and result[0] == 'jsonb':
                # Convert jsonb array back to text array
                cursor.execute("""
                    ALTER TABLE bookingflow_paymentinfostepconfiguration 
                    ALTER COLUMN available_payment_methods TYPE text[] 
                    USING (
                        CASE 
                            WHEN jsonb_typeof(available_payment_methods) = 'array' THEN
                                ARRAY(SELECT jsonb_array_elements_text(available_payment_methods))
                            ELSE
                                ARRAY[]::text[]
                        END
                    );
                """)


class Migration(migrations.Migration):

    dependencies = [
        ('bookingflow', '0006_pricingsummarystepconfiguration'),
    ]

    operations = [
        migrations.RunPython(
            fix_payment_methods_field,
            reverse_fix_payment_methods_field,
        ),
    ]
