# Generated by Django 5.2.1 on 2025-08-25

from django.db import migrations, connection


def fix_array_to_jsonb_fields(apps, schema_editor):
    """
    Fix all array fields to JSONB in PostgreSQL for bookingflow app.
    This migration only runs on PostgreSQL databases.
    """
    if connection.vendor == 'postgresql':
        with schema_editor.connection.cursor() as cursor:
            # List of tables and columns to fix
            fields_to_fix = [
                ('bookingflow_datetimestepconfiguration', 'available_days_of_week'),
                ('bookingflow_datetimestepconfiguration', 'blocked_dates'),
                ('bookingflow_questionnairestepconfiguration', 'allowed_file_types'),
            ]
            
            for table_name, column_name in fields_to_fix:
                # Check if the column exists as an array type
                cursor.execute(f"""
                    SELECT data_type 
                    FROM information_schema.columns
                    WHERE table_name = '{table_name}'
                    AND column_name = '{column_name}'
                """)
                result = cursor.fetchone()
                
                if result and result[0] == 'ARRAY':
                    print(f"Converting {table_name}.{column_name} from ARRAY to JSONB...")
                    
                    # First, alter the column to text with array converted to JSON
                    cursor.execute(f"""
                        ALTER TABLE {table_name}
                        ALTER COLUMN {column_name} TYPE text 
                        USING CASE 
                            WHEN {column_name} IS NULL THEN '[]'
                            WHEN array_length({column_name}, 1) IS NULL THEN '[]'
                            ELSE array_to_json({column_name})::text
                        END;
                    """)
                    
                    # Then alter from text to jsonb
                    cursor.execute(f"""
                        ALTER TABLE {table_name}
                        ALTER COLUMN {column_name} TYPE jsonb 
                        USING {column_name}::jsonb;
                    """)
                    
                    print(f"  ✓ Converted {table_name}.{column_name} to JSONB")


def reverse_fix_array_to_jsonb_fields(apps, schema_editor):
    """
    Reverse the field type changes (for rollback).
    This migration only runs on PostgreSQL databases.
    """
    if connection.vendor == 'postgresql':
        with schema_editor.connection.cursor() as cursor:
            # List of tables and columns to reverse
            fields_to_fix = [
                ('bookingflow_datetimestepconfiguration', 'available_days_of_week', 'integer[]'),
                ('bookingflow_datetimestepconfiguration', 'blocked_dates', 'date[]'),
                ('bookingflow_questionnairestepconfiguration', 'allowed_file_types', 'text[]'),
            ]
            
            for table_name, column_name, array_type in fields_to_fix:
                # Check if the column exists as jsonb
                cursor.execute(f"""
                    SELECT data_type 
                    FROM information_schema.columns
                    WHERE table_name = '{table_name}'
                    AND column_name = '{column_name}'
                """)
                result = cursor.fetchone()
                
                if result and result[0] == 'jsonb':
                    # Convert jsonb array back to PostgreSQL array
                    if array_type == 'integer[]':
                        cursor.execute(f"""
                            ALTER TABLE {table_name}
                            ALTER COLUMN {column_name} TYPE {array_type}
                            USING (
                                CASE 
                                    WHEN jsonb_typeof({column_name}) = 'array' THEN
                                        ARRAY(SELECT jsonb_array_elements_text({column_name})::integer)
                                    ELSE
                                        ARRAY[]::integer[]
                                END
                            );
                        """)
                    elif array_type == 'date[]':
                        cursor.execute(f"""
                            ALTER TABLE {table_name}
                            ALTER COLUMN {column_name} TYPE {array_type}
                            USING (
                                CASE 
                                    WHEN jsonb_typeof({column_name}) = 'array' THEN
                                        ARRAY(SELECT jsonb_array_elements_text({column_name})::date)
                                    ELSE
                                        ARRAY[]::date[]
                                END
                            );
                        """)
                    else:  # text[]
                        cursor.execute(f"""
                            ALTER TABLE {table_name}
                            ALTER COLUMN {column_name} TYPE {array_type}
                            USING (
                                CASE 
                                    WHEN jsonb_typeof({column_name}) = 'array' THEN
                                        ARRAY(SELECT jsonb_array_elements_text({column_name}))
                                    ELSE
                                        ARRAY[]::text[]
                                END
                            );
                        """)


class Migration(migrations.Migration):

    dependencies = [
        ('bookingflow', '0007_fix_available_payment_methods_field_type'),
    ]

    operations = [
        migrations.RunPython(
            fix_array_to_jsonb_fields,
            reverse_fix_array_to_jsonb_fields,
        ),
    ]