# Generated by Django 5.2.1 on 2025-09-04 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingflow', '0008_fix_all_array_to_jsonb_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentinfostepconfiguration',
            name='allow_quote_request',
            field=models.BooleanField(default=True, help_text='Allow users to request a quote instead of paying immediately'),
        ),
        migrations.AddField(
            model_name='paymentinfostepconfiguration',
            name='quote_request_button_text',
            field=models.CharField(blank=True, default='Request Quote', help_text='Text displayed on the quote request button', max_length=100),
        ),
        migrations.AddField(
            model_name='paymentinfostepconfiguration',
            name='quote_request_description',
            field=models.TextField(blank=True, help_text='Description shown for the quote request option'),
        ),
    ]
