# Generated by Django 5.2.1 on 2025-09-04 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingflow', '0009_paymentinfostepconfiguration_allow_quote_request_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentinfostepconfiguration',
            name='balance_due_days',
            field=models.PositiveIntegerField(default=30, help_text='Number of days before the event when the balance is due'),
        ),
    ]
