# Generated by Django 5.2.1 on 2025-09-04 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingflow', '0010_paymentinfostepconfiguration_balance_due_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentinfostepconfiguration',
            name='allow_refunds',
            field=models.BooleanField(default=True, help_text='Allow refunds for this booking flow'),
        ),
        migrations.AddField(
            model_name='paymentinfostepconfiguration',
            name='refund_deadline_days',
            field=models.PositiveIntegerField(default=48, help_text='Number of hours before the event when refunds are no longer allowed'),
        ),
        migrations.AddField(
            model_name='paymentinfostepconfiguration',
            name='refund_percentage',
            field=models.PositiveIntegerField(default=100, help_text='Percentage of payment that can be refunded (0-100)'),
        ),
        migrations.AddField(
            model_name='paymentinfostepconfiguration',
            name='refund_policy_text',
            field=models.TextField(blank=True, help_text='Custom refund policy text to display to clients'),
        ),
    ]
