# Generated by Django 5.2.1 on 2025-09-30 22:00

from django.db import migrations
from decimal import Decimal
import logging

logger = logging.getLogger(__name__)


def audit_payment_configurations(apps, schema_editor):
    """
    Audit existing payment configurations before consolidation.

    This migration checks all PaymentInfoStepConfiguration instances
    and logs any custom settings that differ from PaymentSettings defaults.
    """
    PaymentInfoStepConfiguration = apps.get_model('bookingflow', 'PaymentInfoStepConfiguration')

    # Try to get PaymentSettings model, but handle case where it might not exist yet
    try:
        PaymentSettings = apps.get_model('payments', 'PaymentSettings')
        payment_settings, created = PaymentSettings.objects.get_or_create(
            defaults={
                'balance_due_days': 30,
                'default_deposit_percentage': Decimal('50.00'),
            }
        )
    except LookupError:
        # PaymentSettings model doesn't exist in this migration state
        # Use fallback defaults for comparison
        class MockSettings:
            balance_due_days = 30
            default_deposit_percentage = Decimal('50.00')
        payment_settings = MockSettings()

    # Audit all payment configs
    configs = PaymentInfoStepConfiguration.objects.all()

    if not configs.exists():
        logger.info("✓ No PaymentInfoStepConfiguration instances found")
        return

    logger.info(f"📋 Auditing {configs.count()} payment configurations...")

    custom_configs = []
    for config in configs:
        issues = []

        # Check balance_due_days
        if hasattr(config, 'balance_due_days') and config.balance_due_days != payment_settings.balance_due_days:
            issues.append(f"balance_due_days={config.balance_due_days} (global={payment_settings.balance_due_days})")

        # Check deposit_amount (if it's percentage type)
        if hasattr(config, 'deposit_amount') and hasattr(config, 'deposit_type'):
            if config.deposit_type == 'PERCENTAGE' and config.deposit_amount != payment_settings.default_deposit_percentage:
                issues.append(f"deposit_amount={config.deposit_amount}% (global={payment_settings.default_deposit_percentage}%)")
            elif config.deposit_type == 'FIXED':
                issues.append(f"deposit_amount=₱{config.deposit_amount} FIXED (global uses percentage)")

        if issues:
            flow_name = config.step.booking_flow.name if hasattr(config, 'step') else 'Unknown'
            custom_configs.append({
                'id': config.id,
                'flow': flow_name,
                'issues': issues
            })

    if custom_configs:
        logger.warning("⚠️  Found payment configurations with custom settings:")
        for conf in custom_configs:
            logger.warning(f"  - Flow '{conf['flow']}' (ID={conf['id']}): {', '.join(conf['issues'])}")
        logger.warning("⚠️  These custom settings will be replaced with global PaymentSettings after consolidation")
        logger.warning(f"⚠️  Current global settings: balance_due_days={payment_settings.balance_due_days}, deposit={payment_settings.default_deposit_percentage}%")
    else:
        logger.info("✓ All payment configurations use default settings - safe to proceed with consolidation")


class Migration(migrations.Migration):

    dependencies = [
        ('bookingflow', '0011_paymentinfostepconfiguration_allow_refunds_and_more'),
        ('payments', '0002_invoice_quote_payment_quote_paymentplan_quote'),
    ]

    operations = [
        migrations.RunPython(audit_payment_configurations, reverse_code=migrations.RunPython.noop),
    ]
