# Generated by Django 5.2.1 on 2025-09-30 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingflow', '0012_audit_payment_config_before_consolidation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentinfostepconfiguration',
            name='balance_due_days',
        ),
        migrations.RemoveField(
            model_name='paymentinfostepconfiguration',
            name='deposit_amount',
        ),
        migrations.RemoveField(
            model_name='paymentinfostepconfiguration',
            name='deposit_type',
        ),
        migrations.AlterField(
            model_name='paymentinfostepconfiguration',
            name='accept_deposit',
            field=models.BooleanField(default=True, help_text='Show option to pay deposit (amount calculated from PaymentSettings.default_deposit_percentage)'),
        ),
        migrations.AlterField(
            model_name='paymentinfostepconfiguration',
            name='accept_full_payment',
            field=models.BooleanField(default=True, help_text='Show option to pay in full'),
        ),
        migrations.AlterField(
            model_name='paymentinfostepconfiguration',
            name='allow_payment_plans',
            field=models.BooleanField(default=False, help_text='Show payment plan option in UI'),
        ),
        migrations.AlterField(
            model_name='paymentinfostepconfiguration',
            name='available_payment_methods',
            field=models.JSONField(blank=True, default=list, help_text='Available payment methods (deprecated)'),
        ),
        migrations.AlterField(
            model_name='paymentinfostepconfiguration',
            name='payment_terms',
            field=models.TextField(blank=True, help_text='Payment terms text to display to clients'),
        ),
    ]
