# Generated by Django 5.2.1 on 2025-09-30 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingflow', '0013_remove_payment_config_consolidated_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentinfostepconfiguration',
            name='allow_refunds',
        ),
        migrations.RemoveField(
            model_name='paymentinfostepconfiguration',
            name='allowed_gateways',
        ),
        migrations.RemoveField(
            model_name='paymentinfostepconfiguration',
            name='available_payment_methods',
        ),
        migrations.RemoveField(
            model_name='paymentinfostepconfiguration',
            name='default_gateway',
        ),
        migrations.RemoveField(
            model_name='paymentinfostepconfiguration',
            name='refund_deadline_days',
        ),
        migrations.RemoveField(
            model_name='paymentinfostepconfiguration',
            name='refund_percentage',
        ),
        migrations.RemoveField(
            model_name='paymentinfostepconfiguration',
            name='refund_policy_text',
        ),
        migrations.AlterField(
            model_name='paymentinfostepconfiguration',
            name='accept_deposit',
            field=models.BooleanField(default=True, help_text='Show option to pay deposit (amount from PaymentSettings.default_deposit_percentage)'),
        ),
    ]
