# Generated by Django 5.2.1 on 2025-12-13 10:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingflow', '0016_cleanup_review_booking_steps'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentTermsConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deposit_type', models.CharField(blank=True, choices=[('PERCENTAGE', 'Percentage of Total'), ('FIXED', 'Fixed Amount')], help_text='Override: Type of deposit calculation (null = use global)', max_length=20, null=True)),
                ('deposit_percentage', models.DecimalField(blank=True, decimal_places=2, help_text='Override: Deposit as percentage of total (null = use global)', max_digits=5, null=True)),
                ('deposit_fixed_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Override: Fixed deposit amount (null = use global)', max_digits=10, null=True)),
                ('deposit_is_refundable', models.BooleanField(blank=True, help_text='Override: Whether deposit is refundable (null = use global)', null=True)),
                ('deposit_is_deductible', models.BooleanField(blank=True, help_text='Override: Whether deposit is deducted from total (null = use global)', null=True)),
                ('deposit_waived_on_full_payment', models.BooleanField(blank=True, help_text='Override: Whether deposit is waived on full payment (null = use global)', null=True)),
                ('late_fee_type', models.CharField(blank=True, choices=[('FIXED', 'Fixed Amount'), ('PERCENTAGE', 'Percentage of Invoice')], help_text='Override: Type of late fee calculation (null = use global)', max_length=20, null=True)),
                ('late_fee_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Override: Fixed late fee amount (null = use global)', max_digits=10, null=True)),
                ('late_fee_percentage', models.DecimalField(blank=True, decimal_places=2, help_text='Override: Late fee as percentage (null = use global)', max_digits=5, null=True)),
                ('security_deposit_enabled', models.BooleanField(blank=True, help_text='Override: Whether security deposit is enabled (null = use global)', null=True)),
                ('security_deposit_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Override: Security deposit amount (null = use global)', max_digits=10, null=True)),
                ('security_deposit_is_refundable', models.BooleanField(blank=True, help_text='Override: Whether security deposit is refundable (null = use global)', null=True)),
                ('security_deposit_description', models.CharField(blank=True, help_text='Override: Security deposit description (empty = use global)', max_length=255)),
                ('cancellation_admin_fee_percentage', models.DecimalField(blank=True, decimal_places=2, help_text='Override: Admin fee percentage on cancellation (null = use global)', max_digits=5, null=True)),
                ('downpayment_percentage', models.DecimalField(blank=True, decimal_places=2, help_text='Override: Downpayment percentage of TCP (null = use global)', max_digits=5, null=True)),
                ('downpayment_due_days', models.PositiveIntegerField(blank=True, help_text='Override: Days after booking for downpayment (null = use global)', null=True)),
                ('balance_due_days', models.PositiveIntegerField(blank=True, help_text='Override: Days before event for balance due (null = use global)', null=True)),
                ('balance_due_type', models.CharField(blank=True, choices=[('DAYS_BEFORE', 'Specific Days Before Event'), ('DAY_BEFORE', 'Day Before Event')], help_text='Override: When balance is due (null = use global)', max_length=20, null=True)),
                ('step', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment_terms_config', to='bookingflow.bookingflowstep')),
            ],
            options={
                'verbose_name': 'Payment Terms Configuration',
                'verbose_name_plural': 'Payment Terms Configurations',
            },
        ),
    ]
