# Generated by Django 5.2.1 on 2025-12-16 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingflow', '0017_add_payment_terms_configuration'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttermsconfiguration',
            name='child_pricing_enabled',
            field=models.BooleanField(blank=True, help_text='Override: Enable age-based pricing (null = use global)', null=True),
        ),
        migrations.AddField(
            model_name='paymenttermsconfiguration',
            name='child_pricing_tiers',
            field=models.JSONField(blank=True, help_text='Override: Age-based pricing tiers (null = use global)', null=True),
        ),
        migrations.AddField(
            model_name='paymenttermsconfiguration',
            name='date_blocking_policy',
            field=models.CharField(blank=True, choices=[('IMMEDIATE', 'Block Immediately on Booking'), ('ON_DOWNPAYMENT', 'Block When Downpayment Received')], help_text='Override: When to block dates (null = use global)', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='paymenttermsconfiguration',
            name='downpayment_deadline_days',
            field=models.PositiveIntegerField(blank=True, help_text='Override: Days before auto-cancellation if downpayment not received (null = use global)', null=True),
        ),
        migrations.AddField(
            model_name='paymenttermsconfiguration',
            name='downpayment_due_reference',
            field=models.CharField(blank=True, choices=[('DAYS_AFTER_BOOKING', 'Days After Booking'), ('DAYS_BEFORE_EVENT', 'Days Before Event')], help_text='Override: Reference point for downpayment due date (null = use global)', max_length=20, null=True),
        ),
    ]
