# Generated by Django 5.2.1 on 2025-12-18 23:56

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingflow', '0018_paymenttermsconfiguration_child_pricing_enabled_and_more'),
        ('venues', '0003_venue_custom_package_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingflowstep',
            name='step_type',
            field=models.CharField(choices=[('introduction', 'Introduction'), ('venue_selection', 'Venue Selection'), ('date_time', 'Date & Time Selection'), ('questionnaire', 'Questionnaire'), ('package_selection', 'Package Selection'), ('addon_selection', 'Add-on Selection'), ('pricing_summary', 'Pricing Summary'), ('contact_info', 'Contact Information'), ('payment_info', 'Payment Information'), ('confirmation', 'Confirmation')], max_length=50),
        ),
        migrations.CreateModel(
            name='VenueSelectionStepConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('min_venues', models.PositiveIntegerField(default=1, help_text='Minimum number of venues to select')),
                ('max_venues', models.PositiveIntegerField(default=5, help_text='Maximum number of venues to select')),
                ('show_pricing', models.BooleanField(default=True, help_text='Show standalone pricing for each venue')),
                ('show_included_hours', models.BooleanField(default=True, help_text='Show included hours for each venue')),
                ('show_bundle_discount', models.BooleanField(default=True, help_text='Show bundle discount for multi-venue selections')),
                ('bundle_discount_percent', models.DecimalField(decimal_places=2, default=Decimal('10.00'), help_text='Discount percentage for selecting multiple venues', max_digits=5)),
                ('require_primary_selection', models.BooleanField(default=True, help_text='Require client to select which venue determines datetime rules')),
                ('title', models.CharField(blank=True, default='Select Your Venues', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Description text shown at the top of the step')),
                ('primary_venue_help_text', models.CharField(blank=True, default='Select a primary venue - this determines your available dates and times.', max_length=255)),
                ('available_venues', models.ManyToManyField(blank=True, help_text='Specific venues to show (empty = all rentable venues)', limit_choices_to={'is_active': True, 'is_rentable_standalone': True}, to='venues.venue')),
                ('step', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='venue_selection_config', to='bookingflow.bookingflowstep')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
