# Generated by Django 5.2.1 on 2025-12-19 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingflow', '0019_venue_selection_step_config'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venueselectionstepconfiguration',
            name='description',
            field=models.TextField(blank=True, default='Choose which spaces to include in your booking.', help_text='Description text shown at the top of the step'),
        ),
        migrations.AlterField(
            model_name='venueselectionstepconfiguration',
            name='primary_venue_help_text',
            field=models.CharField(blank=True, default='', help_text='Deprecated: No longer shown in UI', max_length=255),
        ),
        migrations.AlterField(
            model_name='venueselectionstepconfiguration',
            name='require_primary_selection',
            field=models.BooleanField(default=False, help_text='Deprecated: Primary venue is auto-selected (first selected venue)'),
        ),
        migrations.AlterField(
            model_name='venueselectionstepconfiguration',
            name='title',
            field=models.CharField(blank=True, default='Select Your Spaces', max_length=255),
        ),
    ]
