# Generated by Django 5.2.1 on 2025-12-19 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookingflow', '0020_update_venue_selection_defaults'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venueselectionstepconfiguration',
            name='primary_venue_help_text',
        ),
        migrations.RemoveField(
            model_name='venueselectionstepconfiguration',
            name='require_primary_selection',
        ),
    ]
