# Generated by Django 5.2.1 on 2025-12-19 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingflow', '0021_remove_deprecated_primary_venue_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='venueselectionstepconfiguration',
            name='show_package_recommendations',
            field=models.BooleanField(default=True, help_text='Show matching pre-made packages when venues are selected'),
        ),
        migrations.AddField(
            model_name='venueselectionstepconfiguration',
            name='show_view_packages_option',
            field=models.BooleanField(default=True, help_text="Show 'View our packages' link for users who want to browse packages"),
        ),
        migrations.AddField(
            model_name='venueselectionstepconfiguration',
            name='view_packages_button_text',
            field=models.CharField(blank=True, default='Not sure? View our packages instead', help_text="Text for the 'view packages' button", max_length=255),
        ),
    ]
