# Generated by Django 5.2.1 on 2025-12-19 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingflow', '0022_add_venue_selection_package_recommendation_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='datetimestepconfiguration',
            name='max_event_days',
            field=models.PositiveIntegerField(default=7, help_text='Maximum consecutive days allowed for multi-day events'),
        ),
    ]
