# Generated by Django 5.2.1 on 2025-12-19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingflow', '0023_add_max_event_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='datetimestepconfiguration',
            name='min_event_days',
            field=models.PositiveIntegerField(
                default=1,
                help_text='Minimum days allowed for event selection (1 enables single-day selection in range mode)'
            ),
        ),
    ]
