# Generated by Django 5.2.1

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookingflow', '0025_remove_datetime_deprecated_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingflowstep',
            name='name',
        ),
    ]
