# Generated by Django 5.2.1 on 2025-12-23 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookingflow', '0028_add_session_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='bookingsession',
            name='session_completed_expires_idx',
        ),
    ]
