# Generated by Django 5.2.1 on 2026-01-08 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingflow', '0032_remove_venue_selection_from_non_required_flows'),
    ]

    operations = [
        migrations.AddField(
            model_name='packageselectionstepconfiguration',
            name='filter_by_event_type',
            field=models.BooleanField(default=False, help_text="When enabled, only show packages associated with the booking flow's event type. Packages with no event types are hidden when this is enabled."),
        ),
    ]
