# Generated by Django 5.2.1 on 2026-01-16 01:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookingflow', '0033_add_filter_by_event_type_to_package_config'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentinfostepconfiguration',
            name='allow_payment_plans',
        ),
    ]
