# Generated by Django 5.2.1 on 2026-01-22 14:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingflow', '0035_add_filter_by_event_type_to_addon_config'),
        ('events', '0017_add_date_reservation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='bookingsession',
            index=models.Index(fields=['booking_flow', 'is_completed'], name='bookingflow_booking_db024e_idx'),
        ),
        migrations.AddIndex(
            model_name='bookingsession',
            index=models.Index(fields=['client', '-created_at'], name='bookingflow_client__6fb921_idx'),
        ),
    ]
