# Generated by Django 5.2.8 on 2026-03-20 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingflow', '0036_add_performance_indexes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricingsummarystepconfiguration',
            name='header_text',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
