# Generated by Django 5.2.1 on 2025-08-27 20:15

import core.utils.encryption
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_encrypt_gateway_config'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentgateway',
            name='config',
            field=core.utils.encryption.EncryptedJSONField(blank=True, default=''),
        ),
    ]
