# Generated by Django 5.2.1 on 2025-08-28 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_alter_paymentgateway_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='currency',
            field=models.CharField(default='PHP', help_text='Payment currency (ISO 4217 code)', max_length=3),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='currency',
            field=models.CharField(default='PHP', help_text='Transaction currency (ISO 4217 code)', max_length=3),
        ),
    ]
