# Generated by Django 5.2.1 on 2025-08-28 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_add_currency_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='currency',
            field=models.CharField(default='PHP', help_text='Invoice currency (ISO 4217 code)', max_length=3),
        ),
        migrations.AddField(
            model_name='paymentplan',
            name='currency',
            field=models.CharField(default='PHP', help_text='Payment plan currency (ISO 4217 code)', max_length=3),
        ),
        migrations.AddField(
            model_name='refund',
            name='currency',
            field=models.CharField(default='PHP', help_text='Refund currency (ISO 4217 code)', max_length=3),
        ),
    ]
