# Generated by Django 5.2.1 on 2025-09-21 01:58

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingflow', '0011_paymentinfostepconfiguration_allow_refunds_and_more'),
        ('payments', '0006_add_currency_to_invoice_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentinstallment',
            name='last_reminder_sent',
            field=models.DateTimeField(blank=True, help_text='Date when last reminder was sent', null=True),
        ),
        migrations.AddField(
            model_name='paymentinstallment',
            name='late_fee_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Late fee amount applied to this installment', max_digits=10),
        ),
        migrations.AddField(
            model_name='paymentinstallment',
            name='late_fee_applied_date',
            field=models.DateField(blank=True, help_text='Date when late fee was applied', null=True),
        ),
        migrations.AddField(
            model_name='paymentinstallment',
            name='reminder_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of reminders sent for this installment'),
        ),
        migrations.AddField(
            model_name='paymentplan',
            name='auto_payment_enabled',
            field=models.BooleanField(default=False, help_text='Automatically charge saved payment method'),
        ),
        migrations.AddField(
            model_name='paymentplan',
            name='auto_payment_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auto_payment_plans', to='payments.paymentmethod'),
        ),
        migrations.AddField(
            model_name='paymentplan',
            name='created_from_booking_session',
            field=models.ForeignKey(blank=True, help_text='Booking session that created this plan', null=True, on_delete=django.db.models.deletion.SET_NULL, to='bookingflow.bookingsession'),
        ),
        migrations.AddField(
            model_name='paymentplan',
            name='final_payment_date',
            field=models.DateField(blank=True, help_text='Date of final installment', null=True),
        ),
        migrations.AddField(
            model_name='paymentplan',
            name='grace_period_days',
            field=models.PositiveIntegerField(default=7, help_text='Days after due date before marking overdue'),
        ),
        migrations.AddField(
            model_name='paymentplan',
            name='next_payment_date',
            field=models.DateField(blank=True, help_text='Date of next scheduled payment', null=True),
        ),
        migrations.AddField(
            model_name='paymentplan',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Setup'), ('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('SUSPENDED', 'Suspended'), ('DEFAULTED', 'Defaulted'), ('CANCELLED', 'Cancelled')], default='PENDING', help_text='Current status of the payment plan', max_length=20),
        ),
        migrations.AddField(
            model_name='paymentplan',
            name='terms_accepted',
            field=models.BooleanField(default=False, help_text='Client accepted payment plan terms'),
        ),
        migrations.AddField(
            model_name='paymentplan',
            name='terms_accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paymentplan',
            name='terms_accepted_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='paymentinstallment',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('OVERDUE', 'Overdue'), ('PARTIAL', 'Partially Paid'), ('WAIVED', 'Waived'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20),
        ),
    ]
