# Generated by Django 5.2.1 on 2025-09-21 02:28

import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_paymentinstallment_last_reminder_sent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('balance_due_days', models.PositiveIntegerField(default=30, help_text='Default number of days before event when balance is due')),
                ('grace_period_days', models.PositiveIntegerField(default=7, help_text='Default grace period days before marking payments overdue')),
                ('default_installments', models.PositiveIntegerField(default=2, help_text='Default number of installments for payment plans')),
                ('default_installment_frequency', models.CharField(choices=[('WEEKLY', 'Weekly'), ('BIWEEKLY', 'Bi-weekly'), ('MONTHLY', 'Monthly')], default='MONTHLY', help_text='Default frequency for payment installments', max_length=20)),
                ('late_fee_enabled', models.BooleanField(default=True, help_text='Enable automatic late fee application')),
                ('default_late_fee_amount', models.DecimalField(decimal_places=2, default=Decimal('25.00'), help_text='Default late fee amount to apply to overdue payments', max_digits=10)),
                ('default_deposit_percentage', models.DecimalField(decimal_places=2, default=Decimal('50.00'), help_text='Default deposit percentage (0-100)', max_digits=5)),
                ('default_currency', models.CharField(default='PHP', help_text='Default currency (ISO 4217 code)', max_length=3)),
                ('auto_payment_retry_attempts', models.PositiveIntegerField(default=3, help_text='Number of automatic retry attempts for failed payments')),
                ('auto_payment_retry_delay_days', models.PositiveIntegerField(default=2, help_text='Days to wait between automatic payment retry attempts')),
            ],
            options={
                'verbose_name': 'Payment Settings',
                'verbose_name_plural': 'Payment Settings',
            },
        ),
    ]
