# Generated by Django 5.2.1 on 2025-09-25 23:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0008_paymentsettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentNumberSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('year', models.PositiveIntegerField(help_text='Year for which this sequence applies', unique=True)),
                ('next_number', models.PositiveIntegerField(default=1, help_text='Next sequence number to use for this year')),
            ],
            options={
                'verbose_name': 'Payment Number Sequence',
                'verbose_name_plural': 'Payment Number Sequences',
                'ordering': ['-year'],
            },
        ),
    ]
