# Generated by Django 5.2.1 on 2025-09-25 23:26

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0009_add_payment_number_sequence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('CREATED', 'Created'), ('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled'), ('REFUNDED', 'Refunded')], default='CREATED', max_length=20),
        ),
        migrations.CreateModel(
            name='PaymentStateHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('from_state', models.CharField(help_text='Previous payment state', max_length=20)),
                ('to_state', models.CharField(help_text='New payment state', max_length=20)),
                ('reason', models.CharField(help_text='Reason for state transition', max_length=255)),
                ('triggered_by', models.CharField(default='system', help_text='Who or what triggered the state change', max_length=100)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional context data for the transition')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, help_text='When the state transition occurred')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='state_history', to='payments.payment')),
            ],
            options={
                'verbose_name': 'Payment State History',
                'verbose_name_plural': 'Payment State Histories',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['payment', '-timestamp'], name='payments_pa_payment_f9d0b9_idx'), models.Index(fields=['to_state', '-timestamp'], name='payments_pa_to_stat_e8cdd7_idx')],
            },
        ),
    ]
