# Generated by Django 5.2.1 on 2025-09-26 00:37

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0010_add_payment_state_history'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentWebhookLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('gateway_code', models.CharField(help_text='Payment gateway code (stripe, paypal, etc.)', max_length=50)),
                ('event_type', models.CharField(help_text='Gateway-specific event type', max_length=100)),
                ('event_id', models.CharField(help_text='Unique event identifier from gateway', max_length=255, unique=True)),
                ('transaction_id', models.CharField(help_text='Gateway transaction identifier', max_length=255)),
                ('raw_data', models.JSONField(help_text='Complete webhook payload from gateway')),
                ('received_at', models.DateTimeField(default=django.utils.timezone.now, help_text='When webhook was received')),
                ('processed_at', models.DateTimeField(blank=True, help_text='When webhook was processed', null=True)),
                ('processed_successfully', models.BooleanField(default=False, help_text='Whether webhook was processed successfully')),
                ('action_taken', models.CharField(blank=True, help_text='Action taken during processing', max_length=100)),
                ('error_message', models.TextField(blank=True, help_text='Error message if processing failed')),
                ('retry_count', models.PositiveIntegerField(default=0, help_text='Number of processing retry attempts')),
            ],
            options={
                'verbose_name': 'Payment Webhook Log',
                'verbose_name_plural': 'Payment Webhook Logs',
                'ordering': ['-received_at'],
                'indexes': [models.Index(fields=['gateway_code', '-received_at'], name='payments_pa_gateway_7c10d9_idx'), models.Index(fields=['event_type', '-received_at'], name='payments_pa_event_t_37998a_idx'), models.Index(fields=['processed_successfully', '-received_at'], name='payments_pa_process_0d5964_idx'), models.Index(fields=['transaction_id'], name='payments_pa_transac_d80a59_idx')],
            },
        ),
        migrations.CreateModel(
            name='PaymentEventStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('event_id', models.CharField(help_text='Unique identifier for this domain event', max_length=255, unique=True)),
                ('event_type', models.CharField(help_text='Type of domain event (PaymentCompletedEvent, etc.)', max_length=100)),
                ('payment_number', models.CharField(help_text='Payment number for easy lookup', max_length=50)),
                ('event_data', models.JSONField(help_text='Complete event data including transition details')),
                ('from_state', models.CharField(help_text='Previous payment state', max_length=20)),
                ('to_state', models.CharField(help_text='New payment state', max_length=20)),
                ('transition_reason', models.CharField(help_text='Reason for state transition', max_length=255)),
                ('triggered_by', models.CharField(help_text='Who or what triggered the state change', max_length=100)),
                ('processed', models.BooleanField(default=False, help_text='Whether this event has been processed by all handlers')),
                ('processing_started_at', models.DateTimeField(blank=True, help_text='When event processing started', null=True)),
                ('processing_completed_at', models.DateTimeField(blank=True, help_text='When event processing completed', null=True)),
                ('external_system_refs', models.JSONField(blank=True, default=dict, help_text='References to external systems that need to be notified')),
                ('processing_errors', models.JSONField(blank=True, default=list, help_text='Any errors encountered during event processing')),
                ('retry_count', models.PositiveIntegerField(default=0, help_text='Number of processing retry attempts')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stored_events', to='payments.payment')),
            ],
            options={
                'verbose_name': 'Payment Event Store',
                'verbose_name_plural': 'Payment Event Store',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['payment', '-created_at'], name='payments_pa_payment_c98452_idx'), models.Index(fields=['event_type', '-created_at'], name='payments_pa_event_t_d0c28f_idx'), models.Index(fields=['processed', '-created_at'], name='payments_pa_process_e6f3b2_idx'), models.Index(fields=['to_state', '-created_at'], name='payments_pa_to_stat_c95fd7_idx')],
            },
        ),
    ]
