# Generated by Django 5.2.1 on 2025-09-30 23:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0012_invoicelineitem_base_unit_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentsettings',
            name='allow_refunds',
            field=models.BooleanField(default=True, help_text='Allow refunds globally'),
        ),
        migrations.AddField(
            model_name='paymentsettings',
            name='default_payment_gateways',
            field=models.ManyToManyField(blank=True, help_text='Default payment gateways available globally', related_name='global_default_settings', to='payments.paymentgateway'),
        ),
        migrations.AddField(
            model_name='paymentsettings',
            name='primary_payment_gateway',
            field=models.ForeignKey(blank=True, help_text='Primary payment gateway (pre-selected by default)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_for_global_settings', to='payments.paymentgateway'),
        ),
        migrations.AddField(
            model_name='paymentsettings',
            name='refund_deadline_hours',
            field=models.PositiveIntegerField(default=48, help_text='Hours before event when refunds are no longer allowed'),
        ),
        migrations.AddField(
            model_name='paymentsettings',
            name='refund_percentage',
            field=models.PositiveIntegerField(default=100, help_text='Percentage of payment that can be refunded (0-100)'),
        ),
        migrations.AddField(
            model_name='paymentsettings',
            name='refund_policy_text',
            field=models.TextField(blank=True, help_text='Default refund policy text to display to clients'),
        ),
    ]
