# Generated by Django 5.2.1 on 2025-12-13 10:22

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0015_alter_invoice_created_at_alter_invoice_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentsettings',
            name='balance_due_type',
            field=models.CharField(choices=[('DAYS_BEFORE', 'Specific Days Before Event'), ('DAY_BEFORE', 'Day Before Event')], default='DAYS_BEFORE', help_text='When remaining balance is due', max_length=20),
        ),
        migrations.AddField(
            model_name='paymentsettings',
            name='cancellation_admin_fee_percentage',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Administrative processing fee percentage on cancellations', max_digits=5),
        ),
        migrations.AddField(
            model_name='paymentsettings',
            name='deposit_fixed_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Fixed deposit amount (used when deposit_type is FIXED)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='paymentsettings',
            name='deposit_is_deductible',
            field=models.BooleanField(default=True, help_text='Whether the deposit is deducted from the total contract price'),
        ),
        migrations.AddField(
            model_name='paymentsettings',
            name='deposit_is_refundable',
            field=models.BooleanField(default=False, help_text='Whether the deposit is refundable on cancellation'),
        ),
        migrations.AddField(
            model_name='paymentsettings',
            name='deposit_type',
            field=models.CharField(choices=[('PERCENTAGE', 'Percentage of Total'), ('FIXED', 'Fixed Amount')], default='PERCENTAGE', help_text='Type of deposit calculation', max_length=20),
        ),
        migrations.AddField(
            model_name='paymentsettings',
            name='deposit_waived_on_full_payment',
            field=models.BooleanField(default=True, help_text='Whether the deposit is waived if client pays in full upfront'),
        ),
        migrations.AddField(
            model_name='paymentsettings',
            name='downpayment_due_days',
            field=models.PositiveIntegerField(default=7, help_text='Days after booking to pay downpayment (to block date)'),
        ),
        migrations.AddField(
            model_name='paymentsettings',
            name='downpayment_percentage',
            field=models.DecimalField(decimal_places=2, default=Decimal('30.00'), help_text='Downpayment percentage of total contract price (0-100)', max_digits=5),
        ),
        migrations.AddField(
            model_name='paymentsettings',
            name='late_fee_percentage',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Late fee as percentage of invoice amount (used when late_fee_type is PERCENTAGE)', max_digits=5),
        ),
        migrations.AddField(
            model_name='paymentsettings',
            name='late_fee_type',
            field=models.CharField(choices=[('FIXED', 'Fixed Amount'), ('PERCENTAGE', 'Percentage of Invoice')], default='FIXED', help_text='Type of late fee calculation', max_length=20),
        ),
        migrations.AddField(
            model_name='paymentsettings',
            name='security_deposit_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Security deposit amount (e.g., for keys, damages)', max_digits=10),
        ),
        migrations.AddField(
            model_name='paymentsettings',
            name='security_deposit_description',
            field=models.CharField(blank=True, help_text="Description of what security deposit covers (e.g., 'for keys upon check-in')", max_length=255),
        ),
        migrations.AddField(
            model_name='paymentsettings',
            name='security_deposit_enabled',
            field=models.BooleanField(default=False, help_text='Enable security deposit requirement'),
        ),
        migrations.AddField(
            model_name='paymentsettings',
            name='security_deposit_is_refundable',
            field=models.BooleanField(default=True, help_text='Whether security deposit is refundable after event/inspection'),
        ),
    ]
