# Generated by Django 5.2.1 on 2025-12-16 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0017_remove_paymentsettings_default_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentsettings',
            name='child_pricing_enabled',
            field=models.BooleanField(default=False, help_text='Enable age-based pricing tiers'),
        ),
        migrations.AddField(
            model_name='paymentsettings',
            name='child_pricing_tiers',
            field=models.JSONField(blank=True, default=list, help_text='Age-based pricing tiers: [{min_age, max_age, discount_percentage, label}]'),
        ),
        migrations.AddField(
            model_name='paymentsettings',
            name='date_blocking_policy',
            field=models.CharField(choices=[('IMMEDIATE', 'Block Immediately on Booking'), ('ON_DOWNPAYMENT', 'Block When Downpayment Received')], default='IMMEDIATE', help_text='When to block dates for new bookings', max_length=20),
        ),
        migrations.AddField(
            model_name='paymentsettings',
            name='downpayment_deadline_days',
            field=models.PositiveIntegerField(default=7, help_text='Days after booking before event is auto-cancelled if downpayment not received (for ON_DOWNPAYMENT policy)'),
        ),
        migrations.AddField(
            model_name='paymentsettings',
            name='downpayment_due_reference',
            field=models.CharField(choices=[('DAYS_AFTER_BOOKING', 'Days After Booking'), ('DAYS_BEFORE_EVENT', 'Days Before Event')], default='DAYS_AFTER_BOOKING', help_text='Reference point for downpayment due date calculation', max_length=20),
        ),
    ]
