# Generated by Django 5.2.1 on 2025-12-18 05:08

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0018_paymentsettings_child_pricing_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentsettings',
            name='date_hold_duration_days',
            field=models.PositiveIntegerField(default=7, help_text='Default duration for temporary date holds in days'),
        ),
        migrations.AddField(
            model_name='paymentsettings',
            name='date_hold_enabled',
            field=models.BooleanField(default=True, help_text='Enable temporary date holding'),
        ),
        migrations.AddField(
            model_name='paymentsettings',
            name='date_hold_extension_days',
            field=models.PositiveIntegerField(default=3, help_text='Duration of each hold extension in days'),
        ),
        migrations.AddField(
            model_name='paymentsettings',
            name='date_hold_max_extensions',
            field=models.PositiveIntegerField(default=1, help_text='Maximum number of hold extensions allowed'),
        ),
        migrations.AddField(
            model_name='paymentsettings',
            name='late_checkout_fee_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('300.00'), help_text='Late checkout fee amount (fixed or per hour)', max_digits=10),
        ),
        migrations.AddField(
            model_name='paymentsettings',
            name='late_checkout_fee_enabled',
            field=models.BooleanField(default=False, help_text='Enable late checkout fee'),
        ),
        migrations.AddField(
            model_name='paymentsettings',
            name='late_checkout_fee_percentage',
            field=models.DecimalField(decimal_places=2, default=Decimal('10.00'), help_text='Late checkout fee as percentage (if type is PERCENTAGE)', max_digits=5),
        ),
        migrations.AddField(
            model_name='paymentsettings',
            name='late_checkout_fee_type',
            field=models.CharField(choices=[('FIXED', 'Fixed Amount'), ('HOURLY', 'Per Hour'), ('PERCENTAGE', 'Percentage of Contract')], default='HOURLY', help_text='Type of late checkout fee calculation', max_length=20),
        ),
        migrations.AddField(
            model_name='paymentsettings',
            name='late_checkout_grace_minutes',
            field=models.PositiveIntegerField(default=15, help_text='Minutes after scheduled checkout before late fee applies'),
        ),
        migrations.AddField(
            model_name='paymentsettings',
            name='late_checkout_max_hours',
            field=models.PositiveIntegerField(default=4, help_text='Maximum hours for late checkout billing'),
        ),
        migrations.AddField(
            model_name='paymentsettings',
            name='rescheduling_fee_enabled',
            field=models.BooleanField(default=False, help_text='Enable rescheduling fee when client changes event date'),
        ),
        migrations.AddField(
            model_name='paymentsettings',
            name='rescheduling_fee_fixed_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Fixed rescheduling fee amount', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='paymentsettings',
            name='rescheduling_fee_percentage',
            field=models.DecimalField(decimal_places=2, default=Decimal('10.00'), help_text='Rescheduling fee as percentage of contract total', max_digits=5),
        ),
        migrations.AddField(
            model_name='paymentsettings',
            name='rescheduling_fee_type',
            field=models.CharField(choices=[('PERCENTAGE', 'Percentage of Total'), ('FIXED', 'Fixed Amount')], default='PERCENTAGE', help_text='Type of rescheduling fee calculation', max_length=20),
        ),
        migrations.AddField(
            model_name='paymentsettings',
            name='rescheduling_grace_period_hours',
            field=models.PositiveIntegerField(default=24, help_text='Hours after booking during which rescheduling is free'),
        ),
        migrations.AddField(
            model_name='paymentsettings',
            name='service_charge_enabled',
            field=models.BooleanField(default=False, help_text='Enable service charge on bookings'),
        ),
        migrations.AddField(
            model_name='paymentsettings',
            name='service_charge_percentage',
            field=models.DecimalField(decimal_places=2, default=Decimal('10.00'), help_text='Service charge percentage (0-100)', max_digits=5),
        ),
    ]
