# Generated by Django 5.2.1 on 2026-01-16 01:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0019_paymentsettings_date_hold_duration_days_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='installment',
        ),
        migrations.RemoveField(
            model_name='paymentplan',
            name='auto_payment_method',
        ),
        migrations.RemoveField(
            model_name='paymentplan',
            name='created_from_booking_session',
        ),
        migrations.RemoveField(
            model_name='paymentplan',
            name='event',
        ),
        migrations.RemoveField(
            model_name='paymentplan',
            name='quote',
        ),
        migrations.DeleteModel(
            name='PaymentInstallment',
        ),
        migrations.DeleteModel(
            name='PaymentPlan',
        ),
    ]
