# Generated by Django 5.2.1 on 2026-01-18 05:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0020_remove_payment_plan_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentDispute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gateway_dispute_id', models.CharField(help_text='Dispute ID from the payment gateway', max_length=255, unique=True)),
                ('gateway_transaction_id', models.CharField(help_text='Original transaction ID from gateway', max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Disputed amount', max_digits=10)),
                ('currency', models.CharField(default='PHP', help_text='Currency of the disputed amount', max_length=3)),
                ('reason', models.CharField(choices=[('DUPLICATE', 'Duplicate Charge'), ('FRAUDULENT', 'Fraudulent'), ('SUBSCRIPTION_CANCELED', 'Subscription Canceled'), ('PRODUCT_UNACCEPTABLE', 'Product Unacceptable'), ('PRODUCT_NOT_RECEIVED', 'Product Not Received'), ('UNRECOGNIZED', 'Unrecognized'), ('CREDIT_NOT_PROCESSED', 'Credit Not Processed'), ('GENERAL', 'General'), ('OTHER', 'Other')], default='OTHER', help_text='Reason for the dispute', max_length=50)),
                ('reason_description', models.TextField(blank=True, help_text='Detailed description of the dispute reason')),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('UNDER_REVIEW', 'Under Review'), ('WON', 'Won'), ('LOST', 'Lost'), ('CLOSED', 'Closed')], default='OPEN', help_text='Current status of the dispute', max_length=20)),
                ('evidence_due_by', models.DateTimeField(blank=True, help_text='Deadline to submit evidence', null=True)),
                ('resolved_at', models.DateTimeField(blank=True, help_text='When the dispute was resolved', null=True)),
                ('resolution_notes', models.TextField(blank=True, help_text='Notes about the resolution')),
                ('gateway_data', models.JSONField(default=dict, help_text='Raw dispute data from gateway webhook')),
                ('admin_notified', models.BooleanField(default=False, help_text='Whether admin has been notified')),
                ('admin_notified_at', models.DateTimeField(blank=True, help_text='When admin was notified', null=True)),
                ('assigned_to', models.ForeignKey(blank=True, help_text='Admin user assigned to handle this dispute', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_disputes', to=settings.AUTH_USER_MODEL)),
                ('gateway', models.ForeignKey(help_text='Payment gateway that reported the dispute', on_delete=django.db.models.deletion.PROTECT, to='payments.paymentgateway')),
                ('payment', models.ForeignKey(blank=True, help_text='Related payment (may be null if payment not found)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='disputes', to='payments.payment')),
            ],
            options={
                'verbose_name': 'Payment Dispute',
                'verbose_name_plural': 'Payment Disputes',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='payments_pa_status_c6a3f8_idx'), models.Index(fields=['gateway', '-created_at'], name='payments_pa_gateway_6eb4af_idx'), models.Index(fields=['payment', '-created_at'], name='payments_pa_payment_e246f2_idx')],
            },
        ),
    ]
