# Generated by Django 5.2.1 on 2026-01-19 07:22

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0017_add_date_reservation'),
        ('payments', '0021_paymentdispute'),
        ('sales', '0006_add_venue_hours_breakdown_to_quotelineitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookDeadLetter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gateway_code', models.CharField(help_text='Payment gateway code (stripe, paypal, etc.)', max_length=50)),
                ('event_type', models.CharField(help_text='Gateway-specific event type', max_length=100)),
                ('event_id', models.CharField(help_text='Unique event identifier from gateway', max_length=255)),
                ('transaction_id', models.CharField(help_text='Gateway transaction identifier', max_length=255)),
                ('raw_data', models.JSONField(help_text='Complete webhook payload from gateway')),
                ('original_received_at', models.DateTimeField(help_text='When the webhook was originally received')),
                ('moved_to_dead_letter_at', models.DateTimeField(default=django.utils.timezone.now, help_text='When the webhook was moved to dead letter queue')),
                ('retry_count', models.PositiveIntegerField(default=0, help_text='Number of retry attempts before failure')),
                ('final_error', models.TextField(blank=True, help_text='Final error message that caused permanent failure')),
                ('resolved', models.BooleanField(default=False, help_text='Whether this dead letter has been resolved')),
                ('resolved_at', models.DateTimeField(blank=True, help_text='When the dead letter was resolved', null=True)),
                ('resolution_notes', models.TextField(blank=True, help_text='Notes about how the dead letter was resolved')),
            ],
            options={
                'verbose_name': 'Webhook Dead Letter',
                'verbose_name_plural': 'Webhook Dead Letters',
                'ordering': ['-moved_to_dead_letter_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='invoice',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='paymentsettings',
            name='default_installment_frequency',
        ),
        migrations.RemoveField(
            model_name='paymentsettings',
            name='default_installments',
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['status'], name='payments_in_status_45b876_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['due_date'], name='payments_in_due_dat_9c830a_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['event', 'status'], name='payments_in_event_i_779151_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['client', 'status'], name='payments_in_client__8fc948_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['status'], name='payments_pa_status_7ad4af_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['due_date'], name='payments_pa_due_dat_752274_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['event', 'status'], name='payments_pa_event_i_9abc7d_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['transaction_id'], name='payments_pa_transac_c1fd68_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['gateway', 'status'], name='payments_pa_gateway_e36c34_idx'),
        ),
        migrations.AddField(
            model_name='webhookdeadletter',
            name='original_webhook',
            field=models.ForeignKey(blank=True, help_text='Reference to the original webhook log', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dead_letters', to='payments.paymentwebhooklog'),
        ),
        migrations.AddField(
            model_name='webhookdeadletter',
            name='resolved_by',
            field=models.ForeignKey(blank=True, help_text='Admin user who resolved the dead letter', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_dead_letters', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='webhookdeadletter',
            index=models.Index(fields=['resolved', '-moved_to_dead_letter_at'], name='payments_we_resolve_79f6f3_idx'),
        ),
        migrations.AddIndex(
            model_name='webhookdeadletter',
            index=models.Index(fields=['gateway_code', '-moved_to_dead_letter_at'], name='payments_we_gateway_ffd5f6_idx'),
        ),
        migrations.AddIndex(
            model_name='webhookdeadletter',
            index=models.Index(fields=['event_id'], name='payments_we_event_i_8fdd18_idx'),
        ),
    ]
