# Generated by Django 5.2.1 on 2026-01-22 14:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0018_add_performance_indexes'),
        ('payments', '0022_webhookdeadletter_alter_invoice_options_and_more'),
        ('sales', '0006_add_venue_hours_breakdown_to_quotelineitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['quote'], name='payments_in_quote_i_edc987_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['invoice', 'status'], name='payments_pa_invoice_e2429a_idx'),
        ),
    ]
