# Generated by Django 5.2.1 on 2025-12-18 23:42

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0015_add_guest_count_fields'),
        ('payments', '0019_paymentsettings_date_hold_duration_days_and_more'),
        ('products', '0005_add_is_tax_inclusive_to_productoption'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VIPSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_program_enabled', models.BooleanField(default=True, help_text='Master toggle for the VIP program')),
                ('program_name', models.CharField(default='VIP Program', help_text='Display name for the loyalty program', max_length=100)),
                ('earning_automatic_enabled', models.BooleanField(default=True, help_text='Enable automatic tier upgrades based on spending/bookings')),
                ('earning_points_enabled', models.BooleanField(default=False, help_text='Enable points-based loyalty system')),
                ('earning_manual_enabled', models.BooleanField(default=True, help_text='Allow manual VIP assignment by admins')),
                ('automatic_earning_type', models.CharField(choices=[('SPENDING', 'Total Spending'), ('BOOKINGS', 'Completed Bookings'), ('BOTH', 'Both (Any Condition Met)')], default='SPENDING', help_text='Criteria for automatic tier upgrades', max_length=20)),
                ('points_per_currency_spent', models.DecimalField(decimal_places=2, default=Decimal('1.00'), help_text='Points earned per currency unit spent', max_digits=5)),
                ('points_currency_unit', models.DecimalField(decimal_places=2, default=Decimal('100.00'), help_text='Currency amount that earns points_per_currency_spent', max_digits=10)),
                ('points_expiry_months', models.PositiveIntegerField(default=0, help_text='Months until points expire (0 = never expire)')),
                ('expiration_type', models.CharField(choices=[('NEVER', 'Never Expires'), ('INACTIVITY', 'After X Months Inactivity'), ('ANNUAL', 'Annual Renewal Required')], default='NEVER', help_text='How VIP status expires', max_length=20)),
                ('expiration_months', models.PositiveIntegerField(default=12, help_text='Months for expiration (used with INACTIVITY or ANNUAL)')),
                ('show_vip_status_to_client', models.BooleanField(default=True, help_text='Show VIP tier/status in client portal')),
                ('show_tier_progress_to_client', models.BooleanField(default=True, help_text='Show progress toward next tier in client portal')),
                ('show_available_rewards_to_client', models.BooleanField(default=True, help_text='Show available benefits/rewards in client portal')),
                ('show_points_balance_to_client', models.BooleanField(default=True, help_text='Show points balance in client portal')),
            ],
            options={
                'verbose_name': 'VIP Settings',
                'verbose_name_plural': 'VIP Settings',
            },
        ),
        migrations.CreateModel(
            name='VIPTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text="Display name for the tier (e.g., 'Gold', 'VIP', 'Platinum')", max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Description of tier benefits shown to clients')),
                ('level', models.PositiveIntegerField(help_text='Tier level - higher numbers = more exclusive', unique=True)),
                ('is_default', models.BooleanField(default=False, help_text="Default tier for new clients (typically 'Standard')")),
                ('min_total_spent', models.DecimalField(blank=True, decimal_places=2, help_text='Minimum total spending to qualify for this tier', max_digits=12, null=True)),
                ('min_completed_bookings', models.PositiveIntegerField(blank=True, help_text='Minimum completed bookings to qualify for this tier', null=True)),
                ('min_points_required', models.PositiveIntegerField(blank=True, help_text='Minimum points balance to qualify for this tier', null=True)),
                ('color', models.CharField(default='#6B7280', help_text='Hex color for tier badge (e.g., #FFD700 for gold)', max_length=7)),
                ('icon', models.CharField(blank=True, help_text='Icon name for tier display', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'VIP Tier',
                'verbose_name_plural': 'VIP Tiers',
                'ordering': ['level'],
            },
        ),
        migrations.CreateModel(
            name='ClientVIPStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('points_balance', models.PositiveIntegerField(default=0)),
                ('lifetime_points_earned', models.PositiveIntegerField(default=0)),
                ('lifetime_points_spent', models.PositiveIntegerField(default=0)),
                ('total_spent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('completed_bookings_count', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('EXPIRED', 'Expired'), ('SUSPENDED', 'Suspended')], default='ACTIVE', max_length=20)),
                ('assigned_at', models.DateTimeField(blank=True, help_text='When tier was manually assigned', null=True)),
                ('assignment_reason', models.CharField(blank=True, help_text='Reason for manual assignment', max_length=255)),
                ('expires_at', models.DateTimeField(blank=True, help_text='When VIP status expires', null=True)),
                ('last_activity_at', models.DateTimeField(auto_now=True, help_text='Last booking/payment activity')),
                ('assigned_by', models.ForeignKey(blank=True, help_text='Admin who manually assigned the tier', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vip_assignments', to=settings.AUTH_USER_MODEL)),
                ('client', models.OneToOneField(limit_choices_to={'role': 'CLIENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='vip_status', to=settings.AUTH_USER_MODEL)),
                ('current_tier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='vip.viptier')),
            ],
            options={
                'verbose_name': 'Client VIP Status',
                'verbose_name_plural': 'Client VIP Statuses',
            },
        ),
        migrations.CreateModel(
            name='VIPBenefit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('benefit_type', models.CharField(choices=[('PERCENTAGE_DISCOUNT', 'Percentage Discount'), ('FIXED_DISCOUNT', 'Fixed Amount Discount'), ('FREE_HOURS', 'Free Excess Hours'), ('WAIVE_SERVICE_CHARGE', 'Waive Service Charge'), ('WAIVE_LATE_FEE', 'Waive Late Fee'), ('WAIVE_RESCHEDULING_FEE', 'Waive Rescheduling Fee'), ('PRIORITY_BOOKING', 'Priority Booking'), ('EARLY_ACCESS', 'Early Access to Packages'), ('EXCLUSIVE_PACKAGE', 'Access to Exclusive Packages'), ('COMPLIMENTARY_ADDON', 'Complimentary Add-on')], max_length=30)),
                ('application_mode', models.CharField(choices=[('AUTOMATIC', 'Apply Automatically'), ('REDEEMABLE', 'Redeemable from Pool')], default='AUTOMATIC', max_length=20)),
                ('value', models.DecimalField(blank=True, decimal_places=2, help_text='Discount %, fixed amount, or number of free hours', max_digits=10, null=True)),
                ('max_uses_per_booking', models.PositiveIntegerField(blank=True, help_text='Maximum times this benefit can be used per booking', null=True)),
                ('max_uses_per_month', models.PositiveIntegerField(blank=True, help_text='Maximum times this benefit can be used per month', null=True)),
                ('points_cost', models.PositiveIntegerField(default=0, help_text='Points required to redeem this benefit (0 = free)')),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True, help_text='Internal description of the benefit')),
                ('display_name', models.CharField(blank=True, help_text='Client-facing name for the benefit', max_length=100)),
                ('applicable_products', models.ManyToManyField(blank=True, help_text='Products this benefit applies to (for exclusive/complimentary)', related_name='vip_benefits', to='products.productoption')),
                ('tier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='benefits', to='vip.viptier')),
            ],
            options={
                'verbose_name': 'VIP Benefit',
                'verbose_name_plural': 'VIP Benefits',
                'ordering': ['tier__level', 'benefit_type'],
            },
        ),
        migrations.CreateModel(
            name='VIPPointTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('transaction_type', models.CharField(choices=[('EARNED_BOOKING', 'Earned from Booking'), ('EARNED_PAYMENT', 'Earned from Payment'), ('EARNED_MANUAL', 'Manually Added'), ('EARNED_BONUS', 'Bonus Points'), ('SPENT_REWARD', 'Spent on Reward'), ('EXPIRED', 'Points Expired'), ('ADJUSTED', 'Manual Adjustment')], max_length=20)),
                ('points', models.IntegerField(help_text='Positive for earned, negative for spent/expired')),
                ('description', models.CharField(max_length=255)),
                ('balance_after', models.PositiveIntegerField(help_text='Points balance after this transaction')),
                ('client_vip_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='point_transactions', to='vip.clientvipstatus')),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vip_point_transactions', to='events.event')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vip_point_transactions', to='payments.payment')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vip_point_adjustments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'VIP Point Transaction',
                'verbose_name_plural': 'VIP Point Transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VIPRewardRedemption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPLIED', 'Applied'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('points_spent', models.PositiveIntegerField(default=0, help_text='Points deducted for this redemption')),
                ('value_applied', models.DecimalField(blank=True, decimal_places=2, help_text='Monetary value of the benefit applied', max_digits=10, null=True)),
                ('applied_at', models.DateTimeField(blank=True, help_text='When the benefit was applied to the booking', null=True)),
                ('benefit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redemptions', to='vip.vipbenefit')),
                ('client_vip_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redemptions', to='vip.clientvipstatus')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vip_redemptions', to='events.event')),
            ],
            options={
                'verbose_name': 'VIP Reward Redemption',
                'verbose_name_plural': 'VIP Reward Redemptions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VIPTierHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reason', models.CharField(choices=[('AUTOMATIC_UPGRADE', 'Automatic Upgrade'), ('AUTOMATIC_DOWNGRADE', 'Automatic Downgrade'), ('MANUAL_ASSIGNMENT', 'Manual Assignment'), ('EXPIRATION', 'Status Expired'), ('INITIAL', 'Initial Assignment')], max_length=30)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the tier change')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vip_tier_changes', to=settings.AUTH_USER_MODEL)),
                ('client_vip_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tier_history', to='vip.clientvipstatus')),
                ('from_tier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='vip.viptier')),
                ('to_tier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='vip.viptier')),
            ],
            options={
                'verbose_name': 'VIP Tier History',
                'verbose_name_plural': 'VIP Tier Histories',
                'ordering': ['-created_at'],
            },
        ),
    ]
