# Generated by Django 5.2.1 on 2025-12-18 23:43

from django.db import migrations


def seed_default_data(apps, schema_editor):
    """Seed default VIP settings and Standard tier."""
    VIPSettings = apps.get_model('vip', 'VIPSettings')
    VIPTier = apps.get_model('vip', 'VIPTier')

    # Create VIPSettings singleton if it doesn't exist
    if not VIPSettings.objects.exists():
        VIPSettings.objects.create(
            pk=1,
            is_program_enabled=True,
            program_name="VIP Program",
            earning_automatic_enabled=True,
            earning_points_enabled=False,
            earning_manual_enabled=True,
            automatic_earning_type='SPENDING',
            expiration_type='NEVER',
            show_vip_status_to_client=True,
            show_tier_progress_to_client=True,
            show_available_rewards_to_client=True,
            show_points_balance_to_client=True,
        )

    # Create default Standard tier if no tiers exist
    if not VIPTier.objects.exists():
        VIPTier.objects.create(
            name="Standard",
            slug="standard",
            description="Default tier for all clients",
            level=0,
            is_default=True,
            color="#6B7280",
            is_active=True,
        )


def reverse_seed(apps, schema_editor):
    """Reverse the seed - remove seeded data."""
    VIPSettings = apps.get_model('vip', 'VIPSettings')
    VIPTier = apps.get_model('vip', 'VIPTier')

    # Only delete if these were our seeded entries
    VIPTier.objects.filter(slug="standard", is_default=True, level=0).delete()
    VIPSettings.objects.filter(pk=1).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('vip', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(seed_default_data, reverse_seed),
    ]
