# Generated by Django 5.2.1 on 2025-12-23 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vip', '0003_add_status_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='clientvipstatus',
            name='vip_status_expires_idx',
        ),
    ]
