# Generated by Django 5.2.1 on 2025-06-21 20:01

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('communications', '0001_initial'),
        ('events', '0002_eventfeedback_eventfile_eventproductoption_eventtask_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('event_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='events.eventtype')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WorkflowStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('name', models.CharField(max_length=255)),
                ('stage', models.CharField(choices=[('LEAD', 'Lead'), ('PRODUCTION', 'Production'), ('POST_PRODUCTION', 'Post Production')], max_length=20)),
                ('order', models.PositiveIntegerField()),
                ('is_automated', models.BooleanField(default=False)),
                ('automation_type', models.CharField(blank=True, choices=[('EMAIL', 'Send Email'), ('TASK', 'Create Task'), ('QUOTE', 'Generate Quote'), ('CONTRACT', 'Generate Contract'), ('REMINDER', 'Send Reminder'), ('NOTIFICATION', 'Send Notification')], max_length=50)),
                ('trigger_time', models.CharField(blank=True, help_text='When to trigger automation (ON_CREATION, AFTER_1_DAY, AFTER_3_DAYS, etc.)', max_length=255)),
                ('task_description', models.TextField(blank=True)),
                ('progression_condition', models.CharField(blank=True, help_text='Condition required to progress (QUOTE_ACCEPTED, PAYMENT_RECEIVED, etc.)', max_length=255)),
                ('required_tasks_completed', models.BooleanField(default=False, help_text='Require all associated tasks to be completed before progressing')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('email_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='communications.communicationtemplate')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='workflows.workflowtemplate')),
            ],
            options={
                'ordering': ['order'],
                'constraints': [models.UniqueConstraint(fields=('template', 'stage', 'order'), name='unique_stage_order_per_template_and_stage')],
            },
        ),
    ]
