# Generated by Django 5.2.1 on 2025-09-05 07:10

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_remove_event_event_workflow_idx_and_more'),
        ('workflows', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowTrigger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('trigger_type', models.CharField(choices=[('PAYMENT_RECEIVED', 'Payment Received'), ('QUOTE_ACCEPTED', 'Quote Accepted'), ('CONTRACT_SIGNED', 'Contract Signed'), ('EVENT_CREATED', 'Event Created'), ('EVENT_COMPLETED', 'Event Completed'), ('TASK_COMPLETED', 'Task Completed'), ('DATE_TRIGGER', 'Date/Time Trigger'), ('MANUAL_TRIGGER', 'Manual Trigger')], max_length=50)),
                ('details', models.TextField(blank=True, help_text='Description of what triggered this event')),
                ('result_data', models.JSONField(blank=True, default=dict, help_text='Data associated with the trigger')),
                ('processed', models.BooleanField(default=False, help_text='Whether this trigger has been processed')),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_triggers', to='events.event')),
                ('stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='workflows.workflowstage')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
