# Generated by Django 5.2.1 on 2025-09-05 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0002_workflowtrigger'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowstage',
            name='trigger_on_contract_signed',
            field=models.BooleanField(default=False, help_text='Trigger this stage when contract is signed'),
        ),
        migrations.AddField(
            model_name='workflowstage',
            name='trigger_on_event_created',
            field=models.BooleanField(default=False, help_text='Trigger this stage when event is created'),
        ),
        migrations.AddField(
            model_name='workflowstage',
            name='trigger_on_payment_received',
            field=models.BooleanField(default=False, help_text='Trigger this stage when payment is received'),
        ),
        migrations.AddField(
            model_name='workflowstage',
            name='trigger_on_quote_accepted',
            field=models.BooleanField(default=False, help_text='Trigger this stage when quote is accepted'),
        ),
    ]
