# Generated by Django 5.2.1 on 2025-09-21 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0003_workflowstage_trigger_on_contract_signed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflowstage',
            name='automation_type',
            field=models.CharField(blank=True, choices=[('EMAIL', 'Send Email'), ('TASK', 'Create Task'), ('QUOTE', 'Generate Quote'), ('CONTRACT', 'Generate Contract'), ('PAYMENT_PLAN', 'Create Payment Plan'), ('REMINDER', 'Send Reminder'), ('NOTIFICATION', 'Send Notification')], max_length=50),
        ),
        migrations.AlterField(
            model_name='workflowtrigger',
            name='trigger_type',
            field=models.CharField(choices=[('PAYMENT_RECEIVED', 'Payment Received'), ('PAYMENT_PLAN_CREATED', 'Payment Plan Created'), ('PAYMENT_OVERDUE', 'Payment Overdue'), ('QUOTE_ACCEPTED', 'Quote Accepted'), ('CONTRACT_SIGNED', 'Contract Signed'), ('EVENT_CREATED', 'Event Created'), ('EVENT_COMPLETED', 'Event Completed'), ('TASK_COMPLETED', 'Task Completed'), ('DATE_TRIGGER', 'Date/Time Trigger'), ('MANUAL_TRIGGER', 'Manual Trigger')], max_length=50),
        ),
    ]
