# Generated by Django 5.2.1 on 2025-10-04 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0004_alter_workflowstage_automation_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowstage',
            name='trigger_on_quote_sent',
            field=models.BooleanField(
                default=False,
                help_text='Trigger this stage when quote is sent to client'
            ),
        ),
    ]
