# Generated by Django 5.2.1 on 2025-12-16 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0006_alter_workflowstage_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflowstage',
            name='automation_type',
            field=models.CharField(blank=True, choices=[('EMAIL', 'Send Email'), ('TASK', 'Create Task'), ('QUOTE', 'Generate Quote'), ('CONTRACT', 'Generate Contract'), ('REMINDER', 'Send Reminder'), ('NOTIFICATION', 'Send Notification')], max_length=50),
        ),
    ]
