# Generated by Django 5.2.1 on 2026-01-12 10:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0004_remove_legacy_signing_fields'),
        ('workflows', '0007_alter_workflowstage_automation_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowstage',
            name='contract_template',
            field=models.ForeignKey(blank=True, help_text='Contract template to use for CONTRACT automation', null=True, on_delete=django.db.models.deletion.SET_NULL, to='contracts.contracttemplate'),
        ),
        migrations.AlterField(
            model_name='workflowstage',
            name='trigger_time',
            field=models.CharField(blank=True, help_text='When to trigger automation. Supported formats: ON_CREATION (immediate), AFTER_X_DAYS/AFTER_X_HOURS/AFTER_X_WEEKS (delay after stage start), X_DAYS_BEFORE_EVENT (e.g., 30_DAYS_BEFORE_EVENT, 7_DAYS_BEFORE_EVENT)', max_length=255),
        ),
    ]
