# Generated by Django 5.2.1 on 2026-01-19 10:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0009_emailunsubscribetoken'),
        ('events', '0017_add_date_reservation'),
        ('workflows', '0008_add_contract_template_fk'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowtemplate',
            name='lead_stage_auto_stop',
            field=models.BooleanField(default=True, help_text='Stop remaining LEAD automations when event enters PRODUCTION stage'),
        ),
        migrations.CreateModel(
            name='EventWorkflowOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('override_type', models.CharField(choices=[('SKIP', 'Skip Stage'), ('DISABLE_AUTOMATION', 'Disable Automation'), ('CUSTOM_TIMING', 'Custom Timing'), ('ADD_STAGE', 'Add Custom Stage')], help_text='Type of override to apply', max_length=20)),
                ('custom_trigger_time', models.CharField(blank=True, help_text='Custom trigger time for this event (overrides stage.trigger_time)', max_length=255)),
                ('custom_stage_name', models.CharField(blank=True, help_text='Name for custom added stage', max_length=255)),
                ('custom_stage_category', models.CharField(blank=True, choices=[('LEAD', 'Lead'), ('PRODUCTION', 'Production'), ('POST_PRODUCTION', 'Post Production')], help_text='Stage category for custom added stage', max_length=20)),
                ('custom_order', models.PositiveIntegerField(blank=True, help_text='Order position for custom stage', null=True)),
                ('custom_is_automated', models.BooleanField(default=False, help_text='Whether custom stage has automation')),
                ('custom_automation_type', models.CharField(blank=True, help_text='Automation type for custom stage', max_length=50)),
                ('custom_task_description', models.TextField(blank=True, help_text='Task description for custom stage')),
                ('reason', models.TextField(blank=True, help_text='Reason for this override (for audit trail)')),
                ('executed', models.BooleanField(default=False, help_text='Whether this override has been applied/executed')),
                ('executed_at', models.DateTimeField(blank=True, help_text='When this override was applied', null=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this override', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflow_overrides_created', to=settings.AUTH_USER_MODEL)),
                ('custom_email_template', models.ForeignKey(blank=True, help_text='Email template for custom stage', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_override_emails', to='communications.communicationtemplate')),
                ('event', models.ForeignKey(help_text='The event this override applies to', on_delete=django.db.models.deletion.CASCADE, related_name='workflow_overrides', to='events.event')),
                ('stage', models.ForeignKey(blank=True, help_text='The template stage being overridden (null for ADD_STAGE)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_overrides', to='workflows.workflowstage')),
            ],
            options={
                'ordering': ['event', 'custom_order'],
                'indexes': [models.Index(fields=['event', 'override_type'], name='workflows_e_event_i_b96420_idx'), models.Index(fields=['stage', 'override_type'], name='workflows_e_stage_i_940be2_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('stage__isnull', False)), fields=('event', 'stage'), name='unique_event_stage_override')],
            },
        ),
    ]
