# Generated by Django 5.2.1 on 2026-01-19 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaires', '0006_add_field_enhancements'),
        ('workflows', '0009_add_lead_auto_stop_and_event_overrides'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowstage',
            name='questionnaire_template',
            field=models.ForeignKey(blank=True, help_text='Questionnaire template to send for QUESTIONNAIRE automation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflow_stages', to='questionnaires.questionnaire'),
        ),
        migrations.AlterField(
            model_name='workflowstage',
            name='automation_type',
            field=models.CharField(blank=True, choices=[('EMAIL', 'Send Email'), ('TASK', 'Create Task'), ('QUOTE', 'Generate Quote'), ('CONTRACT', 'Generate Contract'), ('QUESTIONNAIRE', 'Send Questionnaire'), ('REMINDER', 'Send Reminder'), ('NOTIFICATION', 'Send Notification')], max_length=50),
        ),
    ]
