# Generated by Django 5.2.1 on 2026-01-19 11:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0010_add_questionnaire_template_to_stage'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowWebhook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Friendly name for this webhook', max_length=255)),
                ('url', models.URLField(help_text='URL to send webhook payloads to', max_length=2048)),
                ('secret', models.CharField(help_text='Secret key for HMAC signature verification', max_length=255)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this webhook is active')),
                ('events', models.JSONField(default=list, help_text='List of event types to trigger this webhook')),
                ('headers', models.JSONField(blank=True, default=dict, help_text='Additional headers to include in webhook requests')),
                ('last_triggered_at', models.DateTimeField(blank=True, help_text='When this webhook was last triggered', null=True)),
                ('failure_count', models.PositiveIntegerField(default=0, help_text='Number of consecutive failures (reset on success)')),
                ('workflow_template', models.ForeignKey(blank=True, help_text='Optional: Limit to specific workflow template', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='webhooks', to='workflows.workflowtemplate')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowWebhookDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.CharField(help_text='The type of event that triggered this delivery', max_length=50)),
                ('payload', models.JSONField(help_text='The JSON payload sent to the webhook')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('RETRYING', 'Retrying')], default='PENDING', help_text='Current status of the delivery', max_length=20)),
                ('response_status_code', models.PositiveIntegerField(blank=True, help_text='HTTP status code from the response', null=True)),
                ('response_body', models.TextField(blank=True, help_text='Response body from the webhook endpoint')),
                ('error_message', models.TextField(blank=True, help_text='Error message if delivery failed')),
                ('attempt_count', models.PositiveIntegerField(default=0, help_text='Number of delivery attempts')),
                ('next_retry_at', models.DateTimeField(blank=True, help_text='When to next retry delivery (if failed)', null=True)),
                ('webhook', models.ForeignKey(help_text='The webhook this delivery is for', on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='workflows.workflowwebhook')),
            ],
            options={
                'verbose_name_plural': 'Workflow webhook deliveries',
                'ordering': ['-created_at'],
            },
        ),
    ]
