# Generated by Django 5.2.1 on 2026-01-21 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0011_add_webhook_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowstage',
            name='trigger_after_stage',
            field=models.ForeignKey(blank=True, help_text="Optional: Stage to wait for before applying trigger_time delay. When set, trigger_time is interpreted as delay AFTER this stage completes. E.g., trigger_after_stage='Job Accepted' + trigger_time='AFTER_5_DAYS' = 5 days after Job Accepted stage is reached.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dependent_stages', to='workflows.workflowstage'),
        ),
        migrations.AlterField(
            model_name='workflowstage',
            name='trigger_time',
            field=models.CharField(blank=True, help_text='When to trigger automation. Supported formats: ON_CREATION (immediate), AFTER_X_DAYS/AFTER_X_HOURS/AFTER_X_WEEKS (delay after stage start or after trigger_after_stage if set), X_DAYS_BEFORE_EVENT (e.g., 30_DAYS_BEFORE_EVENT, 7_DAYS_BEFORE_EVENT)', max_length=255),
        ),
        migrations.AlterField(
            model_name='workflowtrigger',
            name='trigger_type',
            field=models.CharField(choices=[('PAYMENT_RECEIVED', 'Payment Received'), ('PAYMENT_PLAN_CREATED', 'Payment Plan Created'), ('PAYMENT_OVERDUE', 'Payment Overdue'), ('QUOTE_SENT', 'Quote Sent'), ('QUOTE_ACCEPTED', 'Quote Accepted'), ('QUOTE_REJECTED', 'Quote Rejected'), ('QUOTE_EXPIRED', 'Quote Expired'), ('CONTRACT_SENT', 'Contract Sent'), ('CONTRACT_SIGNED', 'Contract Signed'), ('CONTRACT_EXPIRED', 'Contract Expired'), ('INVOICE_SENT', 'Invoice Sent'), ('INVOICE_OVERDUE', 'Invoice Overdue'), ('EVENT_CREATED', 'Event Created'), ('EVENT_COMPLETED', 'Event Completed'), ('TASK_COMPLETED', 'Task Completed'), ('DATE_TRIGGER', 'Date/Time Trigger'), ('MANUAL_TRIGGER', 'Manual Trigger')], max_length=50),
        ),
    ]
