# Generated by Django 5.2.1 on 2025-12-21 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_alter_note_created_at_alter_note_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='is_client_visible',
            field=models.BooleanField(default=False, help_text='If True, note is visible to clients'),
        ),
    ]
