# Generated by Django 5.2.1 on 2025-09-29 17:43

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotelineitem',
            name='base_unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Base price before excess hours (unit_price = base_unit_price + excess per unit)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='quotelineitem',
            name='excess_cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total excess cost (excess_hours * excess_hour_price)', max_digits=10),
        ),
        migrations.AddField(
            model_name='quotelineitem',
            name='excess_hour_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Price per excess hour', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='quotelineitem',
            name='excess_hours',
            field=models.PositiveIntegerField(blank=True, help_text='Number of excess hours for this item', null=True),
        ),
        migrations.AddField(
            model_name='quotelineitem',
            name='item_type',
            field=models.CharField(choices=[('PACKAGE', 'Package'), ('ADDON', 'Add-on')], default='PACKAGE', help_text='Type of item to distinguish packages from addons', max_length=20),
        ),
    ]
