# Generated by Django 5.2.1 on 2025-10-03 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_enhance_quotelineitem_pricing_fields'),
    ]

    operations = [
        # Drop the QuoteCustomizationRequest table directly using SQL
        migrations.RunSQL(
            sql='DROP TABLE IF EXISTS sales_quotecustomizationrequest CASCADE;',
            reverse_sql=migrations.RunSQL.noop,
        ),

        # Remove fields from EventQuote using SQL
        migrations.RunSQL(
            sql='ALTER TABLE sales_eventquote DROP COLUMN IF EXISTS parent_quote_id CASCADE;',
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            sql='ALTER TABLE sales_eventquote DROP COLUMN IF EXISTS negotiation_status CASCADE;',
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            sql='ALTER TABLE sales_eventquote DROP COLUMN IF EXISTS counter_offer_count CASCADE;',
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
