# Generated by Django 5.2.1 on 2025-12-18 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_alter_eventquote_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventquote',
            name='service_charge_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
