# Generated by Django 5.2.1 on 2025-12-19 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_eventquote_service_charge_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotelineitem',
            name='venue_hours_breakdown',
            field=models.JSONField(blank=True, help_text='Per-venue hours breakdown: [{venue_id, venue_name, included_hours, additional_hours, excess_hour_price, venue_cost}]', null=True),
        ),
    ]
