# Generated by Django 5.2.1 on 2026-02-12 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_add_venue_hours_breakdown_to_quotelineitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotelineitem',
            name='metadata',
            field=models.JSONField(blank=True, help_text='Additional metadata: attendee_breakdown for per-person packages, etc.', null=True),
        ),
    ]
