# Generated by Django 5.2.1 on 2026-02-20 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0007_add_metadata_to_quotelineitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventquote',
            name='applied_vip_benefits',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='eventquote',
            name='vip_discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
