# Generated by Django 5.2.1 on 2025-06-15 02:02

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('requires_venue', models.BooleanField(default=False, help_text='Category requires venue specification')),
                ('typical_duration_hours', models.PositiveIntegerField(blank=True, help_text='Typical event duration in hours', null=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='products.productcategory')),
            ],
            options={
                'verbose_name_plural': 'Product Categories',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ProductOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('pricing_model', models.CharField(choices=[('FIXED', 'Fixed Price'), ('HOURLY', 'Hourly Rate'), ('TIERED', 'Tiered Pricing'), ('CUSTOM', 'Custom Quote')], default='FIXED', max_length=10)),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('currency', models.CharField(default='PHP', max_length=3)),
                ('tax_rate', models.DecimalField(decimal_places=2, default=12.0, max_digits=5)),
                ('type', models.CharField(choices=[('PRODUCT', 'Product'), ('PACKAGE', 'Package')], max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('allow_multiple', models.BooleanField(default=False, help_text='Allow multiple quantities per booking')),
                ('requires_approval', models.BooleanField(default=False, help_text='Requires admin approval before booking')),
                ('has_excess_hours', models.BooleanField(default=False)),
                ('included_hours', models.PositiveIntegerField(blank=True, null=True)),
                ('excess_hour_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('minimum_hours', models.PositiveIntegerField(blank=True, help_text='Minimum booking duration', null=True)),
                ('maximum_hours', models.PositiveIntegerField(blank=True, help_text='Maximum booking duration', null=True)),
                ('advance_booking_days', models.PositiveIntegerField(default=7, help_text='Minimum days in advance for booking')),
                ('maximum_booking_days', models.PositiveIntegerField(blank=True, help_text='Maximum days in advance for booking', null=True)),
                ('sku', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='products.productcategory')),
                ('event_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='events.eventtype')),
            ],
            options={
                'ordering': ['category__sort_order', 'sort_order', 'name'],
                'unique_together': {('name', 'category')},
            },
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('description', models.CharField(max_length=255)),
                ('discount_type', models.CharField(choices=[('PERCENTAGE', 'Percentage'), ('FIXED', 'Fixed Amount'), ('FREE_HOURS', 'Free Hours')], max_length=20)),
                ('application_type', models.CharField(choices=[('AUTOMATIC', 'Automatic'), ('CODE_REQUIRED', 'Code Required'), ('ADMIN_ONLY', 'Admin Only')], default='CODE_REQUIRED', max_length=15)),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('valid_from', models.DateField()),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('max_uses', models.PositiveIntegerField(blank=True, null=True)),
                ('max_uses_per_client', models.PositiveIntegerField(blank=True, null=True)),
                ('current_uses', models.PositiveIntegerField(default=0)),
                ('minimum_order_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('minimum_hours', models.PositiveIntegerField(blank=True, null=True)),
                ('applicable_categories', models.ManyToManyField(blank=True, to='products.productcategory')),
                ('applicable_products', models.ManyToManyField(blank=True, to='products.productoption')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
