# Generated by Django 5.2.1 on 2025-06-15 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='currency',
            field=models.CharField(default='PHP', max_length=3),
        ),
    ]
