# Generated by Django 5.2.1 on 2025-10-09 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_discount_created_at_alter_discount_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productoption',
            name='maximum_guests',
            field=models.PositiveIntegerField(blank=True, help_text='Maximum guest capacity', null=True),
        ),
        migrations.AddField(
            model_name='productoption',
            name='minimum_guests',
            field=models.PositiveIntegerField(blank=True, help_text='Minimum guest capacity', null=True),
        ),
        migrations.AddField(
            model_name='productoption',
            name='recommended_guests',
            field=models.PositiveIntegerField(blank=True, help_text='Recommended guest count', null=True),
        ),
    ]
