# Generated by Django 5.2.1 on 2025-12-18 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_productoption_maximum_guests_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productoption',
            name='is_tax_inclusive',
            field=models.BooleanField(default=False, help_text='If True, base_price already includes tax (no additional tax applied)'),
        ),
    ]
