# Generated by Django 5.2.1 on 2025-12-18 23:50

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_add_is_tax_inclusive_to_productoption'),
    ]

    operations = [
        migrations.AddField(
            model_name='productoption',
            name='booking_session_id',
            field=models.CharField(blank=True, help_text='Booking session that created this custom package (for cleanup)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='productoption',
            name='bundle_discount_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Discount applied for multi-venue custom packages', max_digits=5),
        ),
        migrations.AddField(
            model_name='productoption',
            name='is_custom',
            field=models.BooleanField(default=False, help_text='True if this package was generated from venue selection'),
        ),
    ]
