# Generated by Django 5.2.1 on 2025-12-19 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_venue_custom_package_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productoption',
            name='excess_hour_price',
        ),
        migrations.RemoveField(
            model_name='productoption',
            name='has_excess_hours',
        ),
        migrations.RemoveField(
            model_name='productoption',
            name='included_hours',
        ),
    ]
