# Generated by Django 5.2.1 on 2025-12-19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_remove_deprecatedhour_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='productoption',
            name='event_days',
            field=models.PositiveIntegerField(
                blank=True,
                null=True,
                help_text='Exact number of days for this package (e.g., 2 for 2D1N, 3 for 3D2N). Null means no restriction.'
            ),
        ),
    ]
