# Generated by Django 5.2.1 on 2025-12-23 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_add_discount_category_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='discount',
            name='discount_active_valid_idx',
        ),
        migrations.RemoveIndex(
            model_name='productcategory',
            name='category_parent_active_idx',
        ),
    ]
