# Generated by Django 5.2.1 on 2026-01-06 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_remove_discount_discount_active_valid_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productoption',
            name='featured_image',
            field=models.ImageField(blank=True, help_text='Main image shown in listings and cards', null=True, upload_to='products/images/'),
        ),
        migrations.AddField(
            model_name='productoption',
            name='gallery_images',
            field=models.JSONField(blank=True, default=list, help_text='List of image URLs for product gallery'),
        ),
    ]
