# Generated by Django 5.2.1 on 2026-01-08 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0015_add_guest_count_fields'),
        ('products', '0011_add_image_fields_to_productoption'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productoption',
            name='event_type',
        ),
        migrations.AddField(
            model_name='productoption',
            name='event_types',
            field=models.ManyToManyField(blank=True, help_text='Event types this package is available for. Empty = hidden when filtering by event type.', related_name='packages', to='events.eventtype'),
        ),
    ]
