# Generated by Django 5.2.1 on 2026-01-10 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_convert_event_type_to_manytomany'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productoption',
            name='tax_rate',
        ),
    ]
