# Generated by Django 5.2.1 on 2026-01-26 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_remove_tax_rate_from_productoption'),
    ]

    operations = [
        migrations.AddField(
            model_name='productoption',
            name='pricing_unit',
            field=models.CharField(choices=[('PER_EVENT', 'Per Event'), ('PER_PERSON', 'Per Person'), ('PER_HOUR', 'Per Hour')], default='PER_EVENT', help_text='What unit the price applies to (per event, per person, per hour)', max_length=15),
        ),
    ]
