# Generated by Django 5.2.1 on 2026-01-26 05:27

from django.db import migrations


def set_pricing_unit_from_pricing_model(apps, schema_editor):
    """
    Set pricing_unit based on pricing_model and allow_multiple for existing products:
    - HOURLY -> PER_HOUR
    - allow_multiple=True (camp/retreat packages) -> PER_PERSON
    - All others (FIXED, TIERED, CUSTOM) -> PER_EVENT (default)
    """
    ProductOption = apps.get_model('products', 'ProductOption')

    # Update HOURLY products to PER_HOUR
    ProductOption.objects.filter(pricing_model='HOURLY').update(pricing_unit='PER_HOUR')

    # Update PACKAGES with allow_multiple=True to PER_PERSON
    # These are camp/retreat packages where price is per person
    # Note: PRODUCTs (add-ons) with allow_multiple stay PER_EVENT by default
    ProductOption.objects.filter(type='PACKAGE', allow_multiple=True).update(pricing_unit='PER_PERSON')

    # FIXED, TIERED, CUSTOM products without allow_multiple keep the default PER_EVENT
    # (already set by the default value in the previous migration)


def reverse_pricing_unit(apps, schema_editor):
    """Reverse migration - reset all to PER_EVENT"""
    ProductOption = apps.get_model('products', 'ProductOption')
    ProductOption.objects.all().update(pricing_unit='PER_EVENT')


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_add_pricing_unit_field'),
    ]

    operations = [
        migrations.RunPython(
            set_pricing_unit_from_pricing_model,
            reverse_pricing_unit
        ),
    ]
