# Generated by Django 5.2.1 on 2026-02-11 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_set_pricing_unit_from_pricing_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='productoption',
            name='maximum_quantity',
            field=models.PositiveIntegerField(blank=True, help_text='Maximum quantity per booking when allow_multiple is enabled (null = unlimited)', null=True),
        ),
    ]
