# Generated by Django 5.2.1 on 2026-02-16 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_add_maximum_quantity_to_productoption'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='badge_text',
            field=models.CharField(blank=True, default='', help_text="Custom badge label shown on rates page (e.g., 'Staff Pick'). Empty = no badge.", max_length=50),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='includes',
            field=models.JSONField(blank=True, default=list, help_text="List of included features shown on rates page (e.g., ['Swimming pool access', 'Upgraded sound system'])"),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='notes',
            field=models.JSONField(blank=True, default=list, help_text="List of disclaimer notes shown on rates page (e.g., ['Kitchen use: P5,000/day'])"),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='rates_page_section',
            field=models.CharField(blank=True, default='', help_text="Which rates page section this category appears in: 'event_packages', 'wedding_combos', 'all_in_weddings', or empty for hidden", max_length=30),
        ),
        migrations.AddField(
            model_name='productoption',
            name='is_highlighted',
            field=models.BooleanField(default=False, help_text="Highlight this tier on the rates page (e.g., 'Popular' badge)"),
        ),
        migrations.AddField(
            model_name='productoption',
            name='tier_label',
            field=models.CharField(blank=True, default='', help_text="Display label for this pricing tier on rates page (e.g., 'Day Trip', '2D1N', 'Under 100 pax')", max_length=50),
        ),
    ]
