# Generated by Django 5.2.1 on 2025-12-18 17:39

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0005_add_is_tax_inclusive_to_productoption'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Vendor name', max_length=200)),
                ('code', models.CharField(help_text="Unique code (e.g., 'VENDOR_CATERING_ABC')", max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('service_category', models.CharField(choices=[('CATERING', 'Catering'), ('PHOTOGRAPHY', 'Photography'), ('VIDEOGRAPHY', 'Videography'), ('DJ', 'DJ / Music'), ('FLORIST', 'Florist'), ('DECORATOR', 'Decorator'), ('ENTERTAINMENT', 'Entertainment'), ('TRANSPORTATION', 'Transportation'), ('MAKEUP', 'Makeup & Styling'), ('RENTALS', 'Equipment Rentals'), ('OFFICIANT', 'Officiant'), ('COORDINATION', 'Event Coordination'), ('OTHER', 'Other')], default='OTHER', help_text='Primary service category', max_length=20)),
                ('service_description', models.TextField(blank=True, help_text='Detailed description of services offered')),
                ('contact_name', models.CharField(blank=True, max_length=200)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=50)),
                ('company_name', models.CharField(blank=True, max_length=200)),
                ('address', models.TextField(blank=True)),
                ('website', models.URLField(blank=True)),
                ('pricing_notes', models.TextField(blank=True, help_text='Notes about pricing, rates, or packages offered')),
                ('is_active', models.BooleanField(default=True)),
                ('is_bookable', models.BooleanField(default=True, help_text='Whether this vendor can be included in client bookings')),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='vendors/images/')),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Vendor',
                'verbose_name_plural': 'Vendors',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='VendorOperatingRules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('minimum_lead_days', models.PositiveIntegerField(default=0, help_text='Minimum days advance notice required')),
                ('minimum_service_hours', models.DecimalField(blank=True, decimal_places=1, help_text='Minimum service duration in hours', max_digits=4, null=True)),
                ('maximum_service_hours', models.DecimalField(blank=True, decimal_places=1, help_text='Maximum service duration in hours', max_digits=4, null=True)),
                ('setup_hours', models.DecimalField(decimal_places=1, default=Decimal('0.0'), help_text='Required setup time before service', max_digits=4)),
                ('teardown_hours', models.DecimalField(decimal_places=1, default=Decimal('0.0'), help_text='Required teardown time after service', max_digits=4)),
                ('custom_rules', models.JSONField(blank=True, default=dict, help_text='Additional custom rules as JSON')),
                ('vendor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_operating_rules', to='vendors.vendor')),
            ],
            options={
                'verbose_name': 'Vendor Operating Rules',
                'verbose_name_plural': 'Vendor Operating Rules',
            },
        ),
        migrations.CreateModel(
            name='PackageVendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True, help_text="Notes about vendor's services for this package")),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Display order within the package')),
                ('package', models.ForeignKey(limit_choices_to={'type': 'PACKAGE'}, on_delete=django.db.models.deletion.CASCADE, related_name='package_vendors', to='products.productoption')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_packages', to='vendors.vendor')),
            ],
            options={
                'verbose_name': 'Package Vendor',
                'verbose_name_plural': 'Package Vendors',
                'ordering': ['sort_order', 'vendor__name'],
                'unique_together': {('package', 'vendor')},
            },
        ),
    ]
