# Generated by Django 5.2.1 on 2025-06-27 20:56

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversionFunnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('steps', models.JSONField(default=list, help_text='List of funnel steps with event names and criteria')),
                ('time_window_hours', models.PositiveIntegerField(default=24, help_text='Time window for step completion in hours')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('dashboard_type', models.CharField(choices=[('EXECUTIVE', 'Executive Dashboard'), ('OPERATIONAL', 'Operational Dashboard'), ('CLIENT', 'Client Dashboard'), ('FINANCIAL', 'Financial Dashboard'), ('MARKETING', 'Marketing Dashboard'), ('CUSTOM', 'Custom Dashboard')], max_length=20)),
                ('is_public', models.BooleanField(default=False)),
                ('allowed_roles', models.JSONField(default=list, help_text='List of user roles that can access this dashboard')),
                ('layout_config', models.JSONField(default=dict, help_text='Dashboard layout and positioning configuration')),
                ('auto_refresh_interval', models.PositiveIntegerField(default=300, help_text='Auto refresh interval in seconds')),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_dashboards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FunnelConversion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('session_id', models.CharField(blank=True, max_length=255)),
                ('started_at', models.DateTimeField()),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('current_step', models.PositiveIntegerField(default=0)),
                ('completed_steps', models.JSONField(default=list, help_text='List of completed step indices with timestamps')),
                ('conversion_data', models.JSONField(default=dict, help_text='Data collected during the funnel journey')),
                ('funnel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversions', to='analytics.conversionfunnel')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='MetricDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('metric_type', models.CharField(choices=[('COUNT', 'Count'), ('SUM', 'Sum'), ('AVERAGE', 'Average'), ('PERCENTAGE', 'Percentage'), ('RATIO', 'Ratio'), ('CONVERSION_RATE', 'Conversion Rate'), ('REVENUE', 'Revenue'), ('CUSTOM', 'Custom Calculation')], max_length=20)),
                ('source_domain', models.CharField(help_text='Domain to query (events, payments, bookingflow, etc.)', max_length=50)),
                ('source_model', models.CharField(help_text='Model name within the domain', max_length=100)),
                ('source_field', models.CharField(blank=True, help_text='Field to aggregate', max_length=100)),
                ('calculation_rules', models.JSONField(default=dict, help_text='JSON configuration for metric calculation')),
                ('filters', models.JSONField(default=dict, help_text='Django Q object filters as JSON')),
                ('aggregation_period', models.CharField(choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly'), ('QUARTERLY', 'Quarterly'), ('YEARLY', 'Yearly'), ('REAL_TIME', 'Real Time')], max_length=20)),
                ('is_real_time', models.BooleanField(default=False)),
                ('display_format', models.CharField(default='number', help_text='Format for display: number, currency, percentage, etc.', max_length=50)),
                ('decimal_places', models.PositiveIntegerField(default=2)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['source_domain', 'source_model'], name='analytics_m_source__4cf95f_idx'), models.Index(fields=['is_active', 'is_real_time'], name='analytics_m_is_acti_a6409d_idx')],
            },
        ),
        migrations.CreateModel(
            name='EventAggregation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('aggregation_type', models.CharField(choices=[('HOURLY', 'Hourly'), ('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly')], max_length=20)),
                ('period_start', models.DateTimeField()),
                ('period_end', models.DateTimeField()),
                ('total_count', models.PositiveIntegerField(default=0)),
                ('total_sum', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('average_value', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('min_value', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('max_value', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('aggregated_data', models.JSONField(default=dict, help_text='Additional aggregated metrics and breakdowns')),
                ('is_complete', models.BooleanField(default=False)),
                ('processed_at', models.DateTimeField(auto_now=True)),
                ('metric_definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aggregations', to='analytics.metricdefinition')),
            ],
            options={
                'ordering': ['-period_start'],
            },
        ),
        migrations.CreateModel(
            name='AnalyticsReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('report_type', models.CharField(choices=[('BUSINESS_SUMMARY', 'Business Summary'), ('FINANCIAL', 'Financial Report'), ('BOOKING_PERFORMANCE', 'Booking Performance'), ('CLIENT_ANALYSIS', 'Client Analysis'), ('WORKFLOW_EFFICIENCY', 'Workflow Efficiency'), ('PAYMENT_ANALYSIS', 'Payment Analysis'), ('CUSTOM', 'Custom Report')], max_length=30)),
                ('template_config', models.JSONField(default=dict, help_text='Report template and layout configuration')),
                ('filters', models.JSONField(default=dict, help_text='Default filters for the report')),
                ('schedule_frequency', models.CharField(choices=[('MANUAL', 'Manual Only'), ('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly'), ('QUARTERLY', 'Quarterly')], default='MANUAL', max_length=20)),
                ('schedule_time', models.TimeField(blank=True, help_text='Time to run scheduled reports', null=True)),
                ('schedule_day_of_week', models.PositiveIntegerField(blank=True, help_text='Day of week for weekly reports (0=Monday)', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(6)])),
                ('schedule_day_of_month', models.PositiveIntegerField(blank=True, help_text='Day of month for monthly reports', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)])),
                ('output_format', models.CharField(choices=[('PDF', 'PDF'), ('EXCEL', 'Excel'), ('CSV', 'CSV'), ('HTML', 'HTML'), ('JSON', 'JSON')], default='PDF', max_length=10)),
                ('recipients', models.JSONField(default=list, help_text='List of email addresses to send the report to')),
                ('is_active', models.BooleanField(default=True)),
                ('last_generated', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_reports', to=settings.AUTH_USER_MODEL)),
                ('metrics', models.ManyToManyField(related_name='reports', to='analytics.metricdefinition')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AlertRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('operator', models.CharField(choices=[('GT', 'Greater Than'), ('GTE', 'Greater Than or Equal'), ('LT', 'Less Than'), ('LTE', 'Less Than or Equal'), ('EQ', 'Equal'), ('NE', 'Not Equal'), ('CHANGE_GT', 'Change Greater Than'), ('CHANGE_LT', 'Change Less Than')], max_length=20)),
                ('threshold_value', models.DecimalField(decimal_places=2, max_digits=15)),
                ('evaluation_period', models.CharField(default='last_hour', help_text='Time period to evaluate (last_hour, last_day, etc.)', max_length=50)),
                ('evaluation_frequency', models.PositiveIntegerField(default=300, help_text='How often to check the rule in seconds')),
                ('notification_methods', models.JSONField(default=list, help_text='List of notification methods')),
                ('recipients', models.JSONField(default=list, help_text='List of recipients (emails, phone numbers, etc.)')),
                ('is_active', models.BooleanField(default=True)),
                ('last_triggered', models.DateTimeField(blank=True, null=True)),
                ('last_evaluated', models.DateTimeField(blank=True, null=True)),
                ('cooldown_minutes', models.PositiveIntegerField(default=60, help_text='Minimum minutes between alerts for the same rule')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_alert_rules', to=settings.AUTH_USER_MODEL)),
                ('metric_definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_rules', to='analytics.metricdefinition')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ReportExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('execution_id', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('execution_params', models.JSONField(default=dict, help_text='Parameters used for this specific execution')),
                ('date_range_start', models.DateTimeField()),
                ('date_range_end', models.DateTimeField()),
                ('result_data', models.JSONField(default=dict, help_text='Cached report data')),
                ('file_path', models.CharField(blank=True, help_text='Path to generated report file', max_length=500)),
                ('file_size', models.PositiveIntegerField(blank=True, help_text='File size in bytes', null=True)),
                ('execution_time_seconds', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='analytics.analyticsreport')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requested_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Widget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('widget_type', models.CharField(choices=[('METRIC_CARD', 'Metric Card'), ('LINE_CHART', 'Line Chart'), ('BAR_CHART', 'Bar Chart'), ('PIE_CHART', 'Pie Chart'), ('AREA_CHART', 'Area Chart'), ('TABLE', 'Data Table'), ('FUNNEL', 'Conversion Funnel'), ('GAUGE', 'Gauge Chart'), ('HEATMAP', 'Heatmap'), ('PROGRESS_BAR', 'Progress Bar')], max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('size', models.CharField(choices=[('SMALL', 'Small (1x1)'), ('MEDIUM', 'Medium (2x1)'), ('LARGE', 'Large (2x2)'), ('WIDE', 'Wide (3x1)'), ('EXTRA_WIDE', 'Extra Wide (4x1)'), ('TALL', 'Tall (1x2)')], default='MEDIUM', max_length=20)),
                ('position_x', models.PositiveIntegerField(default=0)),
                ('position_y', models.PositiveIntegerField(default=0)),
                ('order', models.PositiveIntegerField(default=0)),
                ('chart_config', models.JSONField(default=dict, help_text='Chart-specific configuration (colors, axes, etc.)')),
                ('time_range', models.CharField(default='last_30_days', help_text='Default time range for the widget', max_length=50)),
                ('data_filters', models.JSONField(default=dict, help_text='Additional filters specific to this widget')),
                ('comparison_enabled', models.BooleanField(default=False)),
                ('comparison_period', models.CharField(blank=True, max_length=50)),
                ('is_visible', models.BooleanField(default=True)),
                ('dashboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='widgets', to='analytics.dashboard')),
                ('metric_definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics.metricdefinition')),
            ],
            options={
                'ordering': ['dashboard', 'order'],
            },
        ),
        migrations.CreateModel(
            name='AnalyticsEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('event_name', models.CharField(max_length=255)),
                ('event_category', models.CharField(choices=[('USER_ACTION', 'User Action'), ('SYSTEM_EVENT', 'System Event'), ('BUSINESS_EVENT', 'Business Event'), ('ERROR_EVENT', 'Error Event'), ('PERFORMANCE', 'Performance')], max_length=20)),
                ('source_domain', models.CharField(max_length=50)),
                ('source_model', models.CharField(blank=True, max_length=100)),
                ('source_id', models.PositiveIntegerField(blank=True, null=True)),
                ('session_id', models.CharField(blank=True, max_length=255)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('event_data', models.JSONField(default=dict, help_text='Event-specific data and metadata')),
                ('numeric_value', models.DecimalField(blank=True, decimal_places=2, help_text='Numeric value for aggregation (revenue, count, etc.)', max_digits=15, null=True)),
                ('event_timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-event_timestamp'],
                'indexes': [models.Index(fields=['event_name', 'event_timestamp'], name='analytics_a_event_n_c6c354_idx'), models.Index(fields=['source_domain', 'source_model'], name='analytics_a_source__0e2e20_idx'), models.Index(fields=['user', 'event_timestamp'], name='analytics_a_user_id_4a5f7d_idx'), models.Index(fields=['event_category', 'event_timestamp'], name='analytics_a_event_c_e74ea5_idx'), models.Index(fields=['event_timestamp'], name='analytics_a_event_t_767ec6_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='dashboard',
            index=models.Index(fields=['dashboard_type', 'is_active'], name='analytics_d_dashboa_e11e0b_idx'),
        ),
        migrations.AddIndex(
            model_name='dashboard',
            index=models.Index(fields=['is_public', 'is_active'], name='analytics_d_is_publ_58aa7e_idx'),
        ),
        migrations.AddIndex(
            model_name='funnelconversion',
            index=models.Index(fields=['funnel', 'is_completed'], name='analytics_f_funnel__e137d9_idx'),
        ),
        migrations.AddIndex(
            model_name='funnelconversion',
            index=models.Index(fields=['started_at'], name='analytics_f_started_e256dd_idx'),
        ),
        migrations.AddIndex(
            model_name='eventaggregation',
            index=models.Index(fields=['metric_definition', 'aggregation_type', 'period_start'], name='analytics_e_metric__023556_idx'),
        ),
        migrations.AddIndex(
            model_name='eventaggregation',
            index=models.Index(fields=['period_start', 'period_end'], name='analytics_e_period__5e052f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='eventaggregation',
            unique_together={('metric_definition', 'aggregation_type', 'period_start')},
        ),
        migrations.AddIndex(
            model_name='analyticsreport',
            index=models.Index(fields=['report_type', 'is_active'], name='analytics_a_report__093bc4_idx'),
        ),
        migrations.AddIndex(
            model_name='analyticsreport',
            index=models.Index(fields=['schedule_frequency', 'is_active'], name='analytics_a_schedul_dc6084_idx'),
        ),
        migrations.AddIndex(
            model_name='alertrule',
            index=models.Index(fields=['metric_definition', 'is_active'], name='analytics_a_metric__6647b3_idx'),
        ),
        migrations.AddIndex(
            model_name='alertrule',
            index=models.Index(fields=['last_evaluated'], name='analytics_a_last_ev_03e14c_idx'),
        ),
        migrations.AddIndex(
            model_name='reportexecution',
            index=models.Index(fields=['report', 'status'], name='analytics_r_report__697413_idx'),
        ),
        migrations.AddIndex(
            model_name='reportexecution',
            index=models.Index(fields=['execution_id'], name='analytics_r_executi_f7aacf_idx'),
        ),
        migrations.AddIndex(
            model_name='reportexecution',
            index=models.Index(fields=['created_at'], name='analytics_r_created_182922_idx'),
        ),
        migrations.AddIndex(
            model_name='widget',
            index=models.Index(fields=['dashboard', 'order'], name='analytics_w_dashboa_2784f1_idx'),
        ),
        migrations.AddIndex(
            model_name='widget',
            index=models.Index(fields=['metric_definition'], name='analytics_w_metric__a9498a_idx'),
        ),
    ]
