# Generated by Django 5.2.1 on 2026-02-07 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analytics', '0003_drop_old_analytics_tables'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyKPISnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(db_index=True, unique=True)),
                ('total_bookings', models.PositiveIntegerField(default=0)),
                ('confirmed_bookings', models.PositiveIntegerField(default=0)),
                ('completed_bookings', models.PositiveIntegerField(default=0)),
                ('cancelled_bookings', models.PositiveIntegerField(default=0)),
                ('event_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('avg_booking_value', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('new_clients', models.PositiveIntegerField(default=0)),
                ('booking_sessions', models.PositiveIntegerField(default=0)),
                ('completed_sessions', models.PositiveIntegerField(default=0)),
                ('conversion_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('cumulative_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('cumulative_bookings', models.PositiveIntegerField(default=0)),
                ('cumulative_clients', models.PositiveIntegerField(default=0)),
                ('revenue_change_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('bookings_change_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('raw_kpi_data', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'Daily KPI Snapshot',
                'verbose_name_plural': 'Daily KPI Snapshots',
                'ordering': ['-date'],
            },
        ),
    ]
