# Generated by Django 5.2.1 on 2025-06-21 20:02

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0003_event_current_stage_event_last_contacted_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('content', models.TextField()),
                ('variables', models.JSONField(default=list)),
                ('requires_signature', models.BooleanField(default=True)),
                ('sections', models.JSONField(default=list, help_text='JSON structure of contract sections')),
                ('signature_requirements', models.JSONField(default=list, help_text="List of required signature roles: ['CLIENT', 'WITNESS', 'COMPANY_REP']")),
                ('requires_witness', models.BooleanField(default=False)),
                ('requires_company_signature', models.BooleanField(default=True)),
                ('allows_amendments', models.BooleanField(default=True)),
                ('amendment_requires_signature', models.BooleanField(default=True)),
                ('event_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='events.eventtype')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EventContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SENT', 'Sent'), ('PARTIALLY_SIGNED', 'Partially Signed'), ('SIGNED', 'Fully Signed'), ('EXPIRED', 'Expired'), ('VOID', 'Void'), ('AMENDED', 'Amended')], max_length=20)),
                ('content', models.TextField()),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('fully_signed_at', models.DateTimeField(blank=True, null=True)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('contract_value', models.DecimalField(blank=True, decimal_places=2, help_text='Total contract value', max_digits=15, null=True)),
                ('payment_schedule_reference', models.TextField(blank=True, help_text='Reference to payment schedule or terms')),
                ('currency', models.CharField(default='PHP', max_length=3)),
                ('signed_at', models.DateTimeField(blank=True, help_text='DEPRECATED: Use ContractSignature model', null=True)),
                ('signature_data', models.TextField(blank=True, help_text='DEPRECATED: Use ContractSignature model', null=True)),
                ('witness_name', models.CharField(blank=True, help_text='DEPRECATED: Use ContractSignature model', max_length=255)),
                ('witness_signature', models.TextField(blank=True, help_text='DEPRECATED: Use ContractSignature model', null=True)),
                ('is_amendment', models.BooleanField(default=False)),
                ('amendment_number', models.PositiveIntegerField(default=0)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='events.event')),
                ('original_contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='amendments', to='contracts.eventcontract')),
                ('signed_by', models.ForeignKey(help_text='DEPRECATED: Use ContractSignature model', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='legacy_signed_contracts', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contracts.contracttemplate')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('event', 'amendment_number')},
            },
        ),
        migrations.CreateModel(
            name='ContractNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('note', models.TextField()),
                ('is_internal', models.BooleanField(default=True, help_text='Internal notes not visible to client')),
                ('category', models.CharField(choices=[('GENERAL', 'General'), ('LEGAL', 'Legal'), ('NEGOTIATION', 'Negotiation'), ('AMENDMENT', 'Amendment'), ('ISSUE', 'Issue'), ('REMINDER', 'Reminder')], default='GENERAL', max_length=30)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='contracts.eventcontract')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContractAmendment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('amendment_reason', models.TextField(help_text='Business reason for the amendment')),
                ('changes_description', models.TextField(help_text='Detailed description of changes')),
                ('section_changes', models.JSONField(default=dict, help_text='Structured data of what sections changed')),
                ('status', models.CharField(choices=[('REQUESTED', 'Requested'), ('DRAFT', 'Draft'), ('SENT_FOR_REVIEW', 'Sent for Review'), ('APPROVED', 'Approved'), ('SIGNED', 'Signed'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], default='REQUESTED', max_length=20)),
                ('original_value', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('new_value', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('value_change', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True)),
                ('requires_new_signatures', models.BooleanField(default=True)),
                ('signature_deadline', models.DateField(blank=True, null=True)),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_amendments', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_amendments', to=settings.AUTH_USER_MODEL)),
                ('amendment_contract', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='amendment_details', to='contracts.eventcontract')),
                ('original_contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amendment_requests', to='contracts.eventcontract')),
            ],
            options={
                'ordering': ['-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='ContractSignature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('role', models.CharField(choices=[('CLIENT', 'Client'), ('WITNESS', 'Witness'), ('COMPANY_REP', 'Company Representative'), ('GUARDIAN', 'Legal Guardian'), ('PARTNER', 'Business Partner'), ('OTHER', 'Other')], max_length=20)),
                ('signature_data', models.TextField(help_text='Base64 encoded signature image or digital signature')),
                ('signed_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('signer_name', models.CharField(help_text='Name as it appears on signature', max_length=255)),
                ('signer_title', models.CharField(blank=True, help_text='Title/position of signer', max_length=100)),
                ('signer_email', models.EmailField(help_text='Email of signer at time of signing', max_length=254)),
                ('is_verified', models.BooleanField(default=False)),
                ('verification_method', models.CharField(blank=True, help_text='Method used to verify signer identity', max_length=50)),
                ('signer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contract_signatures', to=settings.AUTH_USER_MODEL)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signatures', to='contracts.eventcontract')),
            ],
            options={
                'ordering': ['signed_at'],
                'unique_together': {('contract', 'role')},
            },
        ),
        migrations.CreateModel(
            name='ContractDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('document_type', models.CharField(choices=[('ATTACHMENT', 'Attachment'), ('ADDENDUM', 'Addendum'), ('SCHEDULE', 'Schedule'), ('TERMS', 'Terms and Conditions'), ('WAIVER', 'Waiver'), ('OTHER', 'Other')], max_length=50)),
                ('file', models.FileField(upload_to='contracts/documents/')),
                ('version', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='contracts.eventcontract')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('contract', 'name', 'version')},
            },
        ),
    ]
