# Generated by Django 5.2.1 on 2025-09-06 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractsignature',
            name='device_fingerprint',
            field=models.TextField(blank=True, help_text='Device identification for security tracking'),
        ),
        migrations.AddField(
            model_name='contractsignature',
            name='electronic_consent_timestamp',
            field=models.DateTimeField(blank=True, help_text='Timestamp when electronic consent was given', null=True),
        ),
        migrations.AddField(
            model_name='contractsignature',
            name='legal_disclosure_accepted',
            field=models.BooleanField(default=False, help_text='Whether signer accepted electronic signature disclosure'),
        ),
        migrations.AddField(
            model_name='contractsignature',
            name='signature_confidence_score',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Confidence score for signature authenticity (0.0-1.0)', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='contractsignature',
            name='signature_intent_confirmed',
            field=models.BooleanField(default=False, help_text='Whether signer confirmed intent to sign electronically'),
        ),
        migrations.AddField(
            model_name='contractsignature',
            name='signature_metadata',
            field=models.JSONField(default=dict, help_text='Additional metadata about the signing process'),
        ),
    ]
