# Generated by Django 5.2.1 on 2026-01-21 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0004_remove_legacy_signing_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='contracttemplate',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Inactive templates are hidden from selection but preserved for historical records'),
        ),
    ]
