# Generated by Django 5.2.1 on 2025-08-27 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='display_timezone',
            field=models.CharField(default='Asia/Manila', help_text="User's display timezone preference (for admin users)", max_length=50),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='timezone_display_mode',
            field=models.CharField(choices=[('business_only', 'Philippines Time Only'), ('business_with_local', 'Philippines + Local Time'), ('dual_display', 'Both Timezones Side by Side')], default='business_only', help_text='How to display event times to this user', max_length=20),
        ),
    ]
