# Generated by Django 5.2.1 on 2025-10-11 12:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_passwordresettoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='admininvitation',
            name='is_upgrade',
            field=models.BooleanField(default=False, help_text='True if this invitation is to upgrade an existing CLIENT to ADMIN'),
        ),
        migrations.AddField(
            model_name='admininvitation',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Link to existing user if this is a role upgrade invitation', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admin_upgrade_invitation', to=settings.AUTH_USER_MODEL),
        ),
    ]
