# Generated by Django 5.2.1 on 2025-12-23 00:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_admininvitation_is_upgrade_admininvitation_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('consent_type', models.CharField(choices=[('MARKETING_EMAIL', 'Marketing Email'), ('MARKETING_SMS', 'Marketing SMS'), ('MARKETING_PUSH', 'Marketing Push Notifications'), ('ANALYTICS', 'Usage Analytics'), ('THIRD_PARTY_SHARING', 'Third-Party Sharing'), ('SENSITIVE_DATA', 'Sensitive Personal Information Processing'), ('PRIVACY_POLICY', 'Privacy Policy Acceptance'), ('TERMS_OF_SERVICE', 'Terms of Service Acceptance')], max_length=30)),
                ('action', models.CharField(choices=[('GRANT', 'Consent Granted'), ('WITHDRAW', 'Consent Withdrawn'), ('UPDATE', 'Consent Updated')], max_length=10)),
                ('consent_text', models.TextField(blank=True, help_text='The exact text shown to user at time of consent')),
                ('privacy_policy_version', models.CharField(blank=True, help_text='Privacy policy version at time of consent', max_length=20)),
                ('source', models.CharField(choices=[('REGISTRATION', 'Registration'), ('SETTINGS', 'Settings Change'), ('PRIVACY_DASHBOARD', 'Privacy Dashboard'), ('API', 'API Request'), ('ADMIN', 'Admin Action')], default='SETTINGS', max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('device_type', models.CharField(blank=True, max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consent_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Consent Record',
                'verbose_name_plural': 'Consent Records',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'consent_type', '-created_at'], name='users_conse_user_id_32beaf_idx'), models.Index(fields=['user', '-created_at'], name='users_conse_user_id_9b8797_idx')],
            },
        ),
        migrations.CreateModel(
            name='PrivacyRequest',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_email', models.EmailField(help_text='Preserved for audit even after user deletion', max_length=254)),
                ('request_type', models.CharField(choices=[('ACCESS', 'Data Access'), ('EXPORT', 'Data Export/Portability'), ('DELETION', 'Account Deletion/Erasure'), ('CORRECTION', 'Data Correction'), ('OBJECTION', 'Processing Objection')], max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled by User')], default='PENDING', max_length=20)),
                ('request_data', models.JSONField(blank=True, default=dict, help_text='Additional data submitted with request (e.g., corrections)')),
                ('response_data', models.JSONField(blank=True, default=dict, help_text='Result data (e.g., export download URL)')),
                ('rejection_reason', models.TextField(blank=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('deletion_summary', models.JSONField(blank=True, default=dict, help_text='Summary of deleted, anonymized, and retained data')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_privacy_requests', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='privacy_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Privacy Request',
                'verbose_name_plural': 'Privacy Requests',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='users_priva_user_id_593fc4_idx'), models.Index(fields=['status', '-created_at'], name='users_priva_status_56a887_idx'), models.Index(fields=['request_type', 'status'], name='users_priva_request_427461_idx')],
            },
        ),
    ]
