# Generated by Django 5.2.1 on 2026-01-13 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_consentrecord_privacyrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='admininvitation',
            name='permissions',
            field=models.JSONField(blank=True, default=dict, help_text='Admin permissions to assign when invitation is accepted'),
        ),
        migrations.AddField(
            model_name='user',
            name='admin_permissions',
            field=models.JSONField(blank=True, default=dict, help_text='Granular admin permissions stored as JSON. Only applies to ADMIN role users.'),
        ),
    ]
