# Generated by Django 5.2.1 on 2026-01-18 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_add_admin_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, help_text='User profile picture', null=True, upload_to='users/avatars/'),
        ),
    ]
