# Generated by Django 5.2.1 on 2026-01-23 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_userprofile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='google_picture_url',
            field=models.URLField(blank=True, help_text='Profile picture URL from Google OAuth (if signed up via Google)', max_length=500, null=True),
        ),
    ]
