# Generated by Django 5.2.1 on 2026-01-26 15:04

from django.db import migrations, models


def migrate_auth_method_forward(apps, schema_editor):
    """
    Populate auth_method for existing users based on their current state:
    1. Users with google_picture_url set → 'google'
    2. Users with usable password (no '!' prefix) → 'password'
    3. All others → 'invitation_pending'
    """
    User = apps.get_model('users', 'User')
    UserProfile = apps.get_model('users', 'UserProfile')

    # Get all users with Google picture URLs
    google_user_ids = set(
        UserProfile.objects.filter(
            google_picture_url__isnull=False
        ).exclude(
            google_picture_url=''
        ).values_list('user_id', flat=True)
    )

    for user in User.objects.all():
        if user.id in google_user_ids:
            user.auth_method = 'google'
        elif user.password and not user.password.startswith('!'):
            user.auth_method = 'password'
        else:
            user.auth_method = 'invitation_pending'
        user.save(update_fields=['auth_method'])


def migrate_auth_method_reverse(apps, schema_editor):
    """Reverse migration - nothing to do as field will be removed."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_userprofile_google_picture_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='auth_method',
            field=models.CharField(
                choices=[
                    ('password', 'Password'),
                    ('google', 'Google OAuth'),
                    ('invitation_pending', 'Invitation Pending')
                ],
                default='invitation_pending',
                help_text='Authentication method: password, google, or invitation_pending',
                max_length=20
            ),
        ),
        migrations.RunPython(migrate_auth_method_forward, migrate_auth_method_reverse),
    ]
