# Generated by Django 5.2.1 on 2025-12-18 05:54

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0005_add_is_tax_inclusive_to_productoption'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text="Venue name (e.g., 'Cabana', 'Open Field')", max_length=200)),
                ('code', models.CharField(help_text="Unique code (e.g., 'CABANA', 'OPEN_FIELD')", max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_overnight', models.BooleanField(default=False, help_text='True for overnight stays (e.g., Cabana with checkout next day)')),
                ('minimum_capacity', models.PositiveIntegerField(default=1, help_text='Minimum guest capacity')),
                ('maximum_capacity', models.PositiveIntegerField(help_text='Maximum guest capacity')),
                ('recommended_capacity', models.PositiveIntegerField(blank=True, help_text='Recommended guest count for optimal experience', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_bookable', models.BooleanField(default=True, help_text='Whether this venue can be booked via client portal')),
                ('location_description', models.TextField(blank=True, help_text='Description of venue location')),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='venues/images/')),
                ('gallery_images', models.JSONField(blank=True, default=list, help_text='List of image URLs for venue gallery')),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Venue',
                'verbose_name_plural': 'Venues',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='VenueOperatingRules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('default_check_in_time', models.TimeField(help_text='Default check-in time (e.g., 14:00 for Cabana)')),
                ('default_checkout_time', models.TimeField(help_text='Default checkout time (e.g., 12:00 for Cabana)')),
                ('checkout_next_day', models.BooleanField(default=False, help_text='If True, checkout time is on the day AFTER check-in (overnight stays)')),
                ('minimum_program_hours', models.DecimalField(decimal_places=1, default=Decimal('1.0'), help_text='Minimum program duration in hours', max_digits=4)),
                ('maximum_program_hours', models.DecimalField(blank=True, decimal_places=1, help_text='Maximum program duration in hours (null = no limit)', max_digits=4, null=True)),
                ('default_program_hours', models.DecimalField(decimal_places=1, default=Decimal('3.0'), help_text='Default program duration in hours', max_digits=4)),
                ('is_fixed_duration', models.BooleanField(default=False, help_text='If True, program duration is fixed and cannot be adjusted by client')),
                ('ingress_hours', models.DecimalField(decimal_places=1, default=Decimal('0.0'), help_text='Setup time before program (e.g., 5-6 hours for Open Field)', max_digits=4)),
                ('egress_hours', models.DecimalField(decimal_places=1, default=Decimal('0.0'), help_text='Teardown time after program (e.g., 1-2 hours)', max_digits=4)),
                ('allow_custom_ingress', models.BooleanField(default=False, help_text='Allow custom ingress time per booking')),
                ('allow_custom_egress', models.BooleanField(default=False, help_text='Allow custom egress time per booking')),
                ('min_ingress_hours', models.DecimalField(decimal_places=1, default=Decimal('0.0'), help_text='Minimum ingress hours when customizable', max_digits=4)),
                ('max_ingress_hours', models.DecimalField(decimal_places=1, default=Decimal('6.0'), help_text='Maximum ingress hours when customizable', max_digits=4)),
                ('min_egress_hours', models.DecimalField(decimal_places=1, default=Decimal('0.0'), help_text='Minimum egress hours when customizable', max_digits=4)),
                ('max_egress_hours', models.DecimalField(decimal_places=1, default=Decimal('2.0'), help_text='Maximum egress hours when customizable', max_digits=4)),
                ('earliest_start_time', models.TimeField(blank=True, help_text='Earliest time a program can start', null=True)),
                ('latest_end_time', models.TimeField(blank=True, help_text='Latest time program can end (e.g., 21:00 for music curfew)', null=True)),
                ('hard_cutoff_time', models.TimeField(blank=True, help_text='Absolute latest time all activities must conclude (e.g., 02:00)', null=True)),
                ('hard_cutoff_next_day', models.BooleanField(default=True, help_text='If True, hard_cutoff_time is on the next day (e.g., 2:00 AM)')),
                ('early_access_minutes', models.PositiveIntegerField(default=60, help_text='Minutes before program when early prep access is allowed')),
                ('early_checkin_allowed', models.BooleanField(default=False, help_text='Allow check-in before default check-in time')),
                ('early_checkin_fee_per_hour', models.DecimalField(blank=True, decimal_places=2, help_text='Fee per hour for early check-in (e.g., 300.00)', max_digits=10, null=True)),
                ('earliest_checkin_time', models.TimeField(blank=True, help_text='Absolute earliest check-in time allowed (e.g., 10:00)', null=True)),
                ('late_checkout_allowed', models.BooleanField(default=True, help_text='Allow checkout after default checkout time')),
                ('late_checkout_fee_per_hour', models.DecimalField(blank=True, decimal_places=2, help_text='Fee per hour for late checkout (e.g., 300.00)', max_digits=10, null=True)),
                ('late_checkout_max_hours', models.PositiveIntegerField(default=4, help_text='Maximum hours for late checkout extension')),
                ('latest_checkout_time', models.TimeField(blank=True, help_text='Absolute latest checkout time allowed', null=True)),
                ('custom_rules', models.JSONField(blank=True, default=dict, help_text='Custom venue rules as JSON')),
                ('venue', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='venue_operating_rules', to='venues.venue')),
            ],
            options={
                'verbose_name': 'Venue Operating Rules',
                'verbose_name_plural': 'Venue Operating Rules',
            },
        ),
        migrations.CreateModel(
            name='PackageVenue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_primary', models.BooleanField(default=False, help_text='Primary venue determines datetime rules (check-in, checkout, duration)')),
                ('access_order', models.PositiveIntegerField(default=1, help_text='Order of venue access (1=first, 2=second, etc.)')),
                ('access_duration_hours', models.DecimalField(blank=True, decimal_places=1, help_text='How long client uses this venue (null = use venue default)', max_digits=4, null=True)),
                ('notes', models.TextField(blank=True, help_text="Notes about this venue's usage in the package (e.g., 'For ceremony only')")),
                ('package', models.ForeignKey(limit_choices_to={'type': 'PACKAGE'}, on_delete=django.db.models.deletion.CASCADE, related_name='package_venues', to='products.productoption')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='venue_packages', to='venues.venue')),
            ],
            options={
                'verbose_name': 'Package Venue',
                'verbose_name_plural': 'Package Venues',
                'ordering': ['access_order', 'venue__name'],
                'unique_together': {('package', 'venue')},
            },
        ),
        migrations.CreateModel(
            name='VenueBlockedDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('reason', models.CharField(max_length=255)),
                ('is_full_day', models.BooleanField(default=True, help_text='If False, only specific hours are blocked')),
                ('blocked_start_time', models.TimeField(blank=True, help_text='Start time of block (if partial day)', null=True)),
                ('blocked_end_time', models.TimeField(blank=True, help_text='End time of block (if partial day)', null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='venue_blocks_created', to=settings.AUTH_USER_MODEL)),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_dates', to='venues.venue')),
            ],
            options={
                'verbose_name': 'Venue Blocked Date',
                'verbose_name_plural': 'Venue Blocked Dates',
                'ordering': ['date', 'blocked_start_time'],
                'indexes': [models.Index(fields=['venue', 'date'], name='venues_venu_venue_i_44244f_idx')],
            },
        ),
    ]
