# Generated by Django 5.2.1 on 2025-12-18 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0002_seed_initial_venues'),
    ]

    operations = [
        migrations.AddField(
            model_name='packagevenue',
            name='hours_contribution',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Hours this venue contributes to package total', max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='packagevenue',
            name='is_bonus',
            field=models.BooleanField(default=False, help_text='True if venue is included free (e.g., cabanas with bundle)'),
        ),
        migrations.AddField(
            model_name='packagevenue',
            name='price_contribution',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Price this venue contributes to package total', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='venue',
            name='is_rentable_standalone',
            field=models.BooleanField(default=False, help_text='Can this venue be rented without a pre-made package?'),
        ),
        migrations.AddField(
            model_name='venue',
            name='standalone_base_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Price when rented as standalone venue', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='venue',
            name='standalone_excess_hour_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Excess hour rate when rented standalone', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='venue',
            name='standalone_included_hours',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Hours included when rented standalone', max_digits=4, null=True),
        ),
    ]
