# Generated by Django 5.2.1 on 2025-12-19 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0015_add_guest_count_fields'),
        ('venues', '0003_venue_custom_package_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='VenueEventTypeConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('base_price', models.DecimalField(blank=True, decimal_places=2, help_text='Base price for this venue+event type (null = use venue default)', max_digits=10, null=True)),
                ('included_hours', models.DecimalField(blank=True, decimal_places=1, help_text='Hours included for this venue+event type (null = use venue default)', max_digits=4, null=True)),
                ('excess_hour_price', models.DecimalField(blank=True, decimal_places=2, help_text='Excess hour rate for this venue+event type (null = use venue default)', max_digits=10, null=True)),
                ('is_all_day_access', models.BooleanField(default=False, help_text='If True, venue has all-day access with no hour limits for this event type')),
                ('default_check_in_time', models.TimeField(blank=True, help_text='Override check-in time for this event type', null=True)),
                ('default_checkout_time', models.TimeField(blank=True, help_text='Override checkout time for this event type', null=True)),
                ('checkout_next_day', models.BooleanField(blank=True, help_text='Override: checkout is next day (for overnight)', null=True)),
                ('maximum_program_hours', models.DecimalField(blank=True, decimal_places=1, help_text='Override maximum program hours (null in override = no limit)', max_digits=4, null=True)),
                ('is_fixed_duration', models.BooleanField(blank=True, help_text='Override: duration is fixed', null=True)),
                ('notes', models.TextField(blank=True, help_text='Internal notes about this configuration')),
                ('event_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='venue_configs', to='events.eventtype')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_type_configs', to='venues.venue')),
            ],
            options={
                'verbose_name': 'Venue Event Type Configuration',
                'verbose_name_plural': 'Venue Event Type Configurations',
                'ordering': ['venue__name', 'event_type__name'],
                'unique_together': {('venue', 'event_type')},
            },
        ),
    ]
