# Generated by Django 5.2.1 on 2026-01-01 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0004_venue_event_type_configuration'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
