# Generated by Django 5.2.1 on 2026-01-07 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0005_add_is_featured_to_venue'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='amenities',
            field=models.JSONField(blank=True, default=list, help_text="List of amenities (e.g., ['Pool', 'Parking', 'Sound System', 'WiFi'])"),
        ),
    ]
