# Generated by Django 5.2.1 on 2026-02-14 03:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0021_alter_eventtype_options_eventtype_featured_image_and_more'),
        ('venues', '0008_seed_all_event_types_and_packages'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='gallery/')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('GENERAL', 'General'), ('WEDDING', 'Wedding'), ('TEAM_BUILDING', 'Team Building'), ('RETREAT', 'Retreat'), ('WORKSHOP', 'Workshop'), ('CAMPING', 'Camping'), ('ATMOSPHERE', 'Atmosphere & Details')], default='GENERAL', max_length=20)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('event_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gallery_photos', to='events.eventtype')),
                ('venue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gallery_photos', to='venues.venue')),
            ],
            options={
                'verbose_name': 'Gallery Photo',
                'verbose_name_plural': 'Gallery Photos',
                'ordering': ['sort_order', '-created_at'],
            },
        ),
    ]
