# Generated by Django 5.2.1 on 2026-02-15 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0021_alter_eventtype_options_eventtype_featured_image_and_more'),
        ('venues', '0009_galleryphoto'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='galleryphoto',
            index=models.Index(fields=['is_active', 'sort_order', '-created_at'], name='venues_gall_is_acti_e172c0_idx'),
        ),
        migrations.AddIndex(
            model_name='galleryphoto',
            index=models.Index(fields=['is_active', 'category'], name='venues_gall_is_acti_9c6864_idx'),
        ),
    ]
