# Generated by Django 5.2.1 on 2026-02-16 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0010_galleryphoto_add_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='venueeventtypeconfiguration',
            name='capacity_label',
            field=models.CharField(blank=True, default='', help_text="Display label for guest capacity on rates page (e.g., '130-150 guests'). May differ from venue's physical capacity.", max_length=100),
        ),
        migrations.AddField(
            model_name='venueeventtypeconfiguration',
            name='includes',
            field=models.JSONField(blank=True, default=list, help_text="List of included features for this venue+event type on rates page (e.g., ['Free prenup venue'])"),
        ),
    ]
