# Generated by Django 5.2.1 on 2026-02-17 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0011_venueeventtypeconfiguration_capacity_label_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryphoto',
            name='category',
            field=models.CharField(choices=[('GENERAL', 'General'), ('WEDDING', 'Wedding'), ('TEAM_BUILDING', 'Team Building'), ('CAMPS_AND_RETREATS', 'Camps & Retreats'), ('WORKSHOP', 'Workshop'), ('ATMOSPHERE', 'Atmosphere & Details')], default='GENERAL', max_length=20),
        ),
    ]
