# Generated by Django 5.2.1 on 2025-06-08 00:19

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunicationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('channel', models.CharField(choices=[('EMAIL', 'Email'), ('SMS', 'SMS')], default='EMAIL', max_length=10)),
                ('category', models.CharField(choices=[('SYSTEM', 'System'), ('MANUAL', 'Manual'), ('AUTO', 'Auto')], default='MANUAL', max_length=10)),
                ('subject_template', models.CharField(blank=True, max_length=200, null=True)),
                ('body_template', models.TextField()),
                ('is_system', models.BooleanField(default=False)),
                ('variables_schema', models.JSONField(blank=True, default=dict, help_text='Expected variables for template')),
            ],
            options={
                'verbose_name': 'Communication Template',
                'verbose_name_plural': 'Communication Templates',
            },
        ),
        migrations.CreateModel(
            name='CommunicationRecord',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('template_name', models.CharField(max_length=100)),
                ('channel', models.CharField(choices=[('EMAIL', 'Email'), ('SMS', 'SMS')], default='EMAIL', max_length=10)),
                ('category', models.CharField(choices=[('SYSTEM', 'System'), ('MANUAL', 'Manual'), ('AUTO', 'Auto')], default='MANUAL', max_length=10)),
                ('recipient', models.EmailField(max_length=254)),
                ('subject', models.CharField(blank=True, max_length=200, null=True)),
                ('body', models.TextField()),
                ('external_message_id', models.CharField(blank=True, max_length=100, null=True)),
                ('delivery_status', models.CharField(choices=[('PENDING', 'Pending'), ('SENT', 'Sent'), ('DELIVERED', 'Delivered'), ('FAILED', 'Failed'), ('BOUNCED', 'Bounced')], default='PENDING', max_length=20)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('is_opened', models.BooleanField(default=False)),
                ('context_data', models.JSONField(blank=True, default=dict)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='communication_records', to=settings.AUTH_USER_MODEL)),
                ('sent_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_communications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Communication Record',
                'verbose_name_plural': 'Communication Records',
                'ordering': ['-created_at'],
            },
        ),
    ]
