# Generated by Django 5.2.1 on 2025-10-04 23:14

from django.db import migrations


def create_quote_sent_template(apps, schema_editor):
    """Create email template for when quote is sent to client"""
    CommunicationTemplate = apps.get_model('communications', 'CommunicationTemplate')

    template_content = '''
<div style="font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; max-width: 700px; margin: 0 auto; border: 1px solid #e0e0e0;">
    <!-- Header -->
    <div style="background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); padding: 40px 30px; text-align: center;">
        <h1 style="color: white; margin: 0; font-size: 32px; font-weight: 300;">Your Quote is Ready!</h1>
        <p style="color: rgba(255,255,255,0.9); margin-top: 10px; font-size: 16px;">LifePlace Retreat & Events Center</p>
    </div>

    <!-- Content -->
    <div style="padding: 40px 30px; background: white;">
        <p style="color: #333; font-size: 16px; line-height: 1.6; margin-bottom: 25px;">
            Dear {{ client_name }},
        </p>

        <p style="color: #555; font-size: 15px; line-height: 1.6; margin-bottom: 30px;">
            Thank you for your interest in LifePlace! We're excited to share your personalized quote for <strong>{{ event_name }}</strong> scheduled for <strong>{{ event_date }}</strong>.
        </p>

        <!-- Quote Details Box -->
        <div style="background: #f8f9fa; border-left: 4px solid #667eea; padding: 25px; margin: 30px 0; border-radius: 4px;">
            <h2 style="color: #333; margin-top: 0; font-size: 20px; margin-bottom: 20px;">Quote Details</h2>

            <table style="width: 100%; border-collapse: collapse;">
                <tr>
                    <td style="padding: 10px 0; color: #666; border-bottom: 1px solid #e0e0e0;">Quote ID:</td>
                    <td style="padding: 10px 0; color: #333; font-weight: 600; text-align: right; border-bottom: 1px solid #e0e0e0;">#{{ quote_id }}</td>
                </tr>
                <tr>
                    <td style="padding: 10px 0; color: #666; border-bottom: 1px solid #e0e0e0;">Event Date:</td>
                    <td style="padding: 10px 0; color: #333; font-weight: 600; text-align: right; border-bottom: 1px solid #e0e0e0;">{{ event_date }}</td>
                </tr>
                <tr>
                    <td style="padding: 15px 0 10px 0; color: #666; font-size: 18px;">Total Amount:</td>
                    <td style="padding: 15px 0 10px 0; color: #667eea; font-weight: bold; text-align: right; font-size: 24px;">₱{{ total_amount }}</td>
                </tr>
            </table>
        </div>

        <!-- Important Information -->
        <div style="background: #fff3cd; border: 1px solid #ffc107; padding: 20px; margin: 30px 0; border-radius: 4px;">
            <h3 style="color: #856404; margin-top: 0; font-size: 16px;">📌 Important Information</h3>
            <ul style="color: #856404; margin: 10px 0; padding-left: 20px; line-height: 1.8;">
                <li>This quote is valid until <strong>{{ valid_until }}</strong></li>
                <li>Review all details carefully</li>
                <li>Contact us if you have any questions or need modifications</li>
            </ul>
        </div>

        <!-- Call to Action -->
        <div style="text-align: center; margin: 40px 0;">
            <p style="color: #666; font-size: 14px; margin-bottom: 15px;">
                Ready to proceed? Please contact us to accept this quote and secure your booking.
            </p>
        </div>

        <p style="color: #666; font-size: 14px; line-height: 1.6; margin-top: 30px;">
            If you have any questions or would like to discuss customization options, please don't hesitate to contact us.
        </p>
    </div>

    <!-- Footer -->
    <div style="background: #f8f9fa; padding: 30px; text-align: center; border-top: 1px solid #e0e0e0;">
        <p style="color: #666; margin: 5px 0; font-size: 14px;">LifePlace Retreat & Events Center</p>
        <p style="color: #999; margin: 5px 0; font-size: 13px;">Creating Memorable Moments for Your Special Day</p>
        <p style="color: #999; margin: 15px 0 5px 0; font-size: 12px;">© 2025 LifePlace. All rights reserved.</p>
    </div>
</div>
    '''

    CommunicationTemplate.objects.get_or_create(
        name='quote_sent_to_client',
        defaults={
            'channel': 'EMAIL',
            'category': 'SYSTEM',
            'subject_template': 'Your Quote for {{ event_name }}',
            'body_template': template_content,
            'variables_schema': {
                'required': ['client_name', 'quote_id', 'total_amount', 'valid_until', 'event_name', 'event_date'],
                'optional': ['quote_version', 'quote_link']
            },
            'is_system': True
        }
    )


def remove_quote_sent_template(apps, schema_editor):
    """Remove the email template"""
    CommunicationTemplate = apps.get_model('communications', 'CommunicationTemplate')
    CommunicationTemplate.objects.filter(name='quote_sent_to_client').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_quote_sent_template, remove_quote_sent_template),
    ]
