# Generated by Django 5.2.1 on 2025-12-18 00:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0003_alter_communicationrecord_created_at_and_more'),
        ('events', '0011_add_accepted_quote_to_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='communicationrecord',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='communication_records', to='events.event'),
        ),
    ]
