# Generated by Django 5.2.1 on 2025-12-20 17:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0004_add_event_to_communication_record'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='communicationrecord',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='communicationrecord',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_communications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='communicationrecord',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.CreateModel(
            name='CommunicationTemplateHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(help_text='Version number of this history entry')),
                ('name', models.CharField(max_length=100)),
                ('channel', models.CharField(max_length=10)),
                ('category', models.CharField(max_length=10)),
                ('subject_template', models.CharField(blank=True, max_length=200, null=True)),
                ('body_template', models.TextField()),
                ('variables_schema', models.JSONField(blank=True, default=dict)),
                ('reason', models.CharField(choices=[('CREATE', 'Initial Creation'), ('UPDATE', 'Manual Update'), ('ROLLBACK', 'Rollback to Previous Version'), ('SYSTEM', 'System Update')], default='UPDATE', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about this change')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='template_changes', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='communications.communicationtemplate')),
            ],
            options={
                'verbose_name': 'Communication Template History',
                'verbose_name_plural': 'Communication Template Histories',
                'ordering': ['-created_at'],
                'unique_together': {('template', 'version')},
            },
        ),
    ]
