# Generated by Django 5.2.1 on 2025-12-21 03:19

from django.db import migrations, models


def set_context_types(apps, schema_editor):
    """
    Set context_type for existing templates based on their name/usage.
    """
    CommunicationTemplate = apps.get_model('communications', 'CommunicationTemplate')

    # Mapping of template names to their context types
    template_context_mapping = {
        # ADMIN context
        'Admin Invitation': 'ADMIN',
        'Admin Role Upgrade': 'ADMIN',

        # CLIENT context
        'Welcome Email': 'CLIENT',
        'Client Invitation': 'CLIENT',
        'Password Reset': 'CLIENT',

        # EVENT context
        'Events - Welcome New Lead': 'EVENT',
        'Wedding Feedback Survey': 'EVENT',
        'Wedding Invoice Email': 'EVENT',

        # BOOKING context
        'Booking Confirmation': 'BOOKING',
        'Booking Reminder': 'BOOKING',
        'Wedding Booking Confirmed': 'BOOKING',
        'Events - Payment Reminder': 'BOOKING',
        'Events - Complete Your Booking': 'BOOKING',

        # QUOTE context
        'Wedding Quote Email': 'QUOTE',
        'quote_sent_to_client': 'QUOTE',

        # CONTRACT context
        'Wedding Contract for E-Signature': 'CONTRACT',

        # NOTIFICATION context
        'System Notification Email': 'NOTIFICATION',
        'System Notification SMS': 'NOTIFICATION',
        'Notification Digest Email': 'NOTIFICATION',

        # MANUAL context (default for unspecified)
        'Manual Email Layout': 'MANUAL',
        'Manual SMS Layout': 'MANUAL',
        'Professional Email Layout': 'MANUAL',
    }

    for template_name, context_type in template_context_mapping.items():
        CommunicationTemplate.objects.filter(name=template_name).update(
            context_type=context_type
        )


def reverse_context_types(apps, schema_editor):
    """
    Reverse migration - set all to MANUAL.
    """
    CommunicationTemplate = apps.get_model('communications', 'CommunicationTemplate')
    CommunicationTemplate.objects.all().update(context_type='MANUAL')


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0005_communicationrecord_deleted_at_and_more'),
    ]

    operations = [
        # First add the new fields with defaults
        migrations.AddField(
            model_name='communicationtemplate',
            name='context_type',
            field=models.CharField(choices=[('CLIENT', 'Client'), ('EVENT', 'Event'), ('BOOKING', 'Booking'), ('QUOTE', 'Quote'), ('CONTRACT', 'Contract'), ('ADMIN', 'Admin'), ('NOTIFICATION', 'Notification'), ('MANUAL', 'Manual')], default='MANUAL', help_text='Determines which variables are available and required objects at send time', max_length=20),
        ),
        migrations.AddField(
            model_name='communicationtemplate',
            name='include_client_context',
            field=models.BooleanField(default=False, help_text='For MANUAL templates: include client variables if client is provided'),
        ),
        migrations.AddField(
            model_name='communicationtemplate',
            name='include_event_context',
            field=models.BooleanField(default=False, help_text='For MANUAL templates: include event variables if event is provided'),
        ),
        migrations.AddField(
            model_name='communicationtemplatehistory',
            name='context_type',
            field=models.CharField(default='MANUAL', max_length=20),
        ),
        migrations.AddField(
            model_name='communicationtemplatehistory',
            name='include_client_context',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='communicationtemplatehistory',
            name='include_event_context',
            field=models.BooleanField(default=False),
        ),
        # Run data migration to set context types
        migrations.RunPython(set_context_types, reverse_context_types),
        # Remove old variables_schema field
        migrations.RemoveField(
            model_name='communicationtemplate',
            name='variables_schema',
        ),
        migrations.RemoveField(
            model_name='communicationtemplatehistory',
            name='variables_schema',
        ),
    ]
