# Generated by Django 5.2.1 on 2025-12-23 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0006_add_context_type_to_templates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communicationrecord',
            name='category',
            field=models.CharField(choices=[('SYSTEM', 'System'), ('MANUAL', 'Manual'), ('AUTO', 'Auto'), ('MARKETING', 'Marketing')], default='MANUAL', max_length=10),
        ),
        migrations.AlterField(
            model_name='communicationtemplate',
            name='category',
            field=models.CharField(choices=[('SYSTEM', 'System'), ('MANUAL', 'Manual'), ('AUTO', 'Auto'), ('MARKETING', 'Marketing')], default='MANUAL', max_length=10),
        ),
    ]
