# Generated by Django 5.2.1 on 2026-01-16 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0007_alter_communicationrecord_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communicationtemplate',
            name='context_type',
            field=models.CharField(choices=[('CLIENT', 'Client'), ('EVENT', 'Event'), ('BOOKING', 'Booking'), ('QUOTE', 'Quote'), ('CONTRACT', 'Contract'), ('ADMIN', 'Admin'), ('NOTIFICATION', 'Notification'), ('MANUAL', 'Manual'), ('PAYMENT', 'Payment'), ('INVOICE', 'Invoice')], default='MANUAL', help_text='Determines which variables are available and required objects at send time', max_length=20),
        ),
    ]
