# Generated by Django 5.2.1 on 2026-01-19 07:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0008_alter_communicationtemplate_context_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailUnsubscribeToken',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('MARKETING', 'Marketing'), ('ALL', 'All')], default='MARKETING', help_text='Email category to unsubscribe from', max_length=20)),
                ('is_used', models.BooleanField(default=False)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField()),
                ('communication_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unsubscribe_tokens', to='communications.communicationrecord')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unsubscribe_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Email Unsubscribe Token',
                'verbose_name_plural': 'Email Unsubscribe Tokens',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_used'], name='communicati_user_id_c6370c_idx'), models.Index(fields=['expires_at'], name='communicati_expires_c6fc28_idx')],
            },
        ),
    ]
