# Generated by Django 5.2.1 on 2026-01-20 05:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0009_emailunsubscribetoken'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailLayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text="Unique identifier for this layout (e.g., 'Standard', 'Premium Client')", max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Internal description of when to use this layout')),
                ('header_template', models.TextField(help_text='HTML for header section. Variables: {{ site_name }}, {{ header_title }}, {{ header_subtitle }}, {{ logo_url }}')),
                ('footer_template', models.TextField(help_text='HTML for footer section. Variables: {{ site_name }}, {{ current_year }}, {{ support_email }}, {{ unsubscribe_link }}')),
                ('wrapper_template', models.TextField(default='<div class="content-wrapper">{{ content }}</div>', help_text='HTML wrapper for content area. MUST include {{ content }} placeholder.')),
                ('base_styles', models.TextField(blank=True, help_text='CSS styles applied before content. Supports {{ primary_color }}, {{ secondary_color }} variables.')),
                ('primary_color', models.CharField(default='#667eea', help_text='Primary brand color (hex format, e.g., #667eea)', max_length=7)),
                ('secondary_color', models.CharField(default='#764ba2', help_text='Secondary brand color for gradients (hex format)', max_length=7)),
                ('logo_url', models.URLField(blank=True, help_text='URL to company logo image')),
                ('is_default', models.BooleanField(default=False, help_text='If true, this layout is used when no layout is explicitly assigned')),
                ('is_active', models.BooleanField(default=True, help_text='Inactive layouts cannot be assigned to templates')),
            ],
            options={
                'verbose_name': 'Email Layout',
                'verbose_name_plural': 'Email Layouts',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='communicationtemplate',
            name='layout',
            field=models.ForeignKey(blank=True, help_text='Email layout to wrap content. Leave empty for SMS or legacy full-HTML templates.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='templates', to='communications.emaillayout'),
        ),
        migrations.CreateModel(
            name='EmailLayoutHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(help_text='Version number of this history entry')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('header_template', models.TextField()),
                ('footer_template', models.TextField()),
                ('wrapper_template', models.TextField()),
                ('base_styles', models.TextField(blank=True)),
                ('primary_color', models.CharField(max_length=7)),
                ('secondary_color', models.CharField(max_length=7)),
                ('logo_url', models.URLField(blank=True)),
                ('reason', models.CharField(choices=[('CREATE', 'Initial Creation'), ('UPDATE', 'Manual Update'), ('ROLLBACK', 'Rollback to Previous Version')], default='UPDATE', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about this change')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='layout_changes', to=settings.AUTH_USER_MODEL)),
                ('layout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='communications.emaillayout')),
            ],
            options={
                'verbose_name': 'Email Layout History',
                'verbose_name_plural': 'Email Layout Histories',
                'ordering': ['-created_at'],
                'unique_together': {('layout', 'version')},
            },
        ),
    ]
