# Generated by Django 5.2.1 on 2026-02-05
# Data migration to create the New Lead Admin Notification email template

from django.db import migrations

TEMPLATE_NAME = 'New Lead Admin Notification'

SUBJECT = '[New Lead] {{ event_name }} - {{ client_name }}'

BODY = """<h2 style="color: #333; margin-top: 0; font-size: 22px; font-weight: 600;">New Quote Request Received</h2>

<p style="color: #666; line-height: 1.6; font-size: 15px;">
    A new quote request has been submitted through the booking flow. Please review and prepare a quote for the client.
</p>

<div style="background: #f0f8ff; padding: 20px; margin: 20px 0; border-left: 4px solid #667eea; border-radius: 4px;">
    <table style="width: 100%; border-collapse: collapse;">
        <tr>
            <td style="padding: 8px 0; color: #666;">Client:</td>
            <td style="padding: 8px 0; color: #333; font-weight: 600; text-align: right;">{{ client_name }}</td>
        </tr>
        <tr>
            <td style="padding: 8px 0; color: #666;">Email:</td>
            <td style="padding: 8px 0; color: #333; text-align: right;">{{ client_email }}</td>
        </tr>
        {% if client_phone %}
        <tr>
            <td style="padding: 8px 0; color: #666;">Phone:</td>
            <td style="padding: 8px 0; color: #333; text-align: right;">{{ client_phone }}</td>
        </tr>
        {% endif %}
        <tr>
            <td style="padding: 8px 0; color: #666;">Event Type:</td>
            <td style="padding: 8px 0; color: #333; font-weight: 600; text-align: right;">{{ event_name }}</td>
        </tr>
        {% if event_date %}
        <tr>
            <td style="padding: 8px 0; color: #666;">Event Date:</td>
            <td style="padding: 8px 0; color: #333; font-weight: 600; text-align: right;">{{ event_date }}</td>
        </tr>
        {% endif %}
        {% if venue_name %}
        <tr>
            <td style="padding: 8px 0; color: #666;">Venue:</td>
            <td style="padding: 8px 0; color: #333; text-align: right;">{{ venue_name }}</td>
        </tr>
        {% endif %}
        {% if total_amount_formatted %}
        <tr>
            <td style="padding: 8px 0; color: #666;">Estimated Value:</td>
            <td style="padding: 8px 0; color: #333; font-weight: 600; text-align: right;">{{ total_amount_formatted }}</td>
        </tr>
        {% endif %}
    </table>
</div>

{% if client_message %}
<div style="margin: 20px 0; padding: 15px; background-color: #f8f9fa; border-radius: 4px;">
    <p style="margin: 0 0 5px 0; color: #666; font-size: 13px; font-weight: 600;">Client Message:</p>
    <p style="margin: 0; color: #333; font-style: italic; line-height: 1.6;">"{{ client_message }}"</p>
</div>
{% endif %}

<p style="color: #666; font-size: 14px; line-height: 1.6; margin-top: 20px;">
    Log in to the admin dashboard to review this lead and prepare a quote.
</p>"""


def create_template(apps, schema_editor):
    CommunicationTemplate = apps.get_model('communications', 'CommunicationTemplate')
    EmailLayout = apps.get_model('communications', 'EmailLayout')

    # Skip if template already exists (e.g., from seed_production_data)
    if CommunicationTemplate.objects.filter(name=TEMPLATE_NAME).exists():
        return

    # Use the default email layout (pk=2, "Professional" layout used by other admin templates)
    layout = None
    try:
        layout = EmailLayout.objects.get(pk=2)
    except EmailLayout.DoesNotExist:
        # Fall back to any available layout
        layout = EmailLayout.objects.first()

    CommunicationTemplate.objects.create(
        name=TEMPLATE_NAME,
        channel='EMAIL',
        category='SYSTEM',
        context_type='EVENT',
        subject_template=SUBJECT,
        body_template=BODY,
        is_system=True,
        layout=layout,
    )


def remove_template(apps, schema_editor):
    CommunicationTemplate = apps.get_model('communications', 'CommunicationTemplate')
    CommunicationTemplate.objects.filter(name=TEMPLATE_NAME).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0010_add_email_layouts'),
    ]

    operations = [
        migrations.RunPython(create_template, remove_template),
    ]
