# Generated by Django 5.2.1 on 2026-02-05
# Data migration to create Questionnaire Sent and Questionnaire Reminder email templates

from django.db import migrations

TEMPLATES = [
    {
        'name': 'Questionnaire Sent to Client',
        'subject': 'Questionnaire for {{ event_name }} - {{ questionnaire_name }}',
        'body': """<h2 style="color: #333; margin-top: 0; font-size: 22px; font-weight: 600;">New Questionnaire to Complete</h2>

<p style="color: #666; line-height: 1.6; font-size: 15px;">
    Hello {{ client_first_name }},
</p>

<p style="color: #666; line-height: 1.6; font-size: 15px;">
    A questionnaire has been sent for your upcoming event. Please complete it at your earliest convenience to help us plan your event perfectly.
</p>

<div style="background: #f0f8ff; padding: 20px; margin: 20px 0; border-left: 4px solid #667eea; border-radius: 4px;">
    <table style="width: 100%; border-collapse: collapse;">
        <tr>
            <td style="padding: 8px 0; color: #666;">Questionnaire:</td>
            <td style="padding: 8px 0; color: #333; font-weight: 600; text-align: right;">{{ questionnaire_name }}</td>
        </tr>
        <tr>
            <td style="padding: 8px 0; color: #666;">Event:</td>
            <td style="padding: 8px 0; color: #333; font-weight: 600; text-align: right;">{{ event_name }}</td>
        </tr>
        {% if event_date %}
        <tr>
            <td style="padding: 8px 0; color: #666;">Event Date:</td>
            <td style="padding: 8px 0; color: #333; text-align: right;">{{ event_date }}</td>
        </tr>
        {% endif %}
        {% if due_date %}
        <tr>
            <td style="padding: 8px 0; color: #666;">Due Date:</td>
            <td style="padding: 8px 0; color: #333; font-weight: 600; text-align: right;">{{ due_date }}</td>
        </tr>
        {% endif %}
    </table>
</div>

<p style="color: #666; font-size: 14px; line-height: 1.6; margin-top: 20px;">
    You can complete the questionnaire by logging in to your client portal.
</p>""",
    },
    {
        'name': 'Questionnaire Reminder',
        'subject': 'Reminder: Complete Questionnaire for {{ event_name }}',
        'body': """<h2 style="color: #333; margin-top: 0; font-size: 22px; font-weight: 600;">Questionnaire Reminder</h2>

<p style="color: #666; line-height: 1.6; font-size: 15px;">
    Hello {{ client_first_name }},
</p>

<p style="color: #666; line-height: 1.6; font-size: 15px;">
    This is a friendly reminder to complete the questionnaire for your upcoming event. Your responses help us plan your event perfectly.
</p>

<div style="background: #fff3e0; padding: 20px; margin: 20px 0; border-left: 4px solid #FF9800; border-radius: 4px;">
    <table style="width: 100%; border-collapse: collapse;">
        <tr>
            <td style="padding: 8px 0; color: #666;">Questionnaire:</td>
            <td style="padding: 8px 0; color: #333; font-weight: 600; text-align: right;">{{ questionnaire_name }}</td>
        </tr>
        <tr>
            <td style="padding: 8px 0; color: #666;">Event:</td>
            <td style="padding: 8px 0; color: #333; font-weight: 600; text-align: right;">{{ event_name }}</td>
        </tr>
        {% if event_date %}
        <tr>
            <td style="padding: 8px 0; color: #666;">Event Date:</td>
            <td style="padding: 8px 0; color: #333; text-align: right;">{{ event_date }}</td>
        </tr>
        {% endif %}
        {% if due_date %}
        <tr>
            <td style="padding: 8px 0; color: #666;">Due Date:</td>
            <td style="padding: 8px 0; color: #333; font-weight: 600; color: #E65100; text-align: right;">{{ due_date }}</td>
        </tr>
        {% endif %}
    </table>
</div>

{% if is_overdue %}
<div style="background: #fce4ec; padding: 12px 16px; margin: 16px 0; border-radius: 4px;">
    <p style="margin: 0; color: #c62828; font-weight: 600;">This questionnaire is overdue. Please complete it as soon as possible.</p>
</div>
{% endif %}

<p style="color: #666; font-size: 14px; line-height: 1.6; margin-top: 20px;">
    You can complete the questionnaire by logging in to your client portal.
</p>""",
    },
]


def create_templates(apps, schema_editor):
    CommunicationTemplate = apps.get_model('communications', 'CommunicationTemplate')
    EmailLayout = apps.get_model('communications', 'EmailLayout')

    # Use the default email layout (pk=2, "Professional" layout)
    layout = None
    try:
        layout = EmailLayout.objects.get(pk=2)
    except EmailLayout.DoesNotExist:
        layout = EmailLayout.objects.first()

    for template_data in TEMPLATES:
        if CommunicationTemplate.objects.filter(name=template_data['name']).exists():
            continue

        CommunicationTemplate.objects.create(
            name=template_data['name'],
            channel='EMAIL',
            category='SYSTEM',
            context_type='EVENT',
            subject_template=template_data['subject'],
            body_template=template_data['body'],
            is_system=True,
            layout=layout,
        )


def remove_templates(apps, schema_editor):
    CommunicationTemplate = apps.get_model('communications', 'CommunicationTemplate')
    for template_data in TEMPLATES:
        CommunicationTemplate.objects.filter(name=template_data['name']).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0011_add_new_lead_admin_notification_template'),
    ]

    operations = [
        migrations.RunPython(create_templates, remove_templates),
    ]
