# Generated by Django 5.2.1 on 2025-08-25

from django.db import migrations, connection


def fix_options_field(apps, schema_editor):
    """
    Fix the options field from array to JSONB in PostgreSQL.
    This migration only runs on PostgreSQL databases.
    """
    if connection.vendor == 'postgresql':
        with schema_editor.connection.cursor() as cursor:
            # Check if the column exists as an array type
            cursor.execute("""
                SELECT data_type 
                FROM information_schema.columns
                WHERE table_name = 'questionnaires_questionnairefield'
                AND column_name = 'options'
            """)
            result = cursor.fetchone()
            
            if result and result[0] == 'ARRAY':
                print("Converting questionnaires_questionnairefield.options from ARRAY to JSONB...")
                
                # First, alter the column to text with array converted to JSON
                cursor.execute("""
                    ALTER TABLE questionnaires_questionnairefield
                    ALTER COLUMN options TYPE text 
                    USING CASE 
                        WHEN options IS NULL THEN '[]'
                        WHEN array_length(options, 1) IS NULL THEN '[]'
                        ELSE array_to_json(options)::text
                    END;
                """)
                
                # Then alter from text to jsonb
                cursor.execute("""
                    ALTER TABLE questionnaires_questionnairefield
                    ALTER COLUMN options TYPE jsonb 
                    USING options::jsonb;
                """)
                
                print("  ✓ Converted questionnaires_questionnairefield.options to JSONB")


def reverse_fix_options_field(apps, schema_editor):
    """
    Reverse the field type change (for rollback).
    This migration only runs on PostgreSQL databases.
    """
    if connection.vendor == 'postgresql':
        with schema_editor.connection.cursor() as cursor:
            # Check if the column exists as jsonb
            cursor.execute("""
                SELECT data_type 
                FROM information_schema.columns
                WHERE table_name = 'questionnaires_questionnairefield'
                AND column_name = 'options'
            """)
            result = cursor.fetchone()
            
            if result and result[0] == 'jsonb':
                # Convert jsonb array back to text array
                cursor.execute("""
                    ALTER TABLE questionnaires_questionnairefield
                    ALTER COLUMN options TYPE text[] 
                    USING (
                        CASE 
                            WHEN jsonb_typeof(options) = 'array' THEN
                                ARRAY(SELECT jsonb_array_elements_text(options))
                            ELSE
                                ARRAY[]::text[]
                        END
                    );
                """)


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaires', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(
            fix_options_field,
            reverse_fix_options_field,
        ),
    ]