# Generated by Django 5.2.1 on 2025-08-25 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaires', '0002_fix_options_array_to_jsonb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnairefield',
            name='options',
            field=models.JSONField(blank=True, default=list, help_text='List of option strings'),
        ),
    ]
