# Generated by Django 5.2.1 on 2025-12-18 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaires', '0004_alter_questionnaire_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnairefield',
            name='is_guest_count',
            field=models.BooleanField(default=False, help_text="If true, this field's numeric response will contribute to event guest count"),
        ),
    ]
