# Generated by Django 5.2.1 on 2026-01-12 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaires', '0005_add_guest_count_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnairefield',
            name='allowed_file_types',
            field=models.JSONField(blank=True, default=list, help_text="Allowed file extensions e.g., ['pdf', 'jpg', 'png'] (for file fields only)"),
        ),
        migrations.AddField(
            model_name='questionnairefield',
            name='description',
            field=models.TextField(blank=True, help_text='Optional helper text shown below the field to guide users'),
        ),
        migrations.AddField(
            model_name='questionnairefield',
            name='max_file_size_mb',
            field=models.PositiveIntegerField(default=10, help_text='Maximum file size in MB (for file fields only)'),
        ),
        migrations.AddField(
            model_name='questionnairefield',
            name='max_files',
            field=models.PositiveIntegerField(default=1, help_text='Maximum number of files allowed (for file fields only)'),
        ),
        migrations.AddField(
            model_name='questionnairefield',
            name='placeholder',
            field=models.CharField(blank=True, help_text='Placeholder text shown inside the input field', max_length=255),
        ),
        migrations.AddField(
            model_name='questionnairefield',
            name='show_conditions',
            field=models.JSONField(blank=True, default=dict, help_text="Conditions for when to show this field. Format: {'logic': 'AND', 'conditions': [{'field_id': '5', 'operator': 'equals', 'value': 'yes'}]}"),
        ),
        migrations.AlterField(
            model_name='questionnairefield',
            name='is_guest_count',
            field=models.BooleanField(default=False, help_text="DEPRECATED: Use 'guests' field type instead. If true, numeric response contributes to guest count"),
        ),
        migrations.AlterField(
            model_name='questionnairefield',
            name='type',
            field=models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('date', 'Date'), ('time', 'Time'), ('boolean', 'Yes/No'), ('select', 'Select'), ('multi-select', 'Multi-Select'), ('email', 'Email'), ('phone', 'Phone'), ('file', 'File Upload'), ('guests', 'Guest Count')], max_length=20),
        ),
    ]
