# Generated by Django 5.2.1 on 2026-01-26 05:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0018_add_performance_indexes'),
        ('questionnaires', '0006_add_field_enhancements'),
        ('workflows', '0012_add_trigger_after_stage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventQuestionnaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SENT', 'Sent'), ('PARTIAL', 'Partially Complete'), ('COMPLETE', 'Complete')], default='PENDING', max_length=20)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_questionnaires', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_questionnaires', to='events.event')),
                ('questionnaire', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='event_assignments', to='questionnaires.questionnaire')),
                ('sent_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_questionnaires', to=settings.AUTH_USER_MODEL)),
                ('workflow_stage', models.ForeignKey(blank=True, help_text='Workflow stage that created this assignment (if automated)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questionnaire_assignments', to='workflows.workflowstage')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('event', 'questionnaire')},
            },
        ),
        migrations.CreateModel(
            name='EventQuestionnaireActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(choices=[('CREATED', 'Created'), ('SENT', 'Sent'), ('VIEWED', 'Viewed by Client'), ('RESPONSE_ADDED', 'Response Added'), ('STATUS_CHANGED', 'Status Changed'), ('REMINDER_SENT', 'Reminder Sent'), ('COMPLETED', 'Completed')], max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('action_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('event_questionnaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='questionnaires.eventquestionnaire')),
            ],
            options={
                'verbose_name_plural': 'Event questionnaire activities',
                'ordering': ['-created_at'],
            },
        ),
    ]
