# Generated by Django 5.2.1 on 2025-09-10 22:24

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EncryptionKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('key_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('version', models.IntegerField(db_index=True)),
                ('algorithm', models.CharField(default='AES-256-GCM', max_length=50)),
                ('purpose', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('retired_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('is_primary', models.BooleanField(default=False)),
                ('rotation_reason', models.CharField(blank=True, max_length=200)),
                ('security_level', models.CharField(default='STANDARD', max_length=20)),
                ('key_derivation_info', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'messaging_encryption_keys',
                'ordering': ['-version'],
                'indexes': [models.Index(fields=['purpose', 'is_active'], name='messaging_e_purpose_596b5e_idx'), models.Index(fields=['is_primary', 'purpose'], name='messaging_e_is_prim_78caae_idx'), models.Index(fields=['version', 'purpose'], name='messaging_e_version_c63400_idx')],
            },
        ),
        migrations.CreateModel(
            name='KeyRotationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('rotation_reason', models.CharField(max_length=200)),
                ('initiated_by', models.CharField(max_length=150)),
                ('records_migrated', models.IntegerField(default=0)),
                ('migration_duration', models.DurationField(blank=True, null=True)),
                ('rotation_status', models.CharField(choices=[('INITIATED', 'Initiated'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('ROLLED_BACK', 'Rolled Back')], default='INITIATED', max_length=20)),
                ('error_details', models.JSONField(blank=True, default=dict)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('new_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rotation_logs_new', to='messaging.encryptionkey')),
                ('old_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rotation_logs_old', to='messaging.encryptionkey')),
            ],
            options={
                'db_table': 'messaging_key_rotation_log',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ConnectionAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('connection_id', models.CharField(max_length=64, unique=True)),
                ('session_id', models.CharField(blank=True, max_length=64)),
                ('username', models.CharField(blank=True, max_length=150)),
                ('user_role', models.CharField(blank=True, max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('origin', models.URLField(blank=True)),
                ('connected_at', models.DateTimeField(auto_now_add=True)),
                ('disconnected_at', models.DateTimeField(blank=True, null=True)),
                ('duration', models.DurationField(blank=True, null=True)),
                ('connection_data', models.JSONField(blank=True, default=dict)),
                ('disconnect_reason', models.CharField(blank=True, max_length=200)),
                ('messages_sent', models.IntegerField(default=0)),
                ('messages_received', models.IntegerField(default=0)),
                ('errors_count', models.IntegerField(default=0)),
                ('is_suspicious', models.BooleanField(default=False)),
                ('was_blocked', models.BooleanField(default=False)),
                ('auth_failures', models.IntegerField(default=0)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'messaging_connection_audit',
                'ordering': ['-connected_at'],
                'indexes': [models.Index(fields=['connected_at'], name='messaging_c_connect_0506a6_idx'), models.Index(fields=['ip_address', 'connected_at'], name='messaging_c_ip_addr_399f54_idx'), models.Index(fields=['user', 'connected_at'], name='messaging_c_user_id_d7ea3a_idx'), models.Index(fields=['is_suspicious'], name='messaging_c_is_susp_95681a_idx')],
            },
        ),
        migrations.CreateModel(
            name='MessageAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('event_type', models.CharField(choices=[('CONNECTION_OPENED', 'Connection Opened'), ('CONNECTION_CLOSED', 'Connection Closed'), ('CONNECTION_FAILED', 'Connection Failed'), ('MESSAGE_SENT', 'Message Sent'), ('MESSAGE_RECEIVED', 'Message Received'), ('MESSAGE_EDITED', 'Message Edited'), ('MESSAGE_DELETED', 'Message Deleted'), ('THREAD_JOINED', 'Thread Joined'), ('THREAD_LEFT', 'Thread Left'), ('TYPING_STARTED', 'Typing Started'), ('TYPING_STOPPED', 'Typing Stopped'), ('ROOM_JOINED', 'Room Joined'), ('ROOM_LEFT', 'Room Left'), ('ERROR_OCCURRED', 'Error Occurred'), ('RATE_LIMITED', 'Rate Limited'), ('CONTENT_BLOCKED', 'Content Blocked')], db_index=True, max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('username', models.CharField(blank=True, max_length=150)),
                ('user_role', models.CharField(blank=True, max_length=20)),
                ('connection_id', models.CharField(blank=True, max_length=64)),
                ('session_id', models.CharField(blank=True, max_length=64)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('thread_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('message_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('room_name', models.CharField(blank=True, max_length=200)),
                ('event_data', models.JSONField(blank=True, default=dict)),
                ('error_details', models.JSONField(blank=True, default=dict)),
                ('content_length', models.IntegerField(blank=True, null=True)),
                ('content_hash', models.CharField(blank=True, max_length=64)),
                ('is_encrypted', models.BooleanField(default=False)),
                ('is_suspicious', models.BooleanField(default=False)),
                ('risk_score', models.IntegerField(default=0)),
                ('was_blocked', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'messaging_audit_log',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['timestamp', 'event_type'], name='messaging_a_timesta_753882_idx'), models.Index(fields=['user', 'timestamp'], name='messaging_a_user_id_e46043_idx'), models.Index(fields=['ip_address', 'timestamp'], name='messaging_a_ip_addr_822b99_idx'), models.Index(fields=['thread_id', 'timestamp'], name='messaging_a_thread__464e7e_idx'), models.Index(fields=['is_suspicious', 'timestamp'], name='messaging_a_is_susp_7884e8_idx'), models.Index(fields=['risk_score', 'timestamp'], name='messaging_a_risk_sc_2e3428_idx')],
            },
        ),
    ]
