# Generated by Django 5.2.1 on 2026-01-20 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0002_alter_message_created_at_alter_message_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagethread',
            name='category',
            field=models.CharField(blank=True, choices=[('billing', 'Billing & Payments'), ('event', 'Event Changes/Questions'), ('technical', 'Technical Issues'), ('general', 'General Inquiry')], help_text='Category for support inquiries', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='messagethread',
            name='thread_type',
            field=models.CharField(choices=[('conversation', 'Conversation'), ('support', 'Support Inquiry')], default='conversation', help_text='Type of thread - conversation or support inquiry', max_length=20),
        ),
    ]
