# Generated by Django 5.2.1 on 2025-09-17 23:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_remove_event_event_workflow_idx_and_more'),
        ('messaging', '0002_messagethread_message_threadparticipant_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='messagethread',
            name='archived_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when the thread was archived', null=True),
        ),
        migrations.AddField(
            model_name='messagethread',
            name='archived_by',
            field=models.ForeignKey(blank=True, help_text='User who archived this thread', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archived_message_threads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='messagethread',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('waiting', 'Waiting for Response'), ('resolved', 'Resolved'), ('archived', 'Archived')], default='active', max_length=10),
        ),
        migrations.AddIndex(
            model_name='messagethread',
            index=models.Index(fields=['status', 'archived_at'], name='messaging_m_status_4f6856_idx'),
        ),
    ]
