# Generated by Django 5.2.1 on 2025-08-27 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='securityevent',
            new_name='security_ev_timesta_a07168_idx',
            old_name='core_securi_timesta_4b7c3c_idx',
        ),
        migrations.RenameIndex(
            model_name='securityevent',
            new_name='security_ev_ip_addr_038026_idx',
            old_name='core_securi_ip_addr_9e8b1f_idx',
        ),
        migrations.RenameIndex(
            model_name='securityevent',
            new_name='security_ev_user_id_6a5f21_idx',
            old_name='core_securi_user_id_7a2d4e_idx',
        ),
        migrations.RenameIndex(
            model_name='securityevent',
            new_name='security_ev_severit_db68de_idx',
            old_name='core_securi_severit_1c5f8a_idx',
        ),
    ]
