# Generated by Django 5.2.1 on 2025-10-08 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_core_securi_timesta_4b7c3c_idx_security_ev_timesta_a07168_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='securityevent',
            name='user_agent',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='securityevent',
            name='username',
            field=models.CharField(blank=True, default='anonymous', max_length=150),
        ),
    ]
