# backend/core/domains/payments/tests/test_models.py

from datetime import date, timedelta
from decimal import Decimal

from django.contrib.auth import get_user_model
from django.test import TestCase

from core.domains.events.models import Event, EventType
from core.domains.payments.models import (
    Invoice,
    InvoiceLineItem,
    Payment,
    PaymentGateway,
    PaymentMethod,
    PaymentTransaction,
)
from core.domains.products.models import ProductCategory, ProductOption

User = get_user_model()


class PaymentModelTestCase(TestCase):
    """Test cases for Payment model"""

    def setUp(self):
        """Set up test data"""
        self.user = User.objects.create_user(
            email="test@example.com", first_name="Test", last_name="User", role="CLIENT"
        )

        self.event_type = EventType.objects.create(name="Wedding", description="Wedding events")

        self.event = Event.objects.create(
            client=self.user,
            event_type=self.event_type,
            name="Test Wedding",
            start_date=date.today() + timedelta(days=30),
            status="CONFIRMED",
        )

        self.gateway, _ = PaymentGateway.objects.get_or_create(
            code="stripe",
            defaults={
                "name": "Stripe Test",
                "is_active": True,
            },
        )
        # Always update config to ensure test settings are applied
        self.gateway.config = {"test_mode": True}
        self.gateway.is_active = True
        self.gateway.save()

        self.payment_method = PaymentMethod.objects.create(
            gateway=self.gateway, user=self.user, token_reference="test_token_123", last_four="4242", is_default=True
        )

    def test_payment_creation(self):
        """Test basic payment creation"""
        payment = Payment.objects.create(
            event=self.event,
            payment_method=self.payment_method,
            amount=Decimal("2500.00"),
            currency="PHP",
            status="PENDING",
            due_date=date.today() + timedelta(days=7),
        )

        self.assertEqual(payment.amount, Decimal("2500.00"))
        self.assertEqual(payment.currency, "PHP")
        self.assertEqual(payment.status, "PENDING")
        self.assertIsNotNone(payment.payment_number)
        # Payment numbers are generated by PaymentNumberService
        self.assertTrue(len(payment.payment_number) > 0)

    def test_payment_number_generation(self):
        """Test automatic payment number generation"""
        payment1 = Payment.objects.create(
            event=self.event,
            payment_method=self.payment_method,
            amount=Decimal("1000.00"),
            currency="PHP",
            due_date=date.today() + timedelta(days=7),
        )

        payment2 = Payment.objects.create(
            event=self.event,
            payment_method=self.payment_method,
            amount=Decimal("1500.00"),
            currency="PHP",
            due_date=date.today() + timedelta(days=7),
        )

        self.assertNotEqual(payment1.payment_number, payment2.payment_number)
        self.assertTrue(len(payment1.payment_number) > 0)
        self.assertTrue(len(payment2.payment_number) > 0)

    def test_php_currency_formatting(self):
        """Test PHP currency formatting via format_amount_with_currency"""
        payment = Payment.objects.create(
            event=self.event,
            payment_method=self.payment_method,
            amount=Decimal("2500.00"),
            currency="PHP",
            due_date=date.today() + timedelta(days=7),
        )

        formatted = payment.format_amount_with_currency()
        # Should contain the peso symbol and 2,500
        self.assertIn("2,500", formatted)

    def test_usd_currency_formatting(self):
        """Test USD currency formatting via format_amount_with_currency.

        CurrencySettings defaults decimal_places=0 (PHP business context),
        so USD amounts are formatted without decimals unless CurrencySettings
        is explicitly configured with decimal_places=2.
        """
        payment = Payment.objects.create(
            event=self.event,
            payment_method=self.payment_method,
            amount=Decimal("2500.50"),
            currency="USD",
            due_date=date.today() + timedelta(days=7),
        )

        formatted = payment.format_amount_with_currency()
        # With default CurrencySettings (decimal_places=0), USD amounts
        # are formatted without decimals: "$2,500" or "$2,501"
        self.assertIn("$", formatted)
        self.assertIn("2,50", formatted)  # At least contains 2,50x

    def test_payment_status_transitions(self):
        """Test valid payment status transitions"""
        payment = Payment.objects.create(
            event=self.event,
            payment_method=self.payment_method,
            amount=Decimal("1000.00"),
            currency="PHP",
            status="PENDING",
            due_date=date.today() + timedelta(days=7),
        )

        # Valid transition: PENDING -> COMPLETED
        payment.status = "COMPLETED"
        payment.save()
        self.assertEqual(payment.status, "COMPLETED")

    def test_payment_state_machine_methods(self):
        """Test payment state machine integration methods"""
        payment = Payment.objects.create(
            event=self.event,
            payment_method=self.payment_method,
            amount=Decimal("2500.00"),
            currency="PHP",
            status="CREATED",
            due_date=date.today() + timedelta(days=7),
        )

        # Test can_transition_to
        self.assertTrue(payment.can_transition_to("PENDING"))

        # Test get_valid_transitions
        valid = payment.get_valid_transitions()
        self.assertIsInstance(valid, list)

        # Test is_terminal_state
        self.assertFalse(payment.is_terminal_state())


class PaymentGatewayModelTestCase(TestCase):
    """Test cases for PaymentGateway model"""

    def test_gateway_creation(self):
        """Test payment gateway creation"""
        gateway, created = PaymentGateway.objects.get_or_create(
            code="stripe",
            defaults={
                "name": "Stripe Production",
                "is_active": True,
            },
        )
        # Always update config to ensure test settings are applied
        gateway.config = {"publishable_key": "pk_test_123", "secret_key": "sk_test_123", "webhook_secret": "whsec_123"}
        gateway.is_active = True
        gateway.save()

        self.assertEqual(gateway.code, "stripe")
        self.assertTrue(gateway.is_active)
        self.assertIn("publishable_key", gateway.config)

    def test_gateway_config_encryption(self):
        """Test that gateway config is properly encrypted"""
        gateway, created = PaymentGateway.objects.get_or_create(
            code="stripe",
            defaults={
                "name": "Stripe Test",
                "is_active": True,
            },
        )
        gateway.config = {"secret_key": "sk_test_secret_key_123"}
        gateway.save()

        # Config should be accessible as dict
        self.assertIsInstance(gateway.config, dict)
        self.assertEqual(gateway.config["secret_key"], "sk_test_secret_key_123")

        # Raw database value should be encrypted (this requires checking the actual field implementation)
        gateway.refresh_from_db()
        self.assertIsInstance(gateway.config, dict)


class InvoiceModelTestCase(TestCase):
    """Test cases for Invoice and InvoiceLineItem models"""

    def setUp(self):
        """Set up test data"""
        self.user = User.objects.create_user(
            email="client@test.com", first_name="Test", last_name="Client", role="CLIENT"
        )

        self.event_type = EventType.objects.create(name="Wedding")
        self.event = Event.objects.create(
            client=self.user,
            event_type=self.event_type,
            name="Test Wedding",
            start_date=date.today() + timedelta(days=30),
        )

        self.category = ProductCategory.objects.create(name="Wedding Packages")
        self.product = ProductOption.objects.create(
            name="Premium Package",
            base_price=Decimal("2500.00"),
            currency="PHP",
            category=self.category,
            type="PACKAGE",
        )

    def test_invoice_creation(self):
        """Test invoice creation"""
        invoice = Invoice.objects.create(
            event=self.event,
            client=self.user,
            total_amount=Decimal("2800.00"),
            tax_amount=Decimal("300.00"),
            subtotal=Decimal("2500.00"),
            currency="PHP",
            status="DRAFT",
            issue_date=date.today(),
            due_date=date.today() + timedelta(days=30),
        )

        self.assertEqual(invoice.total_amount, Decimal("2800.00"))
        self.assertEqual(invoice.currency, "PHP")
        self.assertEqual(invoice.status, "DRAFT")
        self.assertIsNotNone(invoice.invoice_id)

    def test_invoice_line_item_creation(self):
        """Test invoice line item creation and total calculation"""
        invoice = Invoice.objects.create(
            event=self.event,
            client=self.user,
            total_amount=Decimal("0.00"),
            tax_amount=Decimal("0.00"),
            subtotal=Decimal("0.00"),
            currency="PHP",
            issue_date=date.today(),
            due_date=date.today() + timedelta(days=30),
        )

        line_item = InvoiceLineItem.objects.create(
            invoice=invoice,
            product=self.product,
            description="Premium Wedding Package",
            quantity=1,
            unit_price=Decimal("2500.00"),
            total=Decimal("2500.00"),
            tax_rate=Decimal("12.00"),
        )

        self.assertEqual(line_item.total, Decimal("2500.00"))

    def test_invoice_status_transitions(self):
        """Test invoice status transitions"""
        invoice = Invoice.objects.create(
            event=self.event,
            client=self.user,
            total_amount=Decimal("2800.00"),
            tax_amount=Decimal("300.00"),
            subtotal=Decimal("2500.00"),
            currency="PHP",
            status="DRAFT",
            issue_date=date.today(),
            due_date=date.today() + timedelta(days=30),
        )

        # DRAFT -> ISSUED
        invoice.status = "ISSUED"
        invoice.save()
        self.assertEqual(invoice.status, "ISSUED")

        # ISSUED -> PAID
        invoice.status = "PAID"
        invoice.save()
        self.assertEqual(invoice.status, "PAID")

    def test_invoice_paid_amount_property(self):
        """Test invoice paid_amount computed property"""
        invoice = Invoice.objects.create(
            event=self.event,
            client=self.user,
            total_amount=Decimal("2500.00"),
            tax_amount=Decimal("300.00"),
            subtotal=Decimal("2200.00"),
            currency="PHP",
            status="ISSUED",
            issue_date=date.today(),
            due_date=date.today() + timedelta(days=30),
        )

        # No payments yet
        self.assertEqual(invoice.paid_amount, Decimal("0.00"))
        self.assertFalse(invoice.is_fully_paid)


class PaymentTransactionModelTestCase(TestCase):
    """Test cases for PaymentTransaction model"""

    def setUp(self):
        """Set up test data"""
        self.user = User.objects.create_user(
            email="test@example.com", first_name="Test", last_name="User", role="CLIENT"
        )

        self.event_type = EventType.objects.create(name="Wedding")
        self.event = Event.objects.create(
            client=self.user,
            event_type=self.event_type,
            name="Test Wedding",
            start_date=date.today() + timedelta(days=30),
        )

        self.gateway, _ = PaymentGateway.objects.get_or_create(
            code="stripe",
            defaults={
                "name": "Stripe Test",
                "is_active": True,
            },
        )
        self.gateway.is_active = True
        self.gateway.save()

        self.payment_method = PaymentMethod.objects.create(
            gateway=self.gateway, user=self.user, token_reference="test_token_123"
        )

        self.payment = Payment.objects.create(
            event=self.event,
            payment_method=self.payment_method,
            amount=Decimal("2500.00"),
            currency="PHP",
            due_date=date.today() + timedelta(days=7),
        )

    def test_transaction_creation(self):
        """Test payment transaction creation"""
        txn = PaymentTransaction.objects.create(
            payment=self.payment,
            gateway=self.gateway,
            transaction_id="pi_test_123456",
            status="COMPLETED",
            amount=Decimal("2500.00"),
            currency="PHP",
            response_data={"status": "succeeded", "id": "pi_test_123456"},
        )

        self.assertEqual(txn.transaction_id, "pi_test_123456")
        self.assertEqual(txn.status, "COMPLETED")
        self.assertEqual(txn.amount, Decimal("2500.00"))
        self.assertIn("status", txn.response_data)

    def test_failed_transaction(self):
        """Test failed transaction handling"""
        txn = PaymentTransaction.objects.create(
            payment=self.payment,
            gateway=self.gateway,
            transaction_id="pi_test_failed",
            status="FAILED",
            amount=Decimal("2500.00"),
            currency="PHP",
            error_message="Your card was declined.",
            response_data={"error": {"code": "card_declined"}},
        )

        self.assertEqual(txn.status, "FAILED")
        self.assertIsNotNone(txn.error_message)

    def test_refund_transaction(self):
        """Test that multiple transactions can be created for same payment"""
        # First create a successful charge
        PaymentTransaction.objects.create(
            payment=self.payment,
            gateway=self.gateway,
            transaction_id="pi_test_123456",
            status="COMPLETED",
            amount=Decimal("2500.00"),
            currency="PHP",
        )

        # Then create a refund transaction (separate record)
        refund_txn = PaymentTransaction.objects.create(
            payment=self.payment,
            gateway=self.gateway,
            transaction_id="re_test_123456",
            status="COMPLETED",
            amount=Decimal("2500.00"),
            currency="PHP",
        )

        self.assertEqual(refund_txn.transaction_id, "re_test_123456")
        self.assertEqual(refund_txn.amount, Decimal("2500.00"))

        # Both transactions should exist for this payment
        self.assertEqual(PaymentTransaction.objects.filter(payment=self.payment).count(), 2)
