# Generated by Django 5.2.1 on 2025-12-23 00:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityBreach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('breach_id', models.CharField(max_length=50, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('breach_type', models.CharField(choices=[('UNAUTHORIZED_ACCESS', 'Unauthorized Access'), ('DATA_THEFT', 'Data Theft'), ('DATA_LEAK', 'Data Leak'), ('RANSOMWARE', 'Ransomware'), ('PHISHING', 'Phishing'), ('INSIDER_THREAT', 'Insider Threat'), ('SYSTEM_COMPROMISE', 'System Compromise'), ('OTHER', 'Other')], max_length=30)),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], max_length=20)),
                ('status', models.CharField(choices=[('DETECTED', 'Detected'), ('INVESTIGATING', 'Under Investigation'), ('CONFIRMED', 'Confirmed Breach'), ('CONTAINED', 'Contained'), ('NOTIFYING', 'Notifying Affected Parties'), ('RESOLVED', 'Resolved'), ('FALSE_POSITIVE', 'False Positive')], default='DETECTED', max_length=20)),
                ('detected_at', models.DateTimeField()),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('contained_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('affected_users_count', models.PositiveIntegerField(default=0)),
                ('affected_records_count', models.PositiveIntegerField(default=0)),
                ('involves_spi', models.BooleanField(default=False)),
                ('data_types_affected', models.JSONField(default=list)),
                ('attack_vector', models.TextField(blank=True)),
                ('vulnerabilities_exploited', models.TextField(blank=True)),
                ('containment_actions', models.TextField(blank=True)),
                ('remediation_steps', models.TextField(blank=True)),
                ('prevention_measures', models.TextField(blank=True)),
                ('npc_notified', models.BooleanField(default=False)),
                ('npc_notified_at', models.DateTimeField(blank=True, null=True)),
                ('npc_reference_number', models.CharField(blank=True, max_length=100)),
                ('users_notified', models.BooleanField(default=False)),
                ('users_notified_at', models.DateTimeField(blank=True, null=True)),
                ('incident_lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='led_breaches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Security Breach',
                'verbose_name_plural': 'Security Breaches',
                'ordering': ['-detected_at'],
            },
        ),
        migrations.CreateModel(
            name='BreachNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notification_type', models.CharField(choices=[('NPC_INITIAL', 'NPC Initial Notification'), ('NPC_FULL_REPORT', 'NPC Full Report'), ('USER_EMAIL', 'User Email Notification'), ('USER_SMS', 'User SMS Notification'), ('USER_IN_APP', 'User In-App Notification'), ('INTERNAL', 'Internal Stakeholder')], max_length=30)),
                ('recipient', models.CharField(max_length=255)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('content', models.TextField()),
                ('delivery_status', models.CharField(default='SENT', max_length=50)),
                ('breach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='security.securitybreach')),
            ],
            options={
                'verbose_name': 'Breach Notification',
                'verbose_name_plural': 'Breach Notifications',
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='AffectedUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('data_exposed', models.JSONField(default=list)),
                ('notified', models.BooleanField(default=False)),
                ('notified_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('breach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affected_users', to='security.securitybreach')),
            ],
            options={
                'verbose_name': 'Affected User',
                'verbose_name_plural': 'Affected Users',
                'unique_together': {('breach', 'user')},
            },
        ),
    ]
