# Generated by Django 5.2.1 on 2025-06-26 19:55

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0003_event_current_stage_event_last_contacted_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('code', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('SYSTEM', 'System'), ('EVENT', 'Event Management'), ('TASK', 'Task Management'), ('PAYMENT', 'Payment Processing'), ('CLIENT', 'Client Management'), ('CONTRACT', 'Contract Management'), ('WORKFLOW', 'Workflow Updates'), ('COMMUNICATION', 'Communication Updates')], default='SYSTEM', max_length=100)),
                ('icon', models.CharField(blank=True, help_text='Material UI icon name', max_length=50)),
                ('color', models.CharField(blank=True, help_text='Hex color code', max_length=7)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('NORMAL', 'Normal'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='NORMAL', max_length=20)),
                ('default_title_template', models.CharField(max_length=255)),
                ('default_content_template', models.TextField()),
                ('default_email_template', models.TextField(blank=True)),
                ('default_sms_template', models.CharField(blank=True, max_length=160)),
                ('is_active', models.BooleanField(default=True)),
                ('is_system', models.BooleanField(default=False, help_text='System notifications cannot be disabled')),
                ('supports_email', models.BooleanField(default=True)),
                ('supports_sms', models.BooleanField(default=False)),
                ('auto_read_after_days', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('action_url', models.CharField(blank=True, max_length=500)),
                ('context_data', models.JSONField(blank=True, default=dict)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_via', models.JSONField(blank=True, default=list, help_text='List of delivery methods used')),
                ('delivery_attempts', models.JSONField(blank=True, default=dict)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_expired', models.BooleanField(default=False)),
                ('client', models.ForeignKey(blank=True, limit_choices_to={'role': 'CLIENT'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client_notifications', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='events.event')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('notification_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='notifications.notificationtype')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('email_enabled', models.BooleanField(default=True)),
                ('sms_enabled', models.BooleanField(default=False)),
                ('in_app_enabled', models.BooleanField(default=True)),
                ('system_email', models.BooleanField(default=True)),
                ('system_sms', models.BooleanField(default=False)),
                ('system_in_app', models.BooleanField(default=True)),
                ('event_email', models.BooleanField(default=True)),
                ('event_sms', models.BooleanField(default=False)),
                ('event_in_app', models.BooleanField(default=True)),
                ('task_email', models.BooleanField(default=True)),
                ('task_sms', models.BooleanField(default=False)),
                ('task_in_app', models.BooleanField(default=True)),
                ('payment_email', models.BooleanField(default=True)),
                ('payment_sms', models.BooleanField(default=True)),
                ('payment_in_app', models.BooleanField(default=True)),
                ('client_email', models.BooleanField(default=True)),
                ('client_sms', models.BooleanField(default=False)),
                ('client_in_app', models.BooleanField(default=True)),
                ('contract_email', models.BooleanField(default=True)),
                ('contract_sms', models.BooleanField(default=False)),
                ('contract_in_app', models.BooleanField(default=True)),
                ('workflow_email', models.BooleanField(default=False)),
                ('workflow_sms', models.BooleanField(default=False)),
                ('workflow_in_app', models.BooleanField(default=True)),
                ('communication_email', models.BooleanField(default=False)),
                ('communication_sms', models.BooleanField(default=False)),
                ('communication_in_app', models.BooleanField(default=True)),
                ('quiet_hours_enabled', models.BooleanField(default=False)),
                ('quiet_hours_start', models.TimeField(blank=True, null=True)),
                ('quiet_hours_end', models.TimeField(blank=True, null=True)),
                ('digest_frequency', models.CharField(choices=[('IMMEDIATE', 'Immediate'), ('HOURLY', 'Hourly Digest'), ('DAILY', 'Daily Digest'), ('WEEKLY', 'Weekly Digest')], default='IMMEDIATE', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
                ('disabled_types', models.ManyToManyField(blank=True, help_text='Specific notification types to disable', related_name='users_disabled', to='notifications.notificationtype')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NotificationDigest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('frequency', models.CharField(choices=[('HOURLY', 'Hourly'), ('DAILY', 'Daily'), ('WEEKLY', 'Weekly')], max_length=20)),
                ('period_start', models.DateTimeField()),
                ('period_end', models.DateTimeField()),
                ('notification_count', models.PositiveIntegerField(default=0)),
                ('is_sent', models.BooleanField(default=False)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('delivery_methods', models.JSONField(default=list)),
                ('notifications', models.ManyToManyField(related_name='digests', to='notifications.notification')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_digests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('user', 'frequency', 'period_start')},
            },
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', '-created_at'], name='notificatio_recipie_a972ce_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', 'is_read'], name='notificatio_recipie_4e3567_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['notification_type', '-created_at'], name='notificatio_notific_c4ec61_idx'),
        ),
    ]
