# Generated by Django 5.2.1 on 2025-12-22 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_notification_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationpreference',
            name='marketing_email',
            field=models.BooleanField(default=False, help_text='User has explicitly consented to receive marketing emails'),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='marketing_in_app',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='marketing_sms',
            field=models.BooleanField(default=False, help_text='User has explicitly consented to receive marketing SMS'),
        ),
        migrations.AlterField(
            model_name='notificationtype',
            name='category',
            field=models.CharField(choices=[('SYSTEM', 'System'), ('EVENT', 'Event Management'), ('TASK', 'Task Management'), ('PAYMENT', 'Payment Processing'), ('CLIENT', 'Client Management'), ('CONTRACT', 'Contract Management'), ('WORKFLOW', 'Workflow Updates'), ('COMMUNICATION', 'Communication Updates'), ('MARKETING', 'Marketing & Promotions')], default='SYSTEM', max_length=100),
        ),
    ]
