# Generated by Django 5.2.1 on 2025-12-22 12:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_add_marketing_consent_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationpreference',
            name='client_push',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='communication_push',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='contract_push',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='event_push',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='marketing_push',
            field=models.BooleanField(default=False, help_text='User has explicitly consented to receive marketing push notifications'),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='payment_push',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='push_enabled',
            field=models.BooleanField(default=True, help_text='Enable push notifications to mobile devices'),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='system_push',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='task_push',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='workflow_push',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notificationtype',
            name='supports_push',
            field=models.BooleanField(default=True, help_text='Whether this notification type can be sent via push'),
        ),
        migrations.CreateModel(
            name='DevicePushToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('token', models.CharField(db_index=True, help_text='Expo push token (ExponentPushToken[xxx])', max_length=255)),
                ('device_id', models.CharField(blank=True, help_text='Unique device identifier for token management', max_length=255)),
                ('device_type', models.CharField(choices=[('ios', 'iOS'), ('android', 'Android'), ('web', 'Web')], default='ios', max_length=20)),
                ('device_name', models.CharField(blank=True, help_text="User-friendly device name (e.g., 'John's iPhone')", max_length=255)),
                ('is_active', models.BooleanField(default=True, help_text='Set to False when DeviceNotRegisteredError is received')),
                ('last_used_at', models.DateTimeField(blank=True, help_text='Last time a push was successfully sent to this device', null=True)),
                ('failure_count', models.PositiveIntegerField(default=0, help_text='Consecutive failure count for automatic deactivation')),
                ('app_version', models.CharField(blank=True, help_text='App version when token was registered', max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='push_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_active'], name='notif_push_user_active_idx'), models.Index(fields=['token'], name='notif_push_token_idx')],
                'unique_together': {('user', 'token')},
            },
        ),
    ]
