# Generated by Django 5.2.1 on 2026-01-29
# Data migration to ensure admin users have email notifications enabled

from django.db import migrations
import logging

logger = logging.getLogger(__name__)


def enable_admin_email_notifications(apps, schema_editor):
    """
    Enable email notifications for all admin users.

    Admin notifications are operational/transactional communications necessary
    for business operations (new leads, events, payments, etc.) and fall under
    "legitimate interest" for GDPR purposes. They should be enabled by default.

    This migration:
    1. Ensures all existing admin users have email_enabled=True
    2. Ensures all critical notification categories are enabled for admins
    """
    User = apps.get_model('users', 'User')
    NotificationPreference = apps.get_model('notifications', 'NotificationPreference')

    # Get all admin users
    admin_users = User.objects.filter(role='ADMIN', is_active=True)

    updated_count = 0
    created_count = 0

    for admin in admin_users:
        # Get or create notification preferences
        prefs, created = NotificationPreference.objects.get_or_create(user=admin)

        if created:
            created_count += 1
            logger.info(f"Created notification preferences for admin: {admin.email}")

        # Check if email was disabled and needs to be enabled
        needs_update = False

        # Enable global email if disabled
        if not prefs.email_enabled:
            prefs.email_enabled = True
            needs_update = True
            logger.info(f"Enabled email_enabled for admin: {admin.email}")

        # Enable critical notification categories for admins
        critical_categories = [
            'event_email',      # New events/leads
            'client_email',     # New clients
            'payment_email',    # Payment notifications
            'contract_email',   # Contract notifications
            'system_email',     # System notifications
            'task_email',       # Task assignments
        ]

        for category in critical_categories:
            if not getattr(prefs, category, True):
                setattr(prefs, category, True)
                needs_update = True
                logger.info(f"Enabled {category} for admin: {admin.email}")

        if needs_update:
            prefs.save()
            updated_count += 1

    logger.info(
        f"Admin email notification migration complete: "
        f"{updated_count} updated, {created_count} created"
    )


def reverse_migration(apps, schema_editor):
    """
    Reverse migration - no action needed.
    We don't want to disable emails when reversing this migration.
    """
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_add_push_notification_support'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(
            enable_admin_email_notifications,
            reverse_migration,
        ),
    ]
